### ISSUE TITLE
Allow users to get help without requiring an auth token

### ISSUE THREAD

**Issue by ResidentMario** [Kaggle/kaggle-api#10]
Currently running a `help` commands returns an auth error:

```sh
kaggle datasets list -h
Unauthorized: you must download an API key from https://www.kaggle.com/<username>/account
```

Telling users they're unauthorized to look up function signatures is a weird thing to do. It'd be better if, for these specific queries, this requirement was dropped.

**Comment by giuscri** [comment]
As I understand this, it's outside the scope of this project. Backend requires authentication too (check https://www.kaggle.com/api/v1/competitions/list)
