### ISSUE TITLE
ModuleNotFoundError: No module named 'kaggle.competitions'

### ISSUE THREAD

**Issue by adriangrepo** [Kaggle/kaggle-api#101]
In a python 3.6 virtual env I ran:

`pip3 install kaggle`

I copied the kaggle.json file to .kaggle directory under user in linux.

Then in a jupyter lab notebook I ran:

`import kaggle`
`print(kaggle)
#>><module 'kaggle' from '/home/me/.virtualenvs/myvenv/lib/python3.6/site-packages/kaggle/__init__.py'>`

then I ran:

`from kaggle.competitions import twosigmanews`

and got the following error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-25118fdba524> in <module>()
----> 1 from kaggle.competitions import twosigmanews
      2 # You can only call make_env() once, so don't lose it!
      3 env = twosigmanews.make_env()
      4 print('Done!')

ModuleNotFoundError: No module named 'kaggle.competitions'

**Comment by rysteboe** [comment]
That's not how the API can be used programatically.  I haven't tested this, but you'll need to do something to the effect of:

```
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
files = api.competition_download_files("twosigmanews")
api.competitions_submit("submission.csv", "my submission message", "twosigmanews")
```

The python part of the API is not documented, only the CLI level.  Please browse `kaggle_api_extended` to see what you can do with it.

**Comment by adriangrepo** [comment]
I realised the code I was trying to run was for a kaggle kernel, not a local kernel.

**Comment by Joxman98** [comment]
I have the same problem, can you tell me how did you solve it?

**Comment by zhasulan** [comment]
And I have the same problem

**Comment by paulperry** [comment]
@Joxman98 @zhasulan , it's not solvable.  `twosigmanews` is not an available module and cannot be imported.  Period.

**Comment by Joxman98** [comment]
@paulperry so how can I solve it?
I'm a noob on this things.

**Comment by paulperry** [comment]
You have two options: use the Kaggle kernels, which is what Kaggle wants you to do, or rewrite the module yourself (it doesn’t do much, it just loads the data).

**Comment by jiapei100** [comment]
> That's not how the API can be used programatically. I haven't tested this, but you'll need to do something to the effect of:
> 
> ```
> from kaggle.api.kaggle_api_extended import KaggleApi
> 
> api = KaggleApi()
> files = api.competition_download_files("twosigmanews")
> api.competitions_submit("submission.csv", "my submission message", "twosigmanews")
> ```
> The python part of the API is not documented, only the CLI level. Please browse `kaggle_api_extended` to see what you can do with it.

```console
two-sigma-financial-news python eda-feature-engineering-and-everything.py 
{'text/html': '<script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: \'local\'};</script><script type="text/javascript">if (window.MathJax) {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script><script>requirejs.config({paths: { \'plotly\': [\'https://cdn.plot.ly/plotly-latest.min\']},});if(!window._Plotly) {require([\'plotly\'],function(plotly) {window._Plotly=plotly;});}</script>', 'text/vnd.plotly.v1+html': '<script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: \'local\'};</script><script type="text/javascript">if (window.MathJax) {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script><script>requirejs.config({paths: { \'plotly\': [\'https://cdn.plot.ly/plotly-latest.min\']},});if(!window._Plotly) {require([\'plotly\'],function(plotly) {window._Plotly=plotly;});}</script>'}
Traceback (most recent call last):
  File "eda-feature-engineering-and-everything.py", line 57, in <module>
    files = api.competition_download_files("twosigmanews")
  File "~/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 674, in competition_download_files
    files = self.competition_list_files(competition)
  File "~/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 591, in competition_list_files
    self.competitions_data_list_files_with_http_info(id=competition))
  File "~/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api.py", line 418, in competitions_data_list_files_with_http_info
    collection_formats=collection_formats)
  File "~/.local/lib/python3.6/site-packages/kaggle/api_client.py", line 334, in call_api
    _preload_content, _request_timeout)
  File "~/.local/lib/python3.6/site-packages/kaggle/api_client.py", line 165, in __call_api
    _request_timeout=_request_timeout)
  File "~/.local/lib/python3.6/site-packages/kaggle/api_client.py", line 355, in request
    headers=headers)
  File "~/.local/lib/python3.6/site-packages/kaggle/rest.py", line 251, in GET
    query_params=query_params)
  File "~/.local/lib/python3.6/site-packages/kaggle/rest.py", line 241, in request
    raise ApiException(http_resp=r)
kaggle.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Set-Cookie': 'XSRF-TOKEN=CfDJ8LdUzqlsSWBPr4Ce3rb9VL97E4HspItE4cjR11R9OUJ_pLpWYMk0lbzwxomnZ12ltFFvWPyfknr0f6CQNdrnaRocjQyzl4KoL7B6IAsUpe3lpyOyfStLRdJBDuwxzLrSh7611u1TvbUZRiZcW9k1j-s; path=/, XSRF-TOKEN=CfDJ8LdUzqlsSWBPr4Ce3rb9VL97E4HspItE4cjR11R9OUJ_pLpWYMk0lbzwxomnZ12ltFFvWPyfknr0f6CQNdrnaRocjQyzl4KoL7B6IAsUpe3lpyOyfStLRdJBDuwxzLrSh7611u1TvbUZRiZcW9k1j-s; path=/; samesite=strict, ARRAffinity=4ff21036757ad84cb57c733a43e23d5e3533f456e7a16692f8c88349723abafa;Path=/;HttpOnly;Domain=www.kaggle.com', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'X-Powered-By': 'ASP.NET', 'Date': 'Thu, 17 Jan 2019 02:41:55 GMT', 'Content-Length': '0'})
```

**Comment by rysteboe** [comment]
There were some communication problems between me and the rest of my team on this - my fault entirely.  The API likely will not work properly with Two Sigma or certain other KO competitions.  While this is on my radar, it's not something that I will be able to fix in the short term.

**Comment by dylan7rdgz** [comment]
I need to use this function
GCS_DS_PATH = KaggleDatasets().get_gcs_path('tpu-getting-started')
but KaggleDatasets is part of kaggle_datasets as per 
https://www.kaggle.com/ryanholbrook/create-your-first-submission
Where is  get_gcs_path() defined?

**Comment by Mohsi76** [comment]
i have this error can you help to solve? peptide requirements already satisfied?

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[30], line 1
----> 1 import amp_pd_peptide
      2 env = amp_pd_peptide.make_env()
      3 iter_test = env.iter_test()

ModuleNotFoundError: No module named 'amp_pd_peptide'

**Comment by helloworld-chhanda** [comment]
for conda environment please intsall:
```
conda install kaggle
conda install conda-forge::kaggle

```
