### ISSUE TITLE
"404 - Not Found" when downloading dataset from Google Colab

### ISSUE THREAD

**Issue by raimanu-ds** [Kaggle/kaggle-api#110]
Hello,

Up until yesterday, I was able to download the dataset from Bluebook Bulldozers while running Google Colab. (My Kaggle credentials are stored in Google Drive.)
However, since today, I keep getting an "404 - Not Found" error every time I run the code cells below.

Is someone else having this issue and is there something I can do to fix this ?
Thanks.

````
!pip install kaggle

Output: 
Requirement already satisfied: kaggle in /usr/local/lib/python3.6/dist-packages (1.4.7.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from kaggle) (2.5.3)
Requirement already satisfied: urllib3<1.23.0,>=1.15 in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.22)
Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from kaggle) (2018.10.15)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.11.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.2.6)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from kaggle) (2.18.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from kaggle) (4.27.0)
Requirement already satisfied: Unidecode>=0.04.16 in /usr/local/lib/python3.6/dist-packages (from python-slugify->kaggle) (1.0.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle) (2.6)
````
````from googleapiclient.discovery import build
import io, os
from googleapiclient.http import MediaIoBaseDownload
from google.colab import auth

auth.authenticate_user()

drive_service = build('drive', 'v3')
results = drive_service.files().list(
        q="name = 'kaggle.json'", fields="files(id)").execute()
kaggle_api_key = results.get('files', [])

filename = "/root/.kaggle/kaggle.json"
os.makedirs(os.path.dirname(filename), exist_ok=True)

request = drive_service.files().get_media(fileId=kaggle_api_key[0]['id'])
fh = io.FileIO(filename, 'wb')
downloader = MediaIoBaseDownload(fh, request)
done = False
while done is False:
    status, done = downloader.next_chunk()
    print("Download %d%%." % int(status.progress() * 100))
os.chmod(filename, 600)

Output:
Download 100%.
````

````
!kaggle competitions download -c bluebook-for-bulldozers -p /content/kaggle

Output: 
404 - Not Found
````

**Comment by raimanu-ds** [comment]
Sorry, I opened an issue... I tried the above code again this morning and it now works...

**Comment by howard-scu** [comment]
The same issue.
It works yesterday, but do not work today.

**Comment by jgoodman8** [comment]
Same thing today. Yesterday it worked.

**Comment by iamsd9** [comment]
I had the same issue when I tried to installing kaggle  API with the different command it worked for me
!pip install -q kaggle

**Comment by aadil-srivastava01** [comment]
Didn't wor

> I had the same issue when I tried to installing kaggle API with the different command it worked for me
> !pip install -q kaggle

Didn't worked for me :'(

**Comment by jiteshm17** [comment]
If you are using Ubuntu or any other Linux distribution, try switching to Windows. I am not sure why but this actually worked for me.

**Comment by Santiago8888** [comment]
please reopen

**Comment by ginkobab** [comment]
I found somebody on Kaggle suggesting to reset runtime (not restart) and rerun, and it worked for me!

**Comment by Rameshwar-Sharma** [comment]
This error is because of below reason, see message.
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
