### ISSUE TITLE
Can't download competition files

### ISSUE THREAD

**Issue by evaezekwem** [Kaggle/kaggle-api#112]
I have configured Kaggle api on my computer before now. Created the .kaggle folder which contains the kaggle.json file where my username and api key resides.

After the initial setup, I was able to download data sets from Kaggle using the api but after a while it stopped working. I have requested a new api key are deleted the old kaggle.json file but still thesame issues. Any help will be appreciated. Thanks.
![kaggle download error](https://user-images.githubusercontent.com/28124360/47646273-afaef180-db73-11e8-961a-d3f159b65356.PNG)

**Comment by evaezekwem** [comment]
I already looked at the fix in [#97](https://github.com/Kaggle/kaggle-api/issues/97). Unlike the suggestion in the fix I already have my "kaggle.json file" in the ".kaggle" folder within my root folder. But I still have the same issue. Here is a code to show you that I have everything setup already.
![screenshot 34](https://user-images.githubusercontent.com/28124360/47659719-d1b96b80-db95-11e8-9fe9-053b7962a4d6.png)

**Comment by rysteboe** [comment]
Try updating to 1.5.0 and seeing if the improved error message helps.  The problem is very likely that your API token is in the wrong spot, but the messaging around that was only just improved in #109.

**Comment by evaezekwem** [comment]
I am having troubles updating to version 1.5.0. pip can't find it.


![screenshot 35](https://user-images.githubusercontent.com/28124360/47733095-d189a080-dc67-11e8-8e85-52778790e745.png)
![Uploading Screenshot (35).png]()

**Comment by rysteboe** [comment]
The command for downloading a specific version is `pip install $package==$version` (ex. `pip install kaggle==1.5.0`).  If you `pip install` an already installed package, it won't update that package.  To do an update, run `pip install --upgrade kaggle`.
