### ISSUE TITLE
How to change the contents of dataset-metadata.jason file in google colaboratory 

### ISSUE THREAD

**Issue by maryam2013** [Kaggle/kaggle-api#118]
Hi every one,
as it is given below, I have written the "api_token" in the Jason file by dump.
`!pip install kaggle` 
  `!mkdir .kaggle` 
   `!touch .kaggle/kaggle.json` 
    `api_token = {"username":"x","key":"bber45dmn87hg35d9kjh65f5f8fnhgtr5"}` 
     `import json` 
    `import  zipfile`
     `import  os`
     `with open('/root/.kaggle/kaggle.json', 'w') as file:` 
      `json.dump(api_token,file)` 
      `!chmod 600 /root/.kaggle/kaggle.json` 

      `!kaggle datasets init -p Music/`
     `!cat Music/dataset-metadata.json` 

the outputs are as follows:
{
  "title": "INSERT_TITLE_HERE",
  "id": "x/INSERT_SLUG_HERE",
  "licenses": [
{
 "name": "CC0-1.0"
    }
   ]
 }

My question is how I can change the contents of "dataset-metadata.json" file?
On the other words, I want to edit the value of "title" and convert it from "INSERT_TITLE_HERE" to  "Mary" and also change the value of "id" from "x/INSERT_SLUG_HERE" to x/Mary, but I do know whether I should apply dump to change the value or some commands specified for google collaboratory?
Any answers will be appreciated.

**Comment by maryam2013** [comment]
Hi every one,
after searching, I found out that with this command "%%writefile Music/dataset-metadata.json", 
which specially used for google collaborator you will be able to edit .jason files in the folders of google collaborator shell.

%%writefile Music/dataset-metadata.json
{
  "title": "My Title",
  "id": "x/MY_SLUG",
  "licenses": [
{
 "name": "CC0-1.0"
    }
   ]
 }

**Comment by Naman-Bhalla** [comment]
You can also use the File Explorer in Colab. Right click the metadata file, download it, then fill it on your local machine and upload to colab.
Finally use !mv command to move it to the desired location.
`!mv dataset-metadata.json dataset/`

<img width="361" alt="screenshot 2018-11-10 at 1 34 23 am" src="https://user-images.githubusercontent.com/6305474/48285510-d2e97300-e488-11e8-86f2-19cba2372e3e.png">
<img width="345" alt="screenshot 2018-11-10 at 1 34 13 am" src="https://user-images.githubusercontent.com/6305474/48285509-d2e97300-e488-11e8-914e-92d390718aa3.png">

**Comment by maryam2013** [comment]
> You can also use the File Explorer in Colab. Right click the metadata file, download it, then fill it on your local machine and upload to colab.
> Finally use !mv command to move it to the desired location.
> `!mv dataset-metadata.json dataset/`
> 
> <img alt="screenshot 2018-11-10 at 1 34 23 am" width="361" src="https://user-images.githubusercontent.com/6305474/48285510-d2e97300-e488-11e8-86f2-19cba2372e3e.png">
> 
> <img alt="screenshot 2018-11-10 at 1 34 13 am" width="345" src="https://user-images.githubusercontent.com/6305474/48285509-d2e97300-e488-11e8-914e-92d390718aa3.png">

Hi Naman,
I am so grateful for the responding.

**Comment by rysteboe** [comment]
Looks like this is resolved?

**Comment by maryam2013** [comment]
> Looks like this is resolved?

Hi resteboe,
Yes it has resolved.

**Comment by arhana-k** [comment]
Hey, while uploading the json file it's throwing an error.
NotebookMissingRequiredFieldsError: nbformat,nbformat_minor
CustomError: NotebookMissingRequiredFieldsError: nbformat,nbformat_minor
    at new cL (https://ssl.gstatic.com/colaboratory-static/common/83000cfdeaaaac268732a3603d63496c/external_binary.js:2253:251)
    at LO (https://ssl.gstatic.com/colaboratory-static/common/83000cfdeaaaac268732a3603d63496c/external_binary.js:2499:549)
    at va.program_ (https://ssl.gstatic.com/colaboratory-static/common/83000cfdeaaaac268732a3603d63496c/external_binary.js:3601:253)
    at za (https://ssl.gstatic.com/colaboratory-static/common/83000cfdeaaaac268732a3603d63496c/external_binary.js:16:57)
    at va.next_ (https://ssl.gstatic.com/colaboratory-static/common/83000cfdeaaaac268732a3603d63496c/external_binary.js:14:195)
    at kaa.next (https://ssl.gstatic.com/colaboratory-static/common/83000cfdeaaaac268732a3603d63496c/external_binary.js:17:48)
    at b (https://ssl.gstatic.com/colaboratory-static/common/83000cfdeaaaac268732a3603d63496c/external_binary.js:17:309)
