### ISSUE TITLE
suggestion of CLI defaults

### ISSUE THREAD

**Issue by cottrell** [Kaggle/kaggle-api#127]
It might make sense for the default --path to be a directory of the competition name in the current directory instead of just dumping the files there.

For example, I ran two downloads in the same directory and some of the files stomped over each other so I'll be repulling severl GB. I don't mind but you might if this human error is high enough.

This is the command that defaults to current (for example) for reference

     kaggle competitions download -c PLAsTiCC-2018

**Comment by Philmod** [comment]
That's working as expected.
