### ISSUE TITLE
Can't submit

### ISSUE THREAD

**Issue by nwbvt** [Kaggle/kaggle-api#128]
I get the following error when I try to submit a file to a competition
 kaggle competitions submit -f results_16.csv -m 7e0ada34830c00c989a4d84c1a97630c36240561 human-protein-atlas-image-classification
  0%|                                                                | 0.00/559k [00:00<?, ?B/s]
'file' object has no attribute 'readable'
Could not submit to competition

**Comment by nwbvt** [comment]
It looks like a python 2 issue.  It works on python 3

**Comment by rysteboe** [comment]
Python 2 is not supported.  Please use Python 3 instead.
