### ISSUE TITLE
API limits

### ISSUE THREAD

**Issue by silviutofan92** [Kaggle/kaggle-api#132]
Hello, 

Could you please share what the rate limits are on the API, and what is the reset/throttling mechanism?

Thank you.

**Comment by rysteboe** [comment]
Because the API is still in a beta state, rate limits are something that we're still toying with.  Are you having any particular problems with rate limits?  We had a couple of problems this morning that likely resulted in API calls failing for unrelated reasons.

**Comment by marscod** [comment]
What is the limit on [competition_download_file](https://github.com/Kaggle/kaggle-api/blob/49057db362903d158b1e71a43d888b981dd27159/kaggle/api/kaggle_api_extended.py#L665)?  
```json
{"code":429,"message":"TooManyRequests"}
```

**Comment by marscod** [comment]
@pizzaz93 any idea on this?
Thanks

**Comment by pizzaz93** [comment]
Hi @marscod 
We don't publish specific rate limit numbers, is there a specific bug or issue you are experiencing?

**Comment by marscod** [comment]
Thanks @pizzaz93 for the reply.  I can download dataset through website but I couldn't download it through API. I'm pretty sure, it comes from server side. I already removed and reinstall Kaggle API as suggested in some discussion forums but it didn't work.
```
$ kaggle competitions download -c titanic

429 - Too Many Requests
```

**Comment by marscod** [comment]
I also generated a new API key.

**Comment by jplotts** [comment]
Hi @marscod - There are separate limits for the API requests vs the web requests.  As Peretz says, we don't publish the specific numbers, but we believe the limits are sufficient for most normal uses.  If you think we've missed something, please provide more details about what you're trying to do.  How many datasets are you trying to download?  Are you doing other large operations with the API?  You might just need to spread your API requests over a longer time period.

**Comment by marscod** [comment]
Thanks @jplotts for the quick reply. I am trying to download few competitions at once but it seems that some competitions includes a large number of files and it causes this error. if I know your restriction/limitations, I'll follow the criteria to avoid this type of issue on my side.

**Comment by QasimWani** [comment]
hey - trying to use the kaggle api but i'm seeing a ton of rate limits even after waiting for 30 minutes. I want to download competition data but it won't let me due to rate limits caused by DownloadDataFile service. Anyone know?
