### ISSUE TITLE
500 internal server error on pushing kaggle kernel from GCP, pythonanywhere shell

### ISSUE THREAD

**Issue by arjunaraoc** [Kaggle/kaggle-api#138]
Version:
Kaggle API 1.5.1.1

I tried to push my kernel and received the error as given below
$ kaggle kernels push
500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api

My kernel is at https://www.kaggle.com/arjunaraoc/telugu-wikipedia-anonymous-edits-analysis

I have followed the instructions as detailed in https://www.kaggle.com/rtatman/dashboarding-with-notebooks-day-3

**Comment by arjunaraoc** [comment]
Looks like if the kernel is using internet, it is not allowing push. I tried with a simple kernel with python and it worked.

**Comment by etheleon** [comment]
Your notebook must follow the same name in kaggle, and the metajson should have the id_no

**Comment by Philmod** [comment]
I can't reproduce this bug, feel free to reopen if you are still experiencing it.
