### ISSUE TITLE
Can't download dataset: KeyError: 'content-length'

### ISSUE THREAD

**Issue by dczerniawko** [Kaggle/kaggle-api#140]
Hi,
I have `Kaggle API 1.5.1.1` and I can't download dataset:
```
$ kaggle datasets download -d new-york-city/nypd-motor-vehicle-collisions
Traceback (most recent call last):
  File "/home/daria/.local/bin/kaggle", line 11, in <module>
    load_entry_point('kaggle==1.5.1.1', 'console_scripts', 'kaggle')()
  File "/home/daria/.local/lib/python3.6/site-packages/kaggle/cli.py", line 50, in main
    out = args.func(**command_args)
  File "/home/daria/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 1186, in dataset_download_cli
    dataset, path=path, unzip=unzip, force=force, quiet=quiet)
  File "/home/daria/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 1138, in dataset_download_files
    self.download_file(response, outfile, quiet)
  File "/home/daria/.local/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 1480, in download_file
    size = int(response.headers['Content-Length'])
  File "/home/daria/.local/lib/python3.6/site-packages/urllib3/_collections.py", line 151, in __getitem__
    val = self._container[key.lower()]
KeyError: 'content-length'
```

**Comment by rysteboe** [comment]
Sorry, I've been on holiday.  Are you still experiencing this?  I'm not seeing any problems with the same API version for that dataset.

**Comment by Praneet460** [comment]
Its working fine in my case. Please check that other commands of Kaggle are working or not. If not then please make sure that you have saved  ```kaggle.json```  file in your  ```.kaggle``` 
 folder and set the path of Python3+ version.

![kaggle_issue_140](https://user-images.githubusercontent.com/23660137/50609937-388d3500-0ef7-11e9-9023-cb0be208e756.PNG)

**Comment by dczerniawko** [comment]
It works now, I can't reproduce the error.

**Comment by zuliani99** [comment]
Hi,
I'm still getting the same error but in the case when I try to get the leaderboard of a competition.
I'm using python 3.8.5 and the kaggle api is the 1.5.12

```
Traceback (most recent call last):
  File "start.py", line 33, in <module>
    main()
  File "start.py", line 25, in main
    kaggle_benchmark()
  File "/home/riccardo/Desktop/AutoML-Benchmark/kaggle_benchmark.py", line 23, in kaggle_benchmark
    api.competition_leaderboard_download(competition=dataset, path=path)
  File "/home/riccardo/.local/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 784, in competition_leaderboard_download
    self.download_file(response, outfile, quiet)
  File "/home/riccardo/.local/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 1584, in download_file
    size = int(response.headers['Content-Length'])
  File "/usr/lib/python3/dist-packages/urllib3/_collections.py", line 156, in __getitem__
    val = self._container[key.lower()]
KeyError: 'content-length'
```

And this is the snippet of code that i run:
```
from kaggle.api.kaggle_api_extended import KaggleApi
from zipfile import ZipFile
import pandas as pd
import os
from algo_functions import fun_autosklearn, fun_autokeras, fun_tpot, fun_h2o, fun_autogluon

def kaggle_benchmark():
    api = KaggleApi()
    api.authenticate()

    dataset = 'titanic'
    path = './datasets/kaggle/' + dataset
    if not os.path.exists(path):

        api.competition_download_files(competition=dataset, path=path)
        api.competition_leaderboard_download(competition=dataset, path=path)

        zf = ZipFile(path + '/' + dataset +  '.zip')
        #extracted data is saved in the same directory as notebook
        zf.extractall(path) 
        zf.close()

        os.remove(path + '/' + dataset +  '.zip')

    train = pd.read_csv(path + '/train.csv')
    test = pd.read_csv(path + '/test.csv')

    print(train.head())
    print(test.head())
```

**Comment by Kevin-Kuruvilla** [comment]
If you encounter a KeyError: 'content-length' with Kaggle's API, it's likely due to an expired kaggle.json file. Regenerating this file from your Kaggle account should resolve the issue, allowing the kaggle datasets download command to work properly.

**Comment by ArunKhare** [comment]
yes i also  had the same issue. Its cause of credentials were not provided in the  os environment

**Comment by hmhkamilo** [comment]
Hi I reproduced the error in a google colab environment seems like an issue in parsing the response like it returns back en empty tuple or something :

uploaded_file = files.upload()
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle competitions download -c llm-detect-ai-generated-text

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-26-d02e9214ede1>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 competition_name = 'llm-detect-ai-generated-text'
----> 7 response = api.competition_download_files(competition_name, path=BASE_PATH, force=True)
      8 
      9 # Print relevant information for debugging

[/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py](https://localhost:8080/#) in competition_download_files(self, competition, path, force, quiet)
    958             self.competitions_data_download_files_with_http_info(
    959                 id=competition, _preload_content=False))
--> 960         url = response.retries.history[0].redirect_location.split('?')[0]
    961         outfile = os.path.join(effective_path,
    962                                competition + '.' + url.split('.')[-1])

IndexError: tuple index out of range

**Comment by hmhkamilo** [comment]
Well I figured it out , I was using an expired token , would be nice to include an authentication error at this point.

**Comment by Philmod** [comment]
Thanks, I created a bug internally: b/321135647
