### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by lisongs1995** [Kaggle/kaggle-api#142]
when I writed kaggle competitions list, it shows a error just as above says. I don't know why, can somebody tell me? python version is 3.7.0, kaggle api is 1.5.1.1. Thx for anyone who can deal my question.

**Comment by ljhOfGithub** [comment]
Hello!Have you fixed the bug?Could you please tell me?Thx.

**Comment by Philmod** [comment]
Could you share a command to reproduce the problem?
