### ISSUE TITLE
Encoding issues when pulling the kernel 

### ISSUE THREAD

**Issue by XMK233** [Kaggle/kaggle-api#146]
When I try to pull a Kernel: ftnext/kaggle-spzcolab-201901 from Kaggle Kernels using Kaggle API, 
`kaggle kernels pull ftnext/kaggle-spzcolab-201901 -p . -m`

I saw this information when python version is 3.6.7: 
`'gbk' codec can't encode character '\u25b6' in position 704: illegal multibyte sequence`

I saw this information when python version is 2.7.15:
`'latin-1' codec can't encode characters in position 178-187: ordinal not in range(256)`

Could this problem happeen because of the Asian characters it has? Do I have a method to solve this problem? 

Thank you.

**Comment by rysteboe** [comment]
Yes, that's exactly why.  This is fixed on my internal version of the API - I'll push that update publically asap.  Will update this then.

**Comment by rysteboe** [comment]
Should be fixed in 1.5.2 - let me know if you have any additional problems.

Thanks for the report!

**Comment by Rock3Yu** [comment]
It still has problem in the ```Kaggle API 1.5.13```
I use the windows cmd to download the output of my kaggle notebook, using ```kaggle kernels output rock3yu/bronze-mold-demo1```
It indead work for about 100 pics, after that the expection shows ```'gbk' codec can't encode character '\u257a' in position 3627: illegal multibyte sequence```
How can I fix the problems?
