### ISSUE TITLE
placing json file in .kaggle/kaggle.json

### ISSUE THREAD

**Issue by KaushalendraKumarSingh** [Kaggle/kaggle-api#15]
cannot find the .kaggle in the specified folder.

**Comment by timoboz** [comment]
Are you using Windows or Linux? 

Generally you should get this file first from our homepage www.kaggle.com -> Your Account -> Create New API token. This will download a ready-to-go JSON file to place in you `[user-home]/.kaggle` folder. If there is no `.kaggle` folder yet, please create it first.

**Comment by coffeedjimmy** [comment]
@KaushalendraKumarSingh 
If you are using the Mac, then in your home folder you can use 'shift' + 'cmd' + '.' to show hidden folders. Then you might find the `.kaggle` folder!

**Comment by sfkiwi** [comment]
I'm using kaggle-api on an Amazon linux instance. I downloaded the kaggle.json from the website (using my personal computer) and then copied it to the ~/.kaggle/ directory that I created on the Amazon linux, but every time I try and run kaggle it tells me

    Unauthorized: you must download an API key from https://www.kaggle.com/<username>/account
    Then put kaggle.json in the folder /home/ubuntu/.kaggle

My personal computer was running MacOS. Does it have to be downloaded on the same machine that you are trying to run it on? If so, I have no way of downloading the kaggle.json from the command line.

**Comment by erick84mm** [comment]
@sfkiwi you need to copy the file itself, not the content, if you copy the content the file will lose the formatting. Try copying with (I'll give you the mac example for windows there is something similar)

mac
scp /Users/<user name>/<file path>/kaggle.json username@server ip address:/home/<destinationp path>/.kaggle/kaggle.json

**Comment by BhavtoshRath** [comment]
I created a folder .kaggle in my local drive (~), moved the json file kaggle.json into it.
But when I run `!kaggle competitions list` on colab, I get the message:
```
Unauthorized: you must download an API key from https://www.kaggle.com/<username>/account
Then put kaggle.json in the folder /content/.kaggle
```
Not sure why is it not reading the file. Has anyone else faced this issue?

**Comment by qifengzhou** [comment]
@BhavtoshRath How you solved the problem? 
I have the same problem here on Ubuntu 16.04. I do have the json file in the right directory as suggested.

**Comment by sagar-m** [comment]
Hi, I am using mac. And in my home directory, the system is not allowing me to add dot before the folder name "kaggle", where I can place the json file. Please help. Thanks!

**Comment by rysteboe** [comment]
@sagar-m, open a terminal and run `mkdir ~/.kaggle`.  It may not work if you try to use a GUI.

@qifengzhou, @BhavtoshRath, my best guess is that you're either running the kaggle commands as root or you put the API token in your root user's home.  Any chance either of those two things is what's happening?

**Comment by qifengzhou** [comment]
@rysteboe How should I check this? 

I tried pip uninstall kaggle, it showed me the path where kaggle was install
'/home/qifeng/anaconda3/lib/python3.6/site-packages/kaggle/'
I pasted the API token into the folder 'kaggle.json' I created in this directory. 

I tried again, its the same error message:
'''
~$ kaggle competitions list -s health
Unauthorized: you must download an API key from https://www.kaggle.com/<username>/account
Then put kaggle.json in the folder /home/qifeng/.kaggle
'''

**Comment by rysteboe** [comment]
Run `mkdir ~/.kaggle` (full path in your case would be `/home/qifeng/.kaggle`).  You need to create that directory - the API does not do it for you.  You can place the token there.  The API token doesn't go in the same location as the binary, unless there's some strange interaction with anaconda that I'm unaware of.

**Comment by qifengzhou** [comment]
@rysteboe Thank you:) 
That works!

**Comment by felixpython** [comment]
I have installed kaggle by using `pip3 install kaggle`.

**Comment by XinSu902** [comment]
I am using a mac. I followed kaggle's instruction until I faced the same problem here that i cannot find the folder ".kaggle". So I created a folder(.kaggle) under my home dir("/Users/xin") and drag the kaggle.json file into that folder. Then, I type the following command: "~/.kaggle/kaggle.json" and I got "-bash: /Users/xin/.kaggle/kaggle.json: Permission denied". I am not sure if i need to type this command at all after putting kaggle.json into .kaggle folder.

Then, I tried to download data sets through kaggle API using "kaggle competitions download -c imaterialist-challenge-fashion-2018" and I got "command not found" 

My goal is to download a data set from kaggle that require me to use kaggle API. 
Any idea what's going on here?  Thanks!

**Comment by yellajaswanth** [comment]
I had the same the issue. Download the token to /Users/<your-user-name>/.kaggle directory and then make sure the token file name is **kaggle.json** inside the folder.

**Comment by barvin04** [comment]
Hey brother, was facing similar problem, this might help : https://twitter.com/barvin04/status/1004265422722486272

**Comment by rysteboe** [comment]
As far as I can tell, these installation instructions are covered in the readme.  If you have suggestions for improving it, please submit a PR or suggest specific changes.  Thanks!

**Comment by lokeshdangi** [comment]
remove the directory and create it again then move the file to it

**Comment by Conengmo** [comment]
For users of the [Winpython](https://winpython.github.io/) distribution: your `.kaggle` folder is located in the `settings` folder in your Python folder. For example: `C:\WinPython-64bit-3.6.1.0Qt5\settings\.kaggle\kaggle.json`

**Comment by Jaco-Julio** [comment]
I face the same problem. I find the solution. Go to your terminal and put the code " cd ~/.kaggle ", then the terminal will take you in the directory .kaggle. So, you need to move the kaggle.json to this directory, to do this use the mv command, ex. sudo mv directory1 directory2. then, run the " chmod 600 /home/[user-name]/.kaggle/kaggle.json " command.

**Comment by LUCKMOONLIGHT** [comment]
if you are using LInux.
1.pip install kaggle
2.cd ~/.kaggle
3.homepage www.kaggle.com -> Your Account -> Create New API token
4.mv ~/Downloads/kaggle.json ./
5.chmod 600 ./kaggle.json

**Comment by Ajithvajrala23** [comment]
> if you are using LInux.
> 1.pip install kaggle
> 2.cd ~/.kaggle
> 3.homepage [www.kaggle.com](http://www.kaggle.com) -> Your Account -> Create New API token
> 4.mv ~/Downloads/kaggle.json ./
> 5.chmod 600 ./kaggle.json



It worked thanks

**Comment by zenetio** [comment]
If you are using Windows and installed kaggle via anaconda, here are the steps
1. Go to /users/<username>/.kaggle
2. homepage www.kaggle.com -> Your Account -> Create New API token
3. mv /users/<username>/Downloads/kaggle.json ./
4. activate your kaggle environment and test the kaggle commands.

**Comment by PyxAI** [comment]
I got _Could not find kaggle.json_ error, running the a notebook on a remote linux, The file was there with the right permissions.
Eventually found a workaround by running through the jupyter terminal instead

**Comment by bharath7896** [comment]
i am using windows andi used the jsonwell recently it displayed to update api token so i deleted the old one and created new token but it is saving as kaggle(2).json and i am getting error ass unauthorzed 401 what should i do ?

**Comment by ruimmpires** [comment]
hi, using a colab notebook. I did all the above today and worked fine. Now, trying to go back to my work and I get the following error:
Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python2.7/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/kaggle/api/kaggle_api_extended.py", line 146, in authenticate
    self.config_file, self.config_dir))
IOError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.

Why is colab running python 2.7!? I believe it is not even compatible and it is specifies in the runtime to be python3.

**Comment by shivbobde** [comment]
Ya I got the same error please any one solve @ruimmpires

**Comment by naveen-kumar-123** [comment]
I have done everything according to the documentation:

in the picture below, you can see that my directory structure is as it should be, but error still persists
![image](https://user-images.githubusercontent.com/41302653/87925614-299cb200-ca9e-11ea-8f40-1b59d0b8b31e.png)

How do I fix this?

**Comment by swraza** [comment]
the file is present under my user\kaggle\kaggle.json but when I run kaggle commands, it says 
IOError: Could not find kaggle.json. Make sure it's located in /home/ec2-user/.kaggle. Or use the environment method.

Anyhelp?

**Comment by KarinWiberg** [comment]
Hi, Im having the same issue as many of you that I can not access the API (from Mac). 

I have:
- Created .kaggle in my home directory (~/Users/karinwiberg)
- Moved kaggle.json into the .kaggle directory
- Run the "chmod 600 ~/User/karinwiberg/.kaggle/kaggle.json"
The comments cover this far. For me, I still get error and am wondering if any of you can help me out?

(Additional info is that the kaggle.json is also present int /opt/conda/bin from the installation)

Thanks, 
<img width="1080" alt="Screenshot 2021-02-17 at 09 49 00" src="https://user-images.githubusercontent.com/72396030/108179077-78c6c600-7105-11eb-9bdc-e3169560a4c9.png">

**Comment by Jollygraces** [comment]
> If you are using Windows and installed kaggle via anaconda, here are the steps
> 
> 1. Go to /users//.kaggle
> 2. homepage [www.kaggle.com](http://www.kaggle.com) -> Your Account -> Create New API token
> 3. mv /users//Downloads/kaggle.json ./
> 4. activate your kaggle environment and test the kaggle commands.

**Comment by Jollygraces** [comment]
this worked for me on windows

**Comment by mar-co-pol** [comment]
OSError: Could not find kaggle.json. Make sure it's located in C:\Users\User.kaggle. Or use the environment method In PyCharm, Windows 10, Python 3.8 (not works for 3.9):

pip install kaggle
www.kaggle.com -> Your Account -> Create New API token
Past file in C:\User\.kaggle

You're wonderful!
