### ISSUE TITLE
Upload not stopping.

### ISSUE THREAD

**Issue by amanagr** [Kaggle/kaggle-api#150]
I am trying a create a new dataset on kaggle via it's api. 
kaggle datasets create  -p <file-upload-dir>
(after init)
The file size on disk is 14.16 GB but it keeps uploading and doesn't stop at all. (currently at 22 GB).
What do you think is the cause?

While using the kaggle website to upload the dataset, it shows an exclamation mark next to the file after it finishes uploading and it says something like `please resolve error before creating the dataset`.
Possible cause of this?

**Comment by donariumdebbie** [comment]
I have the same issue 'You must resolve errors before creating your dataset'

**Comment by ChenstEl** [comment]
Same issue here. Did you solved this problem?

**Comment by amanagr** [comment]
Yeah! I divided the data into smaller chunks before uploading and then
combined them in the notebook.
