### ISSUE TITLE
Diabetic Retinopathy Detection dataset

### ISSUE THREAD

**Issue by gsmvenus** [Kaggle/kaggle-api#152]
Unable to download dataset for https://www.kaggle.com/c/diabetic-retinopathy-detection/data

I have kaggle user/password, download API token.

Used this in Admin Cmd
kaggle competitions download -c diabetic-retinopathy-detection

Response: 403 - Forbidden

I have accepted the rules and received the verification code.

Regards,
Giri

**Comment by roleiland** [comment]
I have the same issue. Did you solve the problem?

**Comment by AlphaCoder321** [comment]
I have the same issue, I tried uninstalling the kaggle API and installing again, didnt work. Did you solve it?

**Comment by erprashantkumar85** [comment]
Must verify your account with phone number, then only the download is enabled.

**Comment by Philmod** [comment]
You might need to first accept the competition's rules. I improved the error message in the latest release.

```
$ kaggle competitions download -c diabetic-retinopathy-detection
403 - Forbidden - You must accept this competition's rules before you'll be able to download files.
```
