### ISSUE TITLE
unable unzip test.zip, using !unzip to specific folder in colab

### ISSUE THREAD

**Issue by saikiransingh007** [Kaggle/kaggle-api#154]
I want unzip test.zip in google-colab.
for that I am using below code 

!unzip test.zip 

but, here am having a problem, that it containing so many csv files in it.
so, I want to extract all of those files into a folder,but I couldn't find any-thing related to it.

Saikiran

**Comment by floscha** [comment]
Hi @saikiransingh007, does `!unzip test.zip -d data` work for you? Of course, you can replace *data* with whatever the name of your folder is.

**Comment by jorijnsmit** [comment]
Maybe you could move them to a separate folder?
```python
!mkdir data
!mv *.csv data
```

Anyway I don't really see how this is related to the API... Maybe #231 since it prevents these scenarios from happening.

**Comment by ShettyMahalakshmi** [comment]
!unzip filename.zip

**Comment by shobhanam14** [comment]
! unzip filename.zip is a Linux command
For windows machine what should we use?? 
This is not working for windows.machine.

**Comment by Rohit036** [comment]
@shobhanam14 The colab runs on the cloud does not depend whether from windows or Linux. Use !unzip filename.zip. Do not put space after !

**Comment by ShagunSharma98** [comment]
> I want unzip test.zip in google-colab.
> for that I am using below code
> 
> !unzip test.zip
> 
> but, here am having a problem, that it containing so many csv files in it.
> so, I want to extract all of those files into a folder,but I couldn't find any-thing related to it.
> 
> Saikiran

You can solve this problem using **shutil**.

Use the following code _specifying the correct paths_ to solve this issue:

`from google.colab import drive
drive.mount('/content/drive')`

Executing the above code will mount your google drive to colab. make sure the zip file you want to extract is in the _root directory of your drive_.

Next,
`!mkdir Extracting_folder`

This line will create a folder for you to extract the files into it.

`import shutil
shutil.unpack_archive("drive/MyDrive/File_Name.zip", "Extracting_folder/")`

Your contents will be extracted into the specified folder.
