### ISSUE TITLE
Encoding error when pulling from kernel via Kaggle recommended command

### ISSUE THREAD

**Issue by CloudChaoszero** [Kaggle/kaggle-api#163]
**Device:** 
Mac-OS

**Steps:**
Use recommended/copied command to download kernel from (https://www.kaggle.com/kashnitsky/a2-demo-analyzing-cardiovascular-data-solution):

`kaggle kernels pull kashnitsky/a2-demo-analyzing-cardiovascular-data-solution`

**Issue:**
Receive the following error when using the Kaggle API recommended command to download a kernel. 

`'latin-1' codec can't encode character u'\u2013' in position 249: ordinal not in range(256)`

Cheers,
Raul M.

**Comment by RobHarrand** [comment]
It's because the kernel contains a [U+2013](https://www.fileformat.info/info/unicode/char/2013/index.htm) character (–) when it should be a hyphen. This usually happens when you copy and paste text from, say, Word, into a kernel. It would be good if the API could handle such characters.

**Comment by CloudChaoszero** [comment]
Oh, I see. This is more an issue from the specific pulled data, as opposed from the API? Moreover, this is a warning message from after the download action occurs (residual warning after action), based on a re-attempt.


I'll be closing this issue.

**Comment by CloudChaoszero** [comment]
Note: Another workaround is manual downloading the dataset(s) or kernel, per UI.
