### ISSUE TITLE
Consistent Evaluation Exception error during the scoring phase (both via API and Kaggle web forms)

### ISSUE THREAD

**Issue by mirekphd** [Kaggle/kaggle-api#164]
Since March, 8th I can no longer submit any predictions to e.g. Porto Seguro competition (https://www.kaggle.com/c/porto-seguro-safe-driver-prediction/submit). A Late Submission using kaggle.com web form just hangs in the Scoring phase.

I replicated this error using Kaggle API (repeating dozens of times with different CSV files that used to work), I consistently get this error:
`Evaluation Exception: Object of type 'Kaggle.DataFrames.Series`1[System.Int32]' cannot be converted to type 'Kaggle.DataFrames.Series`1[System.String]`

The problem with submissions has been confirmed over the last day by other non-API users on Kaggle Feedback forum:
https://www.kaggle.com/product-feedback/83191
https://www.kaggle.com/product-feedback/83247

**Comment by mirekphd** [comment]
The problem is rather urgent, as I suspect the reported inability to process predictions data spilled over also to your Contact Form backend (as we informed you on the Product Feedback forum [here](https://www.kaggle.com/product-feedback/83247)). For the past 24 hours users have been unable to inform you of this issue, as it is a typical "catch 22" situation: you cannot file a bug because the bug filling channel is broken...:

![image](https://user-images.githubusercontent.com/36706320/54069738-7fcad580-425a-11e9-8d63-2890ded77225.png)

[ https://www.kaggle.com/contact ] 

. Keeping silent will only increase the number of people using Github as a contact form replacement

**Comment by mirekphd** [comment]
I noticed the Evaluation Exception error (which as its name suggests occurs during the scoring phase - uploads work correctly), happens at roughly 75% of the file (at the 6th second in the scoring process which normally completes after 8 seconds). This happens also to files which I previously managed to score successfully, so the error is not inside my files.

**Comment by rysteboe** [comment]
This is not an API issue.  Please continue this on the Kaggle website.  I'm the only one who checks this repo, and I can't help you.  I've pinged appropriate people about the threads on our site, but posting issues here won't help further.
