### ISSUE TITLE
why my competition disappear?

### ISSUE THREAD

**Issue by adaaaaaa** [Kaggle/kaggle-api#165]
i join housing prices competition last year DEC.
today i find it disappear...
why?

**Comment by adaaaaaa** [comment]
@rysteboe before it disappear , i can see the position in the leaderboard,now i can't find it...

**Comment by Doarakko** [comment]
> This competition runs indefinitely with a rolling leaderboard which invalidates entries after two months.
https://www.kaggle.com/c/house-prices-advanced-regression-techniques

**Comment by adaaaaaa** [comment]
@Doarakko Thanks!
