### ISSUE TITLE
How to download Kernel output files?

### ISSUE THREAD

**Issue by Uysim** [Kaggle/kaggle-api#167]
How can I download my Kernel output file?
https://www.kaggle.com/uysimty/carvana-image-masking/output

**Comment by Doarakko** [comment]
- command
```
$ kaggle kernels output uysimty/carvana-image-masking/output
```
- browser
![スクリーンショット 2019-04-06 13 33 34](https://user-images.githubusercontent.com/21009186/55664890-e00c6180-5870-11e9-82b7-72c46c2ba479.png)

**Comment by Uysim** [comment]
Thank you @Doarakko  this is helpful

**Comment by ManishShah120** [comment]
Is it also possible to download directories from Output? If yes, How???
