### ISSUE TITLE
unable to upload my datasets

### ISSUE THREAD

**Issue by Elaine-DWL** [Kaggle/kaggle-api#169]
Default slug detected, please change values before uploading

**Comment by YangQun1** [comment]
@Elaine-DWL  Do you have solved it? I meet this problem too.

**Comment by kenkrige** [comment]
Same error message. Any solutions?

**Comment by kenkrige** [comment]
If you created a default config file like this:
`kaggle datasets init -p mydataset`
then you need to edit the file _mydataset/dataset-metadata.json_. In Linux this could be done as follows:
`nano mydataset/dataset-metadata.json`
Change the id and the title.

**Comment by Hamedspy** [comment]
if you code in colab open your dataset-metadata.json and change the title and id
