### ISSUE TITLE
Cannot "pip install kaggle", error saying "Could not fetch URL, problem confirming the ssl certificate..."

### ISSUE THREAD

**Issue by jzl4** [Kaggle/kaggle-api#170]
Hi all, I am new to Kaggle, and excited to learn from this wonderful community.

Unfortunately, I was unable to install kaggle using pip in my Windows command line:
> **pip install kaggle**

I received the following error:

> **Could not fetch URL https://pypi.org/simple/kaggle/: There was a problem confirming the ssl certificate ... Max retries exceeded with url: /simple/kaggle/ ...**

![image](https://user-images.githubusercontent.com/48886620/55751238-35807400-5a13-11e9-8556-3c8216b46bd5.png)

I have searched on google repeatedly, through stackexchange / github / fast.ai forums, and looked at similar posts.  As a result, I have tried the following:
(1) I have tried to run cmd as administrator
(2) I tried the command:

>  **pip install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org kaggle**

Unfortunately, I got the same issues:
![image](https://user-images.githubusercontent.com/48886620/55751370-81331d80-5a13-11e9-93ce-f90ae8423af5.png)

Can you please advise?

Thank you very much!

**Comment by Philmod** [comment]
It seems like your computer doesn't have access to pypi.org?
