### ISSUE TITLE
Getting metadata of the dataset owned by Kaggle

### ISSUE THREAD

**Issue by sak797** [Kaggle/kaggle-api#172]
I am trying to get the metadata of this dataset: [(https://www.kaggle.com/c/titanic/data)]
So I want to run `kaggle datasets metadata -p /path/to/download <owner>/titanic`. I am not sure what should be in place of `<owner>`. I have tried 'Kaggle', 'KAGGLE' & 'kaggle'

**Comment by Philmod** [comment]
`kaggle competitions download titanic`
