### ISSUE TITLE
kaggle does not work with colab GPU runtime type

### ISSUE THREAD

**Issue by yakout** [Kaggle/kaggle-api#176]
For some reason when I switch to GPU runtime type in Google Colab, and run the kaggle command
`!kaggle competitions download -c quora-question-pairs` it gives me 
`404 - Not Found`

This is reproducible from my side.
And when I switch back to CPU everything works fine!
Not sure if that issue is related to Google Colab or kaggle command.

**Comment by harrysalmon** [comment]
Experiencing the same on colab
Kaggle API 1.5.3
python3.6

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10744933182675661975
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 1377243164821152880
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 12417575514232854823
physical_device_desc: "device: XLA_GPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 14800692839
locality {
  bus_id: 1
  links {
  }
}
incarnation: 6496953254045019095
physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"
]

**Comment by linlih** [comment]
same problem, the other day works fine, but suddenly it returns 404

**Comment by jiteshm17** [comment]
If you are using Ubuntu or any other Linux distribution, try switching to Windows. I am not sure why but this actually worked for me.

**Comment by Santiago8888** [comment]
How can you switch to Windows in Colab @jiteshm17

**Comment by jiteshm17** [comment]
@Santiago8888, I did not mean a switch to Windows in Colab, I actually meant your desktop/laptop's OS. If your system's operating system is any Linux Distro and you get the 404 error while using the GPU runtime and if you also have Windows alongside Linux in your system(dual-booted), try running Colab in Windows (OS) with the GPU runtime enabled. Doing this worked for me. Hope this helps

**Comment by timyee90** [comment]
I have the same 404 - Not Found issue with the NVIDIA T4 GPU. No issues with the CPU or Telsa K80 GPU. I wonder if they restricted access to the T4 GPU for Kaggle use as it would give kagglers access to more free high powered GPU compute. This issue is specific to the T4 GPU.

**Comment by jorijnsmit** [comment]
Cannot reproduce. The command `!kaggle datasets list` works fine in both CPU, GPU and TPU environments on [colab.research.google.com/](https://colab.research.google.com/).
