### ISSUE TITLE
competitions submit doesn't print process info

### ISSUE THREAD

**Issue by gutouyu** [Kaggle/kaggle-api#18]
Is this normal?  when submit to competitions, we don't know the process but to wait. So sad

**Comment by rysteboe** [comment]
@gutouyu, can you please elaborate on what you'd like here?

**Comment by gutouyu** [comment]
@rysteboe the upload speed and a progress bar shows that how much I have uploaded.
Just let me know the progress.

**Comment by rysteboe** [comment]
Gotcha, thanks.  This is already on my wishlist, but unfortunately there are a lot of other things to get to first.  I do not have any sort of ETA for implementation.

**Comment by rysteboe** [comment]
There should now be a progress bar as of `1.3.9`.  Please let me know if you have any additional problems.

**Comment by gutouyu** [comment]
Thank you very much. Amazing job!
