### ISSUE TITLE
kaggle_api cannot submit

### ISSUE THREAD

**Issue by imimtk** [Kaggle/kaggle-api#181]
error,WARNING Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),)': /upload/storage/v1/b/kaggle-competitions-submissions/o?uploadType=resumable&upload_id=AEnB2UoTUF_ZJou1BV_fFERhDzRqnLVKu5Uh3iuxP_YJgWNOrEjLiZMtlTquo0uGUONeSQ5BMTUgS6iGTHgeNhbKGHrDkZpgSw

**Comment by Djinhui** [comment]
Do you have solved it? I meet this problem too.

**Comment by jorijnsmit** [comment]
Can you provide some more context for this issue? What were you doing and what happened? How can i be reproduced? What version are you using?

**Comment by Philmod** [comment]
I can't reproduce this bug, feel free to reopen if you are still experiencing it.
