### ISSUE TITLE
Error in execution of code in python micro course kernel

### ISSUE THREAD

**Issue by Asutosh765** [Kaggle/kaggle-api#191]
In the Micro course python's 7th Exercise for List and Tuples I completed the code and executed it and it shows that it is incorrect, When that is clearly correct as you can see in the picture. 

![kaggle issue 1](https://user-images.githubusercontent.com/40321400/58749189-4fcd5000-84a0-11e9-8400-6d19cc49045c.PNG)
The indexing during the execution is wrong even the binding to global from learntools.core and importing all the functions from learntools.python.ex4 setup is successfully completed.

**Comment by Asutosh765** [comment]
There is another value read from the list error in the loop and list comprehension section 
![kaggle issue 4](https://user-images.githubusercontent.com/40321400/58753317-c25b2180-84da-11e9-85c1-9cbf38929329.PNG)
![kaggle issue 5](https://user-images.githubusercontent.com/40321400/58753318-c6873f00-84da-11e9-9d2c-b147f5bccdcc.PNG)
look at the blue rounded strings in the printed list and in the element and it,s neighbour printed section they both has to be same but are different hence resulting the error at the yellow line.
Instead of giving a True Boolean value it gives a False resulting to incorrect answer of docstring mentioned required result.

**Comment by rysteboe** [comment]
This doesn't seem to be an API related issue.  Please report such problems on the main Kaggle site (https://www.kaggle.com/discussion) or through our support (https://www.kaggle.com/contact).

Reopen if I'm mistaken here.  Thanks!
