### ISSUE TITLE
Don't childishly block the current urllib3 version

### ISSUE THREAD

**Issue by baerbock** [Kaggle/kaggle-api#192]
You are childishly blocking the current urllib3 version `'urllib3 >= 1.21.1, < 1.25',`
in https://github.com/Kaggle/kaggle-api/blob/master/setup.py

Good programmers would have avoided such steps.

**Comment by rysteboe** [comment]
PR's are appreciated, rude comments are not.  If this is an issue that you feel strongly about, feel free to send a PR fixing it.
