### ISSUE TITLE
Install kaggle with anaconda error

### ISSUE THREAD

**Issue by JiangStein** [Kaggle/kaggle-api#193]
Hi, I'm trying to install kaggle on Ubuntu 16.04.
I firstly tried to install this kaggle by `pip install --user kaggle`, but when I run `kaggle`, it shows `OSError: Could not find kaggle.json.` I searched that in Issues but I can't find `kaggle.json` in either `/root `or other places.
I tried to uninstall kaggle, and it shows that it is installed in anaconda3/bin, the version of my pip is `pip 18.1 from /home/stein/software/anaconda3/lib/python3.7/site-packages/pip (python 3.7)`
Is it because that I installed kaggle with anaconda?

**Comment by JiangStein** [comment]
Sorry I made a mistake... I have download my json and it works...

**Comment by kirankotari** [comment]
@JiangStein I have downloaded my JSON and it works... what does that mean? I am facing the same issue please help.

**Comment by izaharkin** [comment]
@kirankotari , here is the correct answer: https://github.com/Kaggle/kaggle-api/issues/15
