### ISSUE TITLE
Problem with pushing kernels

### ISSUE THREAD

**Issue by mosheliv** [Kaggle/kaggle-api#197]
I have made a dataset and kernel public on kaggle to help reproduce the problem easily:

```
$ kaggle kernels pull -m -p t moshel/dataset-problem
Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/m/.kaggle/kaggle.json'
Source code and metadata downloaded to t
$ kaggle kernels push -p t
Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/m/.kaggle/kaggle.json'
500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api

```

the kernel runs via commit (it is just hello world).

**Comment by virilo** [comment]
The same here: 500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api

Using Kaggle API 1.5.5

**Comment by remotejob** [comment]
push don't work anymore as well for me:

`500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api`

Kaggle API 1.5.5

**Comment by Philmod** [comment]
I can't reproduce this bug, feel free to reopen if you are still experiencing it, with a full reproducible kernel-metadata.json file.
