### ISSUE TITLE
AttributeError: 'KernelPushResponse' object has no attribute 'newUrl'

### ISSUE THREAD

**Issue by andreas-wolf** [Kaggle/kaggle-api#198]
Version kaggle==1.5.4

Code like this:
```
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()
response = api.kernels_push(folder='/a_folder_containing_a_kernel')
print(response)
```
generates the following Exception:

> File "[..]site-packages/kaggle/models/kaggle_models_extended.py", line 164, in __repr__
    return self.newUrl
   AttributeError: 'KernelPushResponse' object has no attribute 'newUrl'

Apparently `KernelPushResponse.newUrl` is not set when returning from `kernels_push`

**Comment by alixTal** [comment]
I have the same issue, what's the solution?

**Comment by svendaj** [comment]
Well, kind of workaround is to call `kernels_push` wrapper called `kernels_push_cli`. The only issue is that there is no return value and you can't get any info on result.
```
>>> api.kernels_push_cli(".")
Kernel version 38 successfully pushed.  Please check progress at https://www.kaggle.com/code/svendaj/testing
```

**Comment by allispaul** [comment]
I think this issue should be reopened. It's a clear bug, and one should be able to push a kernel and print something reasonable about the response.

Changing `return self.newUrl` in `ModelNewResponse.__repr__()` to `return self.url` would fix it, though it could also be useful to return the version number, error information if there were errors, etc.
