### ISSUE TITLE
Competition detault

### ISSUE THREAD

**Issue by antorsae** [Kaggle/kaggle-api#2]
The unofficial kaggle API (https://github.com/floydwch/kaggle-cli) has a nice feature to default to a specific competition if you omit the `-c` parameter, see `$ kg config -g -u <username> -p <password> -c <competition>`

It would be very nice to have this on the official kaggle api.

**Comment by mxbi** [comment]
You could achieve this using a simple bash function actually. For example, adding something like this to your `.bashrc` or `.bash_profile`:

```bash
function kgcomp() {
    kaggle competitions ${@:1:1} -c jigsaw-toxic-comment-classification-challenge ${@:2}
}
```

Running:  
`kgcomp submit -f submission.csv -d "description"`  
should then just be equivalent to:  
`kaggle competitions submit -c jigsaw-toxic-comment-classification-challenge -f submission.csv -d "description"`

**Comment by dpmcna** [comment]
Hey @antorsae and @mxbi , thanks for your suggestions. We are gathering user feedback on the beta release and we will then look at V1.1 incorporating changes based on this feedback. Cheers, Daniel

**Comment by timoboz** [comment]
Thanks for all the suggestions! This is added now to the new API v1.1. You can now set a competition via `kaggle config set -n competition -v [competition]`.
