### ISSUE TITLE
API for Kaggle kernels?

### ISSUE THREAD

**Issue by epatters** [Kaggle/kaggle-api#20]
It's great to see that Kaggle now has an official API, but it seems that the API does not include Kaggle kernels. Is that correct and, if so, are there plans to create a kernels API?

**Comment by rysteboe** [comment]
@epatters, would you mind writing up a bit of what you'd like to see from such an integration?  I'm in the planning stages for this, and am gathering feedback from interested parties.

**Comment by epatters** [comment]
@rysteboe, I'm happy to say why I'm interested in a Kaggle kernels API. Perhaps this can serve as a use case for you.

I'm currently working on a project to construct semantic representations of data science code, using dynamic and static program analysis. (It's not yet available as open source software, but will be soon enough.) I'd like to perform an empirical evaluation of my system on real-world data science code. As far as I know, Kaggle kernels is the only large online repository of code that is specifically for data analysis, which makes it a natural candidate.

For this kind of meta-analysis work, it would be helpful to download kernels programmatically and in bulk, with options to restrict the kernel type (script or Jupyter notebook), programming language, dataset, and/or competition. I imagine that anyone interested in the studying the "metascience" of data science through Kaggle would benefit from such capabilities.

**Comment by MarkDaoust** [comment]
Hi, 

here's another use-case:

I have a bunch of notebooks I'd like to (keep in sync with) or (push to) my kaggle account when I update them.

**Comment by rysteboe** [comment]
Please check out 1.4.0 of the API.  There is now support for kernels, but as this is the initial release, there are a number of QoL issues that I'm aware of and hope to fix.  Please file separate issues with any bugs or feedback.  Closing this for now, but greatly appreciate the feature request!  Was part of what was able to get it prioritized for work.
