### ISSUE TITLE
search dataset return 404

### ISSUE THREAD

**Issue by tiyunchen** [Kaggle/kaggle-api#205]
![image](https://user-images.githubusercontent.com/24793416/62873510-1f344d00-bd52-11e9-8564-8ac2f95e7051.png)

**Comment by yjw1029** [comment]
same issue.

**Comment by leijuzi** [comment]
pip install -U kaggle==1.5.3 
depress the version, it works for me

**Comment by Philmod** [comment]
I can't reproduce this bug, feel free to reopen if you are still experiencing it.
