### ISSUE TITLE
Can't seem to submit - not sure if b/c competition is over..?

### ISSUE THREAD

**Issue by taewookim** [Kaggle/kaggle-api#21]
Im trying to get the kaggle API command line  to work by submitting predictions file 

`kaggle competitions submit -c dogs-vs-cats -f predictions3.csv -m "Testing submissiion"`

Error I get 

> kaggle.rest.ApiException: (404)
> Reason: Not Found
> HTTP response headers: HTTPHeaderDict({'Referrer-Policy': 'strict-origin-when-cross-origin', 'X-Frame-Options': 'SAMEORIGIN', 'X-Kaggle-RequestId': '4eeb1e0a4c44eb1de1e91c1b1465ff17', 'X-Kaggle-MillisecondsElapsed': '99', 'Set-Cookie': 'TempData=.CgyIbYovBnNsRrQ5R40L2VYiUlszXXMjcPEdnDqJsludT7h41+aziHdgLczhPYAtIA83y6CjtoJPjwLpcQMi7kYjvibDQW+7WPF85ETDNY44IcDE7Vnv8qmYcI590AkOhHIk5RsKyZUhaHkWIlucLZ038B+kzltzv6AcqO11XLIXtqe5vsNyfLy9G+wxvLBcXYXece0DhqXMvtb04g/OOI9ilMA=; path=/; secure; HttpOnly, ARRAffinity=a1f2e0851ff7e4cea3fc44de7296743a24a31e636c51d9d4876a2a31fd3e731c;Path=/;HttpOnly;Domain=www.kaggle.com', 'Date': 'Wed, 04 Apr 2018 06:06:33 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '33', 'Cache-Control': 'private', 'X-Kaggle-ApiVersion': '1.1.0'})
> HTTP response body: {"code":404,"message":"NotFound"}

**Comment by datamove** [comment]
Dear Rebecca,
Here is a different rejection response I got while submitting to a "Getting Started" competition. Would it be possible to enable submissions for such a category, as well as "Playground"? I think this is valid ue case, as submission is encouraged to such competitions.

`~$ kaggle competitions submit  -c  word2vec-nlp-tutorial -f Bag_of_Words_model_2.csv -m BOW_2`
...
```
kaggle.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'private', 'Content-Length': '172', 'Content-Type': 'application/json; charset=utf-8', 'X-Kaggle-MillisecondsElapsed': '29', 'X-Kaggle-RequestId': 'b9cc49880613261ce93762015b700505', 'X-Kaggle-ApiVersion': '1.1.0', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Set-Cookie': 'ARRAffinity=0;Path=/;HttpOnly;Domain=www.kaggle.com', 'Date': 'Wed, 02 May 2018 10:29:39 GMT'})
HTTP response body: {"code":403,"message":"This competition is not currently active.  To test submissions prior to competition launch, use the Sandbox Submissions tool found on the Host tab."}

```

**Comment by rysteboe** [comment]
Yeah ... that's a bug.  Let me revert that change.

**Comment by rysteboe** [comment]
Should be fixed now - sorry about that.

**Comment by datamove** [comment]
Thanks, Rebecca! All fine now.

**Comment by jayleverett** [comment]
I'm also getting a 404 error when submitting to an old competition (Dstl). 

Submissions are still open through the Kaggle UI, so I'm curious if it would be possible/easy to support them through the API? ... Would be super useful to those of us working on old competitions.

Thanks for a great API!

**Comment by rysteboe** [comment]
I'll look into late submissions - hopefully have something next week for you.

**Comment by rysteboe** [comment]
@jayleverett would you mind trying again?  I'm now able to submit to that competition on my end - would appreciate verification from you!

**Comment by rysteboe** [comment]
I'm closing this out - by my testing this seems to work, and I've also updated some error messages to be more clear.  Please let me know if you have any additional problems.
