### ISSUE TITLE
Unable to get my kernels list

### ISSUE THREAD

**Issue by gottalottarock** [Kaggle/kaggle-api#213]
Unable to get my kernels list:
` kaggle kernels list -m` returns:
`500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api`
But I'm able to get datasets list with command: 
`kaggle datasets list -m`

```
$ pip show kaggle  

Name: kaggle
Version: 1.5.5  
Summary: Kaggle API  
Home-page: https://github.com/Kaggle/kaggle-api  
Author: Kaggle  
Author-email: support@kaggle.com  
License: Apache 2.0  
```

**Comment by gloryVine** [comment]
I get this error as well. Please someone look into this.

**Comment by Philmod** [comment]
I can't reproduce this bug, feel free to reopen if you are still experiencing it.
