### ISSUE TITLE
Cannot download large datasets over the kaggle API

### ISSUE THREAD

**Issue by rahulkulhalli** [Kaggle/kaggle-api#223]
I'm trying to download the RSNA brain hemorrhage dataset via the kaggle API, and the download progression always idles at 59% and terminates. Note that the size of the data is also pretty substantial (~160 GB).

Is there any way where I could download chunks of the data?

**Comment by bhavesh0009** [comment]
same issue here. Failed after 16% completion. It should start from where it left previously and not from scratch.

**Comment by mdvthu** [comment]
+1 for a completion option similar to `wget -c`

**Comment by PotatoSpudowski** [comment]
Try 

pip uninstall -y kaggle
pip install --upgrade pip
pip install kaggle==1.5.6

**Comment by Philmod** [comment]
We implemented resumable downloads in the last release, let me know if that helps.
