### ISSUE TITLE
Feature request: utility-script in kernels

### ISSUE THREAD

**Issue by go5paopao** [Kaggle/kaggle-api#225]
When I work in local PC and then I want to run in kaggle kernel, I can use kaggle kernels api (kaggle kernels push -p /PATH). It is very useful.

However when I have some utility source code, I cannot finish only kaggle api. I have to open notebook UI and set (click "set as a utility script"), and add utility scripts in main kernel. If I have many utility script, it takes a long time...

So I want to add feature of set/add utility script in kaggle kernels api or add utility script items in "kernel-metadata.json" (the sample is bellow).

```
{
  "id": "go5kuramubon/features",
  .......
  "set_as_utlity_script": False,
  "add_utility_script": [
    "feature_util",
    "lgb_util",
  ]
}
```

**Comment by gloryVine** [comment]
Was this ever added? It's the missing step in my API-only-pipeline.

**Comment by jplotts** [comment]
Yes, you can mark a kernel as utility script by adding `"keywords": [ "util-script" ]` to your "kernel-metadata.json".

You can add a utility script to another kernel the same as you would add any other kernel datasource, by setting the `kernel_sources` attribute.

**Comment by gloryVine** [comment]
@jplotts This does not work. While adding `"keywords": [ "util-script" ]` does indeed make the script available as an utility script, I can't use its code in the kernel to which I have added it as one of the `kernel_sources`.
My utility-script produces output, and while I can access that output in the other notebook, I can't access the utility-script's functions and classes. No `utility_script.py` is made available in the 'Data box' on the right side of the API, only the `.csv` outputs generated by the utility script.

**Comment by jplotts** [comment]
Hi @gloryVine - there's a bug in the code where the utility script designation is not respected on the first version, causing the code to be improperly published.  I'll work on getting that patched soon.  In the meantime, this should work if you re-save the utility script.

**Comment by gloryVine** [comment]
@jplotts I got it to work once, which was nice. But now a few days later, I get this error when trying to push the kernel: `The following are not valid tags and could not be added to the kernel: ['util-script']` (The single quotes are only in the error message; I used double quotes inside kernel-metadata.json).
Is this related to the above or should I start a new issue?
