### ISSUE TITLE
API kaggle competitions download -c planet-understanding-the-amazon-from-space producing 404 - Not found error

### ISSUE THREAD

**Issue by sharm636** [Kaggle/kaggle-api#226]

**Comment by cheezit46** [comment]
I'm running into the same problem. If you do "kaggle competitions list" it doesn't come up. Are you trying to follow along with the fastAI lessons as well?

![image](https://user-images.githubusercontent.com/51181778/68766648-dc01a880-05e4-11ea-85f2-db9c3359f249.png)

**Comment by dwitman1** [comment]
I have encountered the same problem... not working the fastai course and also do not see the competition in the competitions list

**Comment by piavgh** [comment]
> I'm running into the same problem. If you do "kaggle competitions list" it doesn't come up. Are you trying to follow along with the fastAI lessons as well?
> 
> ![image](https://user-images.githubusercontent.com/51181778/68766648-dc01a880-05e4-11ea-85f2-db9c3359f249.png)

I have the same problem because I'm following the fastai course.
How did you solve this problem?

**Comment by cheezit46** [comment]
> I have the same problem because I'm following the fastai course.
> How did you solve this problem?

I haven't quite solved the problem, but I have gotten a little closer. On the [kaggle webpage for the competition](https://www.kaggle.com/c/planet-understanding-the-amazon-from-space/data) , the download link can be found directly in the "data tab". 
<img width="743" alt="KaggleAmazon" src="https://user-images.githubusercontent.com/51181778/71588649-e110ad80-2ae7-11ea-9073-3dde5438951e.PNG">


Unfortunately though, the images are downloaded through the torrent provided, and almost nobody is seeding the torrent.

**Comment by piavgh** [comment]
@cheezit46 : I managed to do it, by downloading each file separately.

Check this image:

<img width="1023" alt="Screenshot at Dec 31 08-27-25" src="https://user-images.githubusercontent.com/4060207/71606903-7f177d00-2ba7-11ea-9231-20717b0c32ec.png">

You can click on the file and download each file individually, then manually upload it to your notebook. (you only need 2 files: train-jpg.tar.7z and train_v2.csv

The uploading process is quite long (the file is more than 600 MB), but it works, I'm sure.

**Comment by cheezit46** [comment]
Didn't even notice that. Thanks for letting me know!

Now I just need to move around some hard drive space :)

**Comment by coolsonu39** [comment]
I found a way to download the files directly into colab using wget and cookies.txt chrome extension. Just follow the steps in this [comment](https://www.kaggle.com/general/51898#723056) but replace {donwload-all-button-url} with individual file download url as pointed out by @piavgh

**Comment by JJ11teen** [comment]
Also seeing the same issue :(

**Comment by marcNY** [comment]
When running the command:
`kaggle competitions files -c planet-understanding-the-amazon-from-space`

I get the output:

> name                                                
> ------------------------------------------------- 
> train_v2.csv/train_v2.csv                           
> test_v2_file_mapping.csv/test_v2_file_mapping.csv 
> sample_submission_v2.csv/sample_submission_v2.csv
> Kaggle-planet-train-tif.torrent 
> Kaggle-planet-test-tif.torrent       
> 

So I was able to get the file test_v2 by changing the name but it seems that the file train_v2.tar is not available via api

**Comment by shangeethas** [comment]
I also came across same issue and I logged an open issue https://github.com/Kaggle/kaggle-api/issues/238. I thought it is an issue with internet and I am downloading all kernels in parallel using map-reduce. 

As mentioned earlier, I downloaded manually selecting that particular kernel. There are other few kernels, which also make the downloading process in hung. Thank you.

**Comment by kanak8278** [comment]
I downloaded the zip file using the Kaggle API, but after extracting zip file I got the torrent files, How can I download .tar files.
[Planet: Understanding the Amazon from Space](https://www.kaggle.com/c/planet-understanding-the-amazon-from-space/data) Competition and [API](https://www.kaggle.com/c/planet-understanding-the-amazon-from-space/data). I wanted to download the file directly to my instance as I am not able to download from torrent .
