### ISSUE TITLE
Unable to pull kernel - "404 - Not Found"

### ISSUE THREAD

**Issue by nocibambi** [Kaggle/kaggle-api#227]
Trying to pull one of my kernels ([nocibambi/exploring-bitcoin-data)](https://www.kaggle.com/nocibambi/exploring-bitcoin-data/edit) but unable to do so and receive the following error:
```404 - Not Found```

**Comment by leijuzi** [comment]
me either, have you resolved this?

**Comment by nocibambi** [comment]
Nope, still the same. Working in the online environment as a workaround.

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
