### ISSUE TITLE
 404 - Not Found

### ISSUE THREAD

**Issue by leijuzi** [Kaggle/kaggle-api#229]
kaggle competitions download -c cifar-10
  then l got 
![image](https://user-images.githubusercontent.com/42333539/68645994-c349b200-0554-11ea-9632-30ad1e1c3442.png)

**Comment by leijuzi** [comment]
my version is upgraded to 1.5.7, when i 
pip install -U kaggle==1.5.3 
depress the version, it works for me

**Comment by GEOTCBRL** [comment]
I also got 404 under version 1.5.6, and it turns out working under version 1.5.3.

**Comment by jzenn** [comment]
I had the same issue and downgrading fixed it.

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
