### ISSUE TITLE
 kaggle datasets metadata fails with KeyError: 'errorMessage' with API 1.5.6 and 1.5.5

### ISSUE THREAD

**Issue by higepon** [Kaggle/kaggle-api#235]
```
kaggle datasets metadata -p ./ higepon/tf2-my-submission
```

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/kaggle", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/kaggle/cli.py", line 51, in main
    out = args.func(**command_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1028, in dataset_metadata_cli
    meta_file = self.dataset_metadata(dataset, path)
  File "/opt/anaconda3/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1010, in dataset_metadata
    if (result['errorMessage']):
KeyError: 'errorMessage'
```

This is not happening in 1.5.4.

**Comment by jorijnsmit** [comment]
Same for me: `kaggle datasets metadata jorijnsmit/binance-full-history`

**Comment by neomatrix369** [comment]
I get the same, I just ran:
```
kaggle datasets metadata timoboz/google-trends-data
```

**Comment by AshishR21** [comment]
Getting Same Error, after running following command
<kaggle datasets metadata ashudata/covid19dataset>

**Description** : 
Kaggle API 1.5.6

**Comment by alext234** [comment]
Confirm this bug is not fixed yet 1.5.6

**Comment by Crimsonarcher** [comment]
Got the same error: 18-May-2020
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Survived'

**Comment by YuliaZhou** [comment]
Got the same error on Nov 19th

**Comment by ravimulpuri** [comment]
I got the same error as well

**Comment by skyprince999** [comment]
@grafail Has this bug been closed?? I am getting the same error in 1.5.10 (latest version) #296

**Comment by grafail** [comment]
> @grafail Has this bug been closed?? I am getting the same error in 1.5.10 (latest version) #296 
>  

It's in #304

**Comment by Danilo-Araujo-Silva** [comment]
I still have this error on version 1.5.12.

**Comment by wyattowalsh** [comment]
Yep, I'm facing issues with this same problem. I'd be happy to put some work in to fix this bug; does anyone have some clues to get started? 

Version: 1.5.12
Date: 2021-03-31

**Comment by erdalsivri** [comment]
We've just deployed a server-side fix for this bug. Please let me us if you still have any issues with this command

**Comment by sarpu** [comment]
Still facing this issue
