### ISSUE TITLE
Improve the command-line APIs

### ISSUE THREAD

**Issue by dclong** [Kaggle/kaggle-api#236]
It's my first time to use the Kaggle command-line APIs. I got the following error message when I use the command `kaggle datasets list`. I thought something was wrong with the kaggle package that I installed or with my configuration but later I figured out that I should use `kaggle datasets list -s keywords`. It would be much more user-friendly if the error message tells users that the syntax is wrong and give hints on the correct syntax. I didn't read the implementation of the kaggle command-line API, but at least the Python package `argparse` does what I've suggested. 
![image](https://user-images.githubusercontent.com/824507/71458475-ba551e80-2757-11ea-9e9e-a55a0c303ded.png)

**Comment by jorijnsmit** [comment]
This is actually a bug: #239.

**Comment by Philmod** [comment]
I can't reproduce, feel free to reopen otherwise.
