### ISSUE TITLE
404 Not Found Error when pulling kernels

### ISSUE THREAD

**Issue by shangeethas** [Kaggle/kaggle-api#238]
Hi 
I am getting following error when downloading kernels from a particular competition.
`File "/Users/shangeetha/anaconda3/envs/py3/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1961, in kernels_pull
    self.kernel_pull_with_http_info(owner_slug, kernel_slug))
  File "/Users/shangeetha/anaconda3/envs/py3/lib/python3.7/site-packages/kaggle/api/kaggle_api.py", line 2340, in kernel_pull_with_http_info
    collection_formats=collection_formats)
  File "/Users/shangeetha/anaconda3/envs/py3/lib/python3.7/site-packages/kaggle/api_client.py", line 334, in call_api
    _preload_content, _request_timeout)
  File "/Users/shangeetha/anaconda3/envs/py3/lib/python3.7/site-packages/kaggle/api_client.py", line 165, in __call_api
    _request_timeout=_request_timeout)
  File "/Users/shangeetha/anaconda3/envs/py3/lib/python3.7/site-packages/kaggle/api_client.py", line 355, in request
    headers=headers)
  File "/Users/shangeetha/anaconda3/envs/py3/lib/python3.7/site-packages/kaggle/rest.py", line 251, in GET
    query_params=query_params)
  File "/Users/shangeetha/anaconda3/envs/py3/lib/python3.7/site-packages/kaggle/rest.py", line 241, in request
    raise ApiException(http_resp=r)
kaggle.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 31 Dec 2019 06:15:36 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Vary': 'Accept-Encoding', 'Access-Control-Allow-Credentials': 'true', 'Turbolinks-Location': 'https://www.kaggle.com/api/v1/kernels/pull?userName=aamaia&kernelSlug=quick-view', 'X-Kaggle-MillisecondsElapsed': '64', 'X-Kaggle-RequestId': '1e08004ebb9e1a9d711d6edb8abf8db3', 'X-Kaggle-ApiVersion': '1.5.6', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=3600; includeSubDomains', 'Content-Security-Policy': "object-src 'none'; script-src 'nonce-0OIHMvz6TaXe1Rwu/VITKg==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://js.stripe.com https://www.google.com/recaptcha/ https://form.jotform.com https://submit.jotform.us https://submit.jotform.com https://www.docdroid.com https://www.docdroid.net https://kkb-dev.jupyter-proxy.kaggle.net https://kkb-staging.jupyter-proxy.kaggle.net https://kkb-production.jupyter-proxy.kaggle.net; base-uri 'none'; report-uri /csp/report", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Via': '1.1 google', 'Set-Cookie': 'GCLB=CMPO1qX-1Ied-QE; path=/; HttpOnly', 'Alt-Svc': 'clear'})
HTTP response body: {"code":404,"message":"NotFound"}`

**Comment by rameshgangwar** [comment]
Facing the same problem. I am trying to download my own kernel from kaggle.
