### ISSUE TITLE
Download resumption

### ISSUE THREAD

**Issue by Keno** [Kaggle/kaggle-api#24]
I was downloading the 150GB dataset for https://www.kaggle.com/c/imagenet-object-localization-challenge/data using this CLI, but unfortunately the connection broke after about 100GB and the tool would not pick up where it stopped when I called it again. Luckily https://github.com/floydwch/kaggle-cli was able to resume the download, so I didn't have to download it over again. However, it would be nice if this tool was able to automatically resume the download if it got interrupted.

**Comment by ambigus9** [comment]
I'm agree, will be nice if in official Kaggle API would be possible to resume downloads!

**Comment by pyaf** [comment]
A year and we still have this issue.

**Comment by sicklife** [comment]
sad………………

**Comment by raffaem** [comment]
That would certainly be a nice feature to add

**Comment by asdspal** [comment]
Hello, any update on this?

**Comment by JonathanRayner** [comment]
Bump. Just had a 200 gb dl fail at 80% after downloading for nearly 24 hours :(

**Comment by tteravai** [comment]
this is completely ridiculous. i could resume downloads in the early 1990s on a 2400 bps modem for crying out loud. this "API" is less functional than just using curl.

**Comment by jameskyle** [comment]
kind of blows my mind this is still open.

**Comment by jon-lo** [comment]
Have had trouble resuming download attempts for the 100GB Google Landmark Recognition 2020 dataset. This feature is sorely needed! For the time being, will give kaggle-cli a try.

**Comment by iakashpaul** [comment]
Facing the same issue for 100GB Google Landmark Recognition 2020 dataset, sometimes its the Kaggle CDN/network which just stops downloading or other times it would be my Mac getting disconnected from WiFi. Not having the ability to resume is quite painful for both time & bandwidth being wasted on huge datasets, even a web-torrent would be a better solution to have if it can be integrated with the security/keys.

**Comment by cpoptic** [comment]
The pulmonary embolism competition is a massive dataset of 912.92 GB.  My internet connection cut out after 900 GB were downloaded and running the download command with the kaggle API was unable to resume downloading the data and foolishly began completely from zero.

This is ridiculous.  And frankly unacceptable.

Can Kaggle please update their API to something in the 21st century that can actually resume a download upon pausing/interruption?

And since I have about as much confidence that Kaggle will solve this issue any time soon (this issue has been open for over two years) as I have confidence for Kaggle to not randomly impose arbitrary interpretations of competition rules after a competition concludes (see the drama fallout from the DeepFakes competition), I ask the Kaggle community instead:  what methods do you use to download the big datasets like the pulmonary embolism dataset?

**Comment by cdluminate** [comment]
Why is such a fundamental feature not yet implemented? This is insane.

**Comment by lmassaron** [comment]
I have the same problems downloading a dataset related to the pulmonary embolism competition which often just get resetted after many hours of downloading without any possibility of resuming. If downloads were exposed I could downalod with something smarter, but they are just locked behing this API. Disappointing, extremely disappointing :-(

**Comment by csachs** [comment]
To whom it may concern, I worked on resumable downloads in PR #328 .

**Comment by psicobloc** [comment]
So almost 3 years on and this is still open, how is this not a priority?

**Comment by ccl-private** [comment]
@csachs I used your PR，but when I try to resume download，it shows “ imagenet-object-localization-challenge.zip: Skipping, found more recently modified local copy (use --force to force download)”

**Comment by jordanmendler** [comment]
Is there any update in terms of intent to implement resume feature?

**Comment by jordanmendler** [comment]
> @csachs I used your PR，but when I try to resume download，it shows “ imagenet-object-localization-challenge.zip: Skipping, found more recently modified local copy (use --force to force download)”

Did you install it from the right branch and then downloading a new dataset from scratch before trying to resume? This is what worked for me:

pip install git+https://github.com/csachs/kaggle-api.git@resumable

**Comment by ccl-private** [comment]
my mistake, I forgot to change the branch to resumable.

**Comment by jstolberg** [comment]
> > @csachs I used your PR，but when I try to resume download，it shows “ imagenet-object-localization-challenge.zip: Skipping, found more recently modified local copy (use --force to force download)”
> 
> Did you install it from the right branch and then downloading a new dataset from scratch before trying to resume? This is what worked for me:
> 
> pip install git+https://github.com/csachs/kaggle-api.git@resumable

I used your command, but still get "imagenet-object-localization-challenge.zip: Skipping, found more recently modified local copy (use --force to force download)" when I run
kaggle competitions download -c imagenet-object-localization-challenge
How did you resume the download after installing the PR like this?

**Comment by mxmlnkn** [comment]
@jstolberg Maybe try with `--force-reinstall`?

```python
pip install --force-reinstall git+https://github.com/csachs/kaggle-api.git@resumable
```

**Comment by schoonhovenrichard** [comment]
> To whom it may concern, I worked on resumable downloads in PR #328 .

This solved my problem! Thanks for sharing.

**Comment by woshiZS** [comment]
> touch -m -t 201712240000

thks, this works for me, it really help a lot.

**Comment by Nirbhayr** [comment]
Is there any official solution to this? Just lost 225GB file because of download failure. It is painful.

**Comment by findalexli** [comment]
Please invest some time.... This is super painful

**Comment by Philmod** [comment]
Resumable download has been added to the latest release.

**Comment by mxmlnkn** [comment]
Finally works. I needed it just now. Thank you!
