### ISSUE TITLE
Functions and Getting Help - ex.3   

### ISSUE THREAD

**Issue by gustavoalonso93** [Kaggle/kaggle-api#241]
On this exercise I put my solution, the variable wich i have done with number of candies after % 3 , the number of friends for sharing , but if I run the cell this message appears:

"Incorrect: to_smash should be callable with two arguments (e.g. to_smash(10, 2)"

Okay, I had run the other cell to see the hint but nothing appears.
I already updated the page to see if it was the problem, but still not running the hint or the solution

**Comment by jorijnsmit** [comment]
Can you provide some context for this? I don't see how it is related to the Kaggle API.

**Comment by gustavoalonso93** [comment]
I already managed to solve thanks
