### ISSUE TITLE
No authentication instructions in README

### ISSUE THREAD

**Issue by Guitaricet** [Kaggle/kaggle-api#242]
Thank you for Kaggle API!
I think README is missing Authentication section. I forgot how it is done and neeed to install kaggle api on my computer, it was not clear what to do from the README and I had to google it.
It is not a big problem, but you can probably just copy this seciton from kaggle.com/docs/api

**Comment by jorijnsmit** [comment]
What's wrong with the current [API credentials](https://github.com/Kaggle/kaggle-api/blob/master/README.md#api-credentials) section in the README? Looks complete to me.

**Comment by Guitaricet** [comment]
I am sorry. Don't know why I missed it.
