### ISSUE TITLE
Dataset creation error: The requested title "******" is already in use by a dataset. Please choose another title.

### ISSUE THREAD

**Issue by GOSSAN0602** [Kaggle/kaggle-api#243]
When I use datasets create command
`kaggle datasets create -p ./trained_resnext101`
I get this error
`Dataset creation error: The requested title "******" is already in use by a dataset. Please choose another title.`
I get an error no matter what the title written in dataset-metadata.json .

API version is 1.5.6

**Comment by jorijnsmit** [comment]
Can you share the first part of your `dataset-metadata.json`?

**Comment by kshitiz52** [comment]
I too have the same problem.

**Comment by jorijnsmit** [comment]
Can you share the first part of your `dataset-metadata.json`?

**Comment by kshitiz52** [comment]
Hi,
Thank you for the reply.
Actually, I uploaded a Zip file (~1GB) into my dataset and later deleted
it. But now I have been trying to upload the same dataset in my dataset but
I got the error (The requested title "******" is already in use by a
dataset. ).

Please let me know if you want me to share the zipped file from my
google drive ?

Best Regards,

Kshitiz Dhakal
Graduate Research Assistant, Ph.D. Student
School of Plant and Environmental Sciences
Virginia Polytechnic Institute and State University (Virginia Tech),
Blacksburg, VA 24061
Email: kshitiz@vt.edu <jylee43@vt.edu> | Skype: xanith.ctiz | Cell:
+1-443-301-8101
b Result with Site Links

**Comment by jorijnsmit** [comment]
Your issue is a bit difficult to debug without knowing what your actual command is, but I think you are looking for `kaggle datasets version`: https://www.kaggle.com/docs/api#create-a-new-dataset-version

**Comment by kshitiz52** [comment]
FYI: I am using the web version of kaggle not the command line.

Kshitiz Dhakal
Graduate Research Assistant, Ph.D. Student
School of Plant and Environmental Sciences
Virginia Polytechnic Institute and State University (Virginia Tech),
Blacksburg, VA 24061
Email: kshitiz@vt.edu <jylee43@vt.edu> | Skype: xanith.ctiz | Cell:
+1-443-301-8101
b Result with Site Links

**Comment by zimonitrome** [comment]
I got the same issue through the web GUI @jorijnsmit.
My error was that I uploaded a dataset but a file contained an invalid character.
So the page for the dataset was never created but when I try to create it again I get the same error:

```The requested title "____" is already in use by a dataset. Please choose another title.```

**Comment by AGenchev** [comment]
> I got the same issue through the web GUI @jorijnsmit.
> My error was that I uploaded a dataset but a file contained an invalid character.
> So the page for the dataset was never created but when I try to create it again I get the same error:
> 
> `The requested title "____" is already in use by a dataset. Please choose another title.`

I have thesame issue - the dataset creation failed (due to invalid character in a filename) so it was not created. But then any subsequent try fails with error The requested title "***" is already in use by a dataset. Please choose another title.

**Comment by Timmate** [comment]
Got the same error, but instead of first running into an error with an invalid character in a filename or whatever, I accidentally exceeded my private dataset quota while attempting to upload a dataset and therefore ran into an exception saying "The size of your files is X bytes, it exceeds the maximum of Y bytes.". Reclaiming enough private dataset space by erasing some private datasets and afterward re-trying to upload the same dataset using the exact same dataset-metadata.json file led to the the same exception as the one mentioned in the title and throughout this thread. Kaggle API version: 1.5.12

**Comment by lextoumbourou** [comment]
I think the solution may be to upload a new version of the dataset:

Something like:

```
kaggle datasets version --path . --dir-mode zip -m "Init version"
```

It is insanely annoying that Kaggle uploads the files first and then checks if the dataset is valid. When you have a big dataset, it can be an hour before you learn if the command has succeeded or not.
