### ISSUE TITLE
Dataset creation error: You are not allowed to create a dataset as this owner.

### ISSUE THREAD

**Issue by alexeygrigorev** [Kaggle/kaggle-api#25]
I try to create a dataset with two gzipped json line files.

What I do:
- `pip install kaggle` (the downloaded version is `kaggle==1.1.0`)
- place the token to `~/.kaggle/kaggle.json`
- invoke `kaggle datasets init -p kaggle_code/`
- edit the content of `kaggle_code/datapackage.json` to look like that:
```
{"licenses": [{"name": "CC0-1.0"}],
"id": "agrigorev/codeforces-code",
"title": "The source code scraped from codeforces.com"}
```
- call `kaggle datasets create -p kaggle_code/`. This is what I get:
```
Upload successful: dump-tokenized.jsonl.gz (274MB)
Upload successful: dump-original.jsonl.gz (346MB)
Dataset creation error: You are not allowed to create a dataset as this owner.
```

Link to my kaggle page is https://www.kaggle.com/agrigorev/

**Comment by andyharless** [comment]
I have the same problem.
```
{"id": "aharless/tdsub1", "title": "TD sub from 75 million rows", "licenses": [{"name": "CC0-1.0"}]}
```
I tried unzipping them. Still doesn't work.
```
Upload successful: sub_it0_val.csv (578MB)
Upload successful: sub_it0.csv (520MB)
Dataset creation error: You are not allowed to create a dataset as this owner.
```
[My profile](https://www.kaggle.com/aharless)
I have no problem creating a dataset via the usual Web GUI, so clearly I am allowed to create a dataset.  Also so far I have had no problem with submissions or downloads via the API.

**Comment by rrqq** [comment]
Same Issue:

Dataset creation error: You are not allowed to create a dataset as this owner.

**Comment by rysteboe** [comment]
FYI - I haven't investigated this yet, but I'm going into bug fixing mode and this one is high on my list.  I'll hopefully have a fix out soon.

**Comment by rysteboe** [comment]
Should be fixed now - please let me know if you have any additional problems.
