### ISSUE TITLE
Document for python api

### ISSUE THREAD

**Issue by flyfj** [Kaggle/kaggle-api#250]
Surprisingly, there doesn't seem to be any document for the python api. Some examples online don't work at more. Any information about where can we find such things if it ever exists?

**Comment by jorijnsmit** [comment]
This question on StackOverflow has some interesting information: https://stackoverflow.com/questions/55934733/documentation-for-kaggle-api-within-python. Also I posted this exact same question a while back on the Kaggle forums: https://www.kaggle.com/general/130766.

**Comment by flyfj** [comment]
> This question on StackOverflow has some interesting information: https://stackoverflow.com/questions/55934733/documentation-for-kaggle-api-within-python. Also I posted this exact same question a while back on the Kaggle forums: https://www.kaggle.com/general/130766.

Thanks for the reply, although the api doesn't seem to be working using the document, giving me 'module kaggle has no attribute api' error.

**Comment by shangeethas** [comment]
@flyfj What do you really mean by python api ?

**Comment by jorijnsmit** [comment]
I think what he is talking about is using Kaggle's Python package directly in Python instead of through the command-line.

Like instead of calling `os.system(kaggle [...])` from within Python and let it run a new Python script in the background, use `import kaggle` and call its functions directly.

**Comment by mukatee** [comment]
There is some Swagger API interleaved with the "kaggle" package here. And documentation is very poor in relation to calling this an API.

I had a look myself and wrote it down in a Kaggle kernel:

https://www.kaggle.com/donkeys/kaggle-python-api

**Comment by Mike-Honey** [comment]
I was also really confused by this at first - I felt sure I was missing something. I'm glad to hear it's not just me ...

The top answer on that SO post is helpful, it also links to a blog post.  But both of those seem poor substitutes for documentation that you would hope would be produced by the authors.

**Comment by tharindusathis** [comment]
Kaggle API – The Missing Python Documentation: https://technowhisp.com/kaggle-api-python-documentation/

**Comment by Philmod** [comment]
What about the README on this repo https://github.com/Kaggle/kaggle-api ?
