### ISSUE TITLE
kaggle competitions download command returning 404 not found

### ISSUE THREAD

**Issue by subhankar-ghosh** [Kaggle/kaggle-api#254]
I am trying to download the data for https://www.kaggle.com/c/outbrain-click-prediction/overview
competition (completed competition).
- I have a valid Kaggle account
- I have accepted the terms and conditions of the competition
- I have the latest version of Kaggle API 

I used this command to download the data:
`kaggle competitions download -c outbrain-click-prediction`

I am getting this error:
404 - Not Found

**Comment by Sgsouham** [comment]
use an ! mark before the statement. eg- 
! kaggle competitions download -c outbrain-click-prediction

Works for me

**Comment by nmay231** [comment]
Looks like it's simply an error with the API and not the cli. Trying to manually "download all" from the site also fails with a 404.

https://www.kaggle.com/c/outbrain-click-prediction/data
