### ISSUE TITLE
How can I update the kaggle api?

### ISSUE THREAD

**Issue by paras-jain** [Kaggle/kaggle-api#260]
Running `!kaggle competitions download -c bike-sharing-demand` gives the following error:
`Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.6 / client 1.5.4)`

I am using google colab, I read through previous issues; I have also accepted the competition rules.

Now, how can I update the kaggle api?

**Comment by stoufa** [comment]
Try this
```
!pip uninstall -y kaggle
!pip install --upgrade pip
!pip install kaggle==1.5.6
!kaggle -v
```
Credit: https://www.kaggle.com/c/rsna-intracranial-hemorrhage-detection/discussion/109520

**Comment by paras-jain** [comment]
Worked wonders, thanks!
