### ISSUE TITLE
Push tpu kernel  problem

### ISSUE THREAD

**Issue by gray2020** [Kaggle/kaggle-api#261]
I want to push a  tpu enabled kernel using kaggle-api 
`kaggle kernels push -p toxic`
But I can't find `tpu_enable` in the [metadata field supported](https://github.com/Kaggle/kaggle-api/wiki/Kernel-Metadata).
Is there anyway to push a kernel and enable the tpu?

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
