### ISSUE TITLE
How do I solve ‘Could not find kaggle.json’?

### ISSUE THREAD

**Issue by teowu** [Kaggle/kaggle-api#264]
As is mentioned...

**Comment by Sgsouham** [comment]
1)from google.colab import files
files.upload()
after you run this code snippet you will get an option to upload the json file from your system into the working directory.

2)After installing the kaggle api for colab(just in case you are working in it), you need to make a directory kaggle using :- ! mkdir ~/.kaggle
3)after this copy the kaggle.json that is in your local system into this folder by using-
! cp kaggle.json ~/.kaggle/
4)use the ! chmod 600 ~/.kaggle/kaggle.json command to change the access type of the kaggle directory and you api should be working fine.
