### ISSUE TITLE
downloading library

### ISSUE THREAD

**Issue by lelsener7** [Kaggle/kaggle-api#27]
I installed the library using pip install kaggle and then created the token and saved my API credentials in ~/.kaggle/

However, when I try to run any of the kaggle commands in terminal, I get this error:
-bash: kaggle: command not found

**Comment by rysteboe** [comment]
What API version did you download?  I assume `1.1.0`?  Did the error persist after restarting your terminal session?

**Comment by lelsener7** [comment]
This is the output from terminal after installing kaggle:

Lauras-MBP:~ Lels7$ pip install kaggle
Collecting kaggle
  Downloading https://files.pythonhosted.org/packages/c7/85/16bab6a9328d62d14f162b82eace751be2e6ac97c3433edc4ea48ae1d407/kaggle-1.2.1.tar.gz
Collecting urllib3>=1.15 (from kaggle)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 663kB/s 
Collecting six>=1.10 (from kaggle)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting certifi (from kaggle)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 975kB/s 
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from kaggle) (1.5)
Installing collected packages: urllib3, six, certifi, kaggle

After restarting my terminal session, this happens when I try to use a command:
Lauras-MBP:~ Lels7$ kaggle competitions list 
-bash: kaggle: command not found

**Comment by lelsener7** [comment]
Was a problem with my PATH file -- figured it out. Thanks!
