### ISSUE TITLE
Swagger.json available?

### ISSUE THREAD

**Issue by gitfvb** [Kaggle/kaggle-api#28]
Hi kaggle,

The API looks very promising.... Is it possible to share the swagger.json location so there are more ways to connect to the API? [Swagger JSON](https://www.kaggle.com/api/v1/swagger.json) didn't work.

Thanks
Florian

**Comment by rysteboe** [comment]
I have on my todo list to expose more of the code that is currently closed source.  The first step of that will be `KaggleSwagger.yaml`.  Hoping to do that soon (this week).

**Comment by rysteboe** [comment]
Both `KaggleSwagger.yaml` and `KaggleSwaggerConfig.json` are in the repo now.  Let me know if you need anything else.
