### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by vaibhawc** [Kaggle/kaggle-api#29]
I pip installed it. Placed json at right place.
But "kaggle: command not found".

**Comment by rysteboe** [comment]
Which version was installed?  You may need to restart your terminal session.

**Comment by vaibhawc** [comment]
I did it yesterday. That must be latest. I restarted the everything. Still doesn't.

**Comment by rysteboe** [comment]
I suspect that the binary is not on your path.  Can you please `echo $PATH` and paste the results?

**Comment by rysteboe** [comment]
You need for python's binary directory to be on your path.  For a `pip install kaggle --user` on Linux, this is `~/.local/bin`.  On Windows, it's something like `{python-root}/bin`.

**Comment by vaibhawc** [comment]
My `echo $PATH` : 
`/home/mangal/bin:/home/mangal/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

On `ls ~/.local/bin` : 
```
easy_install      f2py          markdown_py  pip3    saved_model_cli  toco              wheel
easy_install-3.5  freeze_graph  pip          pip3.5  tensorboard      toco_from_protos

```

So it does seem like that the binary is still not there!

But when I did `pip uninstall kaggle` , strange enough : 
```
Skipping kaggle as it is not installed.
```

This creates suspicion but when I do `pip install kaggle`, it doesn't appear as if anything went wrong.
Could it something wrong with pip?

![screenshot from 2018-04-18 23-27-16](https://user-images.githubusercontent.com/18726502/38949455-17e5ccf8-4360-11e8-90c8-9f6f3ee5b221.png)

 ¯\_(ツ)_/¯

**Comment by rysteboe** [comment]
Hmm, that's really weird.  Do a `whereis kaggle` just to confirm that it's not being installed elsewhere - I don't remember where python drops system binaries.  If that turns up nothing, try `pip install --user kaggle`.  That will only install it for your user.  I'm skeptical about that working, though.  You can also try `pip show kaggle`, but if it's not detecting it for removal, then that probably won't work either.

**Comment by rysteboe** [comment]
I would also check `/etc/pip.conf`, `$HOME/$XDG_CONFIG_HOME/pip/pip.conf` (defaults to `~/.config/pip/pip.conf`), and `$HOME/.pip/pip.conf`  to see if there's anything weird there.

**Comment by rysteboe** [comment]
Yeah, I have an to do item to improve the installation instructions, since you're not the first one to have that problem.

**Comment by josephthweatt** [comment]
@rysteboe I also used `pip install --user kaggle` and was able to get `pip show kaggle` to work. However, the terminal still tells me `kaggle: command not found`. Also `whereis kaggle` returns nothing, which is kinda weird.

Do you have any idea why this might be? I'm fairly new to pip, but I think that if it is installed I should have the command available.

**Comment by rysteboe** [comment]
Did you do the following? 

> You need for python's binary directory to be on your path. For a pip install kaggle --user on Linux, this is ~/.local/bin. On Windows, it's something like {python-root}/bin. You can find the exact path by doing pip uninstall kaggle and looking for the executable in the list of files that it says it would remove.

**Comment by nikhiljay** [comment]
I just installed kaggle using python 3 and it works: `pip3 install kaggle`

**Comment by josephthweatt** [comment]
@rysteboe I did check the binaries but was not entirely sure if that was the issue. I looked at @nikhiljay's comment and found that python3 was not installed on my current computer. I downloaded that and installed kaggle with `python3 -m pip install kaggle` (`pip3` was not a recognized command).
In any case kaggle is fully installed. If you are planning on adding to installation instructions, it might help to specify installation with python3.

**Comment by rysteboe** [comment]
It's not, strictly speaking, a python2 problem.  python2 is all I have installed on my laptop and it works.  Honestly, the API has been tested much less with 3 than with 2.  I still strongly suspect that the problem was with your path, but I'm glad that the problem was resolved either way.

**Comment by RaviGML** [comment]
**downloading kaggle API second time  and keeping at ~/.kaggle/ worked for me**

**Comment by thebeancounter** [comment]
Still getting the same error,  after installing with pip3

**Comment by SoleSensei** [comment]
Reinstall works for me:
```bash
python3 -m pip uninstall kaggle
```
and then
```bash
python3 -m pip install kaggle
```

**Comment by thegopieffect** [comment]
> Reinstall works for me:
> 
> ```shell
> $ kaggle
> "kaggle": command not found
> $ python3 -m pip uninstall kaggle
> ```
> 
> and then
> 
> ```shell
> $ python3 -m pip install kaggle
> $ kaggle
> usage: kaggle [-h] [-v] {competitions,c,datasets,d,kernels,k,config} ...
> ```

This worked for me. Thank a lot.

**Comment by mhnamaki** [comment]
I've just restarted my ubuntu machine and it worked.

**Comment by RaccoonDML** [comment]
Reinstall works for me:

$ kaggle
"kaggle": command not found
$ python3 -m pip uninstall kaggle
and then

$ python3 -m pip install kaggle
$ kaggle
usage: kaggle [-h] [-v] {competitions,c,datasets,d,kernels,k,config} ...
This worked for me. Thank a lot.

**Comment by SeriousHyena** [comment]
> 
> 
> I just installed kaggle using python 3 and it works: `pip3 install kaggle`

After trying many other solutions this is the one that worked for me as well. I am running Windows 10 version 1909 and using jupyter notebooks and Python 3.7. also I installed directly into my anaconda environment.

**Comment by Maria-UET** [comment]
> > Reinstall works for me:
> > ```shell
> > $ kaggle
> > "kaggle": command not found
> > $ python3 -m pip uninstall kaggle
> > ```
> > 
> > 
> > and then
> > ```shell
> > $ python3 -m pip install kaggle
> > $ kaggle
> > usage: kaggle [-h] [-v] {competitions,c,datasets,d,kernels,k,config} ...
> > ```
> 
> This worked for me. Thank a lot.

This worked for me as well.

**Comment by patilabhay679** [comment]
try : sudo pip install kaggle

**Comment by LeoTungAnh** [comment]
The following solution works for me:
1. sudo pip install kaggle
2. I go to download  kaggle account on website of Kaggle to get API in format of "kaggle.json"
3. I move "kaggle.json" to /home/"user_name"/.kaggle

**Comment by valentin-fngr** [comment]
> pip install --user kaggle

Yep that works. 

Of course you need to do : 

`export PATH=/home/your_user/.local/bin`

**Comment by diakt** [comment]
> Reinstall works for me:
> 
> ```shell
> $ kaggle
> "kaggle": command not found
> $ python3 -m pip uninstall kaggle
> ```
> 
> and then
> 
> ```shell
> $ python3 -m pip install kaggle
> $ kaggle
> usage: kaggle [-h] [-v] {competitions,c,datasets,d,kernels,k,config} ...
> ```

Worked for me.
