### ISSUE TITLE
Add environmental based token

### ISSUE THREAD

**Issue by exp0nge** [Kaggle/kaggle-api#30]
It's really restricting to have to use the file based token storage. It would be nice and _easier_ to debug to use environmental variables instead.

**Comment by vsoch** [comment]
I can take a stab at this!

**Comment by exp0nge** [comment]
That would be great.

**Comment by vsoch** [comment]
I'm finished up for this, but I need to do some testing, and I ran out of steam for today! I'll definitely get the PR in sometime tomorrow. Stay tuned!

**Comment by vsoch** [comment]
hey @exp0nge I just opened a PR here --> https://github.com/Kaggle/kaggle-api/pull/57 note that we definitely need tests before this goes through, and I think the lead developer might be on holiday, so TLDR stay tuned!

**Comment by rysteboe** [comment]
Released as 1.4.6.  Closing this out - let me know if there are any problems!

**Comment by vsoch** [comment]
@rysteboe can I help with docstrings? Have you decided on a format?

**Comment by rysteboe** [comment]
@vsoch what you were doing is fine.  Additional documentation is not high on my to do list atm, so anything you do in that area is appreciated.

**Comment by vsoch** [comment]
okay cool! I'm working on some boring stuff this morning, but will want to contribute this soon :)
