### ISSUE TITLE
ValueError: Error: Missing username in configuration

### ISSUE THREAD

**Issue by mgavish** [Kaggle/kaggle-api#305]
I'm on a windows pc using Ubuntu and bash under wsl (windows subsystem for linux)
I pip installed kaggle and put the `kaggle.json` in `~/.kaggle` but get the bellow error:

`Traceback (most recent call last):`  

  `File "document_similarity_search.py", line 12, in <module>from kaggle import KaggleApi`    

  `File "/home/matan/.local/lib/python3.7/site-packages/kaggle/__init__.py", line 23, in <module>api.authenticate()`

  `File "/home/matan/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 169, in authenticate
    self._load_config(config_data)`

  `File "/home/matan/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 210, in _load_config
    raise ValueError('Error: Missing %s in configuration.' % item)`

`ValueError: Error: Missing username in configuration.`

I then tried adding the environment variables `KAGGLE_USERNAME` and `KAGGLE_KEY` which seem to work in bash running a `.py` but but not in a jupyter notebook on a local server (the environment variables dissapear in new shell instances using `export` and still don't work after adding to `.bashrc` and `.prifile` ).  Additionally, when I run the jupyter notebook in vsCode, (under wsl: ubuntu) I get `ModuleNotFoundError: No module named 'kaggle'`

**Comment by jorijnsmit** [comment]
It appears your Jupyter notebooks are running in a different environment and therefore do not have access to `kaggle.json` and/or the `kaggle` module.

A quick fix would be to manually configure your authentication details and install kaggle in a cell in your notebook:
```
import os

os.environ['KAGGLE_USERNAME'] = 'username'
os.environ['KAGGLE_KEY'] = 'key'

!pip install kaggle
```
