### ISSUE TITLE
Not all files are listed when use `files` command

### ISSUE THREAD

**Issue by detkov** [Kaggle/kaggle-api#308]
Problem occurs when trying to get files from "RSNA STR Pulmonary Embolism Detection":
`kaggle competitions files rsna-str-pulmonary-embolism-detection`
There should be more than 1.94m of `.dcm` files and 3 `.csv`, but only 800 of of `.dcm` files and 3 `.csv` are presented.

**Comment by eet182561** [comment]
Facing same issue with rfcx-species-audio-detection. Not all files are listed.
