### ISSUE TITLE
question of kaggle API in Colab

### ISSUE THREAD

**Issue by hspierre** [Kaggle/kaggle-api#312]
Hi, 
The version og Kaggle API in Colab is 1.5.9
Requirement already up-to-date: kaggle in /usr/local/lib/python3.6/dist-packages (1.5.9)
However, error message in Colab is as following when I execute " !kaggle kernels list --user pierreth --sort-by dateRun "
00 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api

Please tell me how to do next. Thanks

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
