### ISSUE TITLE
i verified my phone number and also verified the code given by kaggle to my phone but still getting 403 error

### ISSUE THREAD

**Issue by balaji-skoruz** [Kaggle/kaggle-api#319]
i verified my phone number and also verified the code given by kaggle to my phone but still getting 403 error
on :  kaggle competitions download -c dogs-vs-cats

_Originally posted by @Fasih1994 in https://github.com/Kaggle/kaggle-api/issues/87#issuecomment-474231848_

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
