### ISSUE TITLE
real time collaborator coding on notebook kernels

### ISSUE THREAD

**Issue by YasPHP** [Kaggle/kaggle-api#327]
The version control for the competition notebook kernels gets very inefficient when multi-working versions arise with multiple collaborators' quick saves. Will there be an implementation of live collaborator coding any time soon? Something like http://repl.it/ but for kaggle's notebook kernels.

**Comment by Philmod** [comment]
Thanks for the feature request, it's unrelated to the kaggle-api, so I submitted it internally.
