### ISSUE TITLE
Cannot search for datasets with a CC license

### ISSUE THREAD

**Issue by HarroTuin** [Kaggle/kaggle-api#333]
The following command does not work for me: "kaggle datasets list --license cc". It does work when specifying other licenses (gpl, odb).

**Comment by devblin** [comment]
Are you getting any error messages ? 
As you can see in below image, command `kaggle datasets list --license cc` is working for me.
![image](https://user-images.githubusercontent.com/55559527/111271809-bad91e00-8657-11eb-8c86-0f5bed400cba.png)

**Comment by HarroTuin** [comment]
That's odd. Right now it is working fine for me as well.
