### ISSUE TITLE
Resuming downloads

### ISSUE THREAD

**Issue by pierretallotte** [Kaggle/kaggle-api#341]
The dataset and the data of a competition can be very large and take time to download. It could be interesting to have the possibility to stop and resume a download (or to resume an interrupted download) using the Kaggle API.
For instance, if you stop a download started using `kaggle competition download`, if you launch the command again in the same folder, the download continues where it stops.

**Comment by Philmod** [comment]
Internal bug: http://b/130297872

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
