### ISSUE TITLE
404 error with kaggle-api 1.5.12

### ISSUE THREAD

**Issue by sorenwacker** [Kaggle/kaggle-api#344]
Just followed the comment in the terminal and upgraded the API, because the figures were downloaded but not in the folder structure training, test, etc. with the older API.

> Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.3)

Now, using `kaggle-1.5.12-py37h89c1867_` I get:

    kaggle competitions download -c bms-molecular-translation
    > 404 - Not Found

cannot download at all.

**Comment by soerendip** [comment]
Downgrading to 5.1.3 enabled the download, but the images are downloaded without the folder structure as described here: https://www.kaggle.com/c/bms-molecular-translation/data

And then the download suddenly stopped with

> 429 - Too Many Requests

**Comment by osamirabo** [comment]
same problem here

**Comment by soerendip** [comment]
You have to go to the webpage first and accept the conditions of usage.

**Comment by osamirabo** [comment]
I solved the problem of 401 - Unauthorized, it seems that I need to change the kaggle.json in colab to be under /root/.kaggle instead of /content/.kaggle (also it worked before), thanks for help. now i  am facing 404 - Not Found

**Comment by whoafridi** [comment]
same happens  to me also. any solution??

**Comment by osamirabo** [comment]
According to this discussion they are working on fixing the issue

https://www.kaggle.com/c/bms-molecular-translation/discussion/232027

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
