### ISSUE TITLE
Kernel not found - unable to create new kernels using the api

### ISSUE THREAD

**Issue by signinit** [Kaggle/kaggle-api#345]
I am currently unable to create any new Kernels with the API. I am receiving the error "Kernel not found". Existing kernels can be edited, but no new kernels can be created.

response for rest API using: https://www.kaggle.com/api/v1/kernels/push
```JSON
{
"ref": null,
"url": null,
"versionNumber": null,
"error": "Kernel not found",
"invalidTags": [],
"invalidDatasetSources": [],
"invalidCompetitionSources": [],
"invalidKernelSources": [],
}
```

response for CLI using: Kaggle kernels push
`Kernel push error: Kernel not found`

Tested using the CLI tool and raw API access. The problem also occurs for other people in different environments.

**Comment by timoboz** [comment]
Thanks for reporting! Looks like we unfortunately introduced this bug during an internal migration a few days ago. I just pushed a fix, it should work again now as it did previously.
