### ISSUE TITLE
Error in download the whole dataset

### ISSUE THREAD

**Issue by whoafridi** [Kaggle/kaggle-api#346]
When downloading the dataset comes with this error & the whole dataset isn't downloading. (try with google colab)
```py
!kaggle competitions download -c plant-pathology-2021-fgvc8
```
output
```py
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
```
just download couple of files. only 5/10MBs. whereas dataset is 14.94GB

**Comment by Abhiram4572** [comment]
`!pip install --upgrade --force-reinstall --no-deps kaggle`

this has fixed the issue for me (on google colab)

**Comment by Abhiram4572** [comment]
> When downloading the dataset comes with this error & the whole dataset isn't downloading. (try with google colab)
> 
> ```python
> !kaggle competitions download -c plant-pathology-2021-fgvc8
> ```
> 
> output
> 
> ```python
> Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
> ```
> 
> just download couple of files. only 5/10MBs. whereas dataset is 14.94GB

`!pip install --upgrade --force-reinstall --no-deps kaggle`

this has fixed the issue for me (on google colab)

**Comment by whoafridi** [comment]
@Abhiram4572 Thanks,. It's helped me a lot.
