### ISSUE TITLE
404 error with allen-institute-for-ai/CORD-19-research-challenge

### ISSUE THREAD

**Issue by orkuntemiz** [Kaggle/kaggle-api#348]
I have tried to download this dataset to colab with kaggle api 1.5.3, 1.5.4, 1.5.6. I am getting 404 not found error. 1 week before I could download this file smoothly. Help please !

**Comment by jplotts** [comment]
Hi @orkuntemiz - I'm not able to reproduce this issue.  We're currently on version 1.5.12 of the API, so you might consider updating to something more recent, although I'm not sure that would help.  What's the command you're using?

**Comment by orkuntemiz** [comment]
Hello, the problem is resolved somehow although, I did not changed any single line of code.
The full code I am using is below.
!pip install -U kaggle==1.5.6
from google.colab import files
files.upload()
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets list
!kaggle -v
!kaggle datasets download -d allen-institute-for-ai/CORD-19-research-challenge

**Comment by yeonsookKwak** [comment]
I have same issue. But yesterday same code and same situation was fine though.
Restarting computer, notebook cell also tried and has same issue.
I'm using google colab pro version.
And below code was used.
!pip install -q kaggle
from google.colab import files
files.upload()
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!ls ~/.kaggle
!chmod 600 /root/.kaggle/kaggle.json
!kaggle datasets download -d allen-institute-for-ai/CORD-19-research-challenge
