### ISSUE TITLE
Failed when Creating New API Token 

### ISSUE THREAD

**Issue by Nandayang** [Kaggle/kaggle-api#352]
An error has occurred. Please try again. 
Does anyone know how to fix this? Refreshing the page or cleaning the cookies didn't work.

**Comment by Ark23Barca** [comment]
Same Here mate... I thought I was the only one who was facing this Issue !
-
Some maintenance maybe?

**Comment by Julius-R-UI** [comment]
Same here

**Comment by Thejineaswar** [comment]
I have been facing the same problem as well...

**Comment by Thejineaswar** [comment]
I have been facing this problem as well....

**Comment by HimanshuKGP007** [comment]
Facing the same issue.

**Comment by meg890** [comment]
facing the same issue

**Comment by eeshangpt** [comment]
Facing the same issue

**Comment by Ark23Barca** [comment]
The problem has been resolved !!!
-
Check it out guyz.

**Comment by meg890** [comment]
Thanks for notifying us!

**Comment by yeniihi** [comment]
same problem..
