### ISSUE TITLE
kaggle kernels push -k: unrecognized arguments: -k

### ISSUE THREAD

**Issue by tbrodbeck** [Kaggle/kaggle-api#355]
On this side https://www.kaggle.com/docs/api#interacting-with-notebooks it says you have to reference the kernel by `-k` when using `kaggle kernels push` . But this returns `kaggle: error: unrecognized arguments: -k`

**Comment by jplotts** [comment]
Hi @tbrodbeck - thanks for reporting this issue!  I've updated our documentation accordingly.
