### ISSUE TITLE
AttributeError: module 'pyarrow.lib' has no attribute '_Weakrefable'

### ISSUE THREAD

**Issue by bhargav-inthezone** [Kaggle/kaggle-api#358]
hey !,
I'm working kaggle notebooks for a competition 

!pip install vaex  ## sucessfully installed

import vaex
print(vaex.__version__)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-2d4bdef9460d> in <module>
----> 1 import vaex
      2 import vaex.ml
      3 print(vaex.__version__)

/opt/conda/lib/python3.7/site-packages/vaex/__init__.py in <module>
     39 import six
     40 
---> 41 import vaex.dataframe
     42 import vaex.dataset
     43 from vaex.functions import register_function

/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in <module>
     15 import threading
     16 import six
---> 17 import vaex.utils
     18 # import vaex.image
     19 import numpy as np

/opt/conda/lib/python3.7/site-packages/vaex/utils.py in <module>
     24 
     25 from .json import VaexJsonEncoder, VaexJsonDecoder
---> 26 import vaex.file
     27 
     28 

/opt/conda/lib/python3.7/site-packages/vaex/file/__init__.py in <module>
     12 
     13 import pyarrow as pa
---> 14 import pyarrow.fs
     15 
     16 import vaex.file.cache

/opt/conda/lib/python3.7/site-packages/pyarrow/fs.py in <module>
     22 from pyarrow.util import _is_path_like, _stringify_path
     23 
---> 24 from pyarrow._fs import (  # noqa
     25     FileSelector,
     26     FileType,

/opt/conda/lib/python3.7/site-packages/pyarrow/_fs.pyx in init pyarrow._fs()

AttributeError: module 'pyarrow.lib' has no attribute '_Weakrefable'

**Comment by Philmod** [comment]
Hi,

This seems to be an issue with vaex package, here is their repo: https://github.com/vaexio/vaex

For any problem linked to Kaggle python image: https://github.com/kaggle/docker-python

Best,
Philippe
