### ISSUE TITLE
datasets create 400 - Bad Request

### ISSUE THREAD

**Issue by cmosguy** [Kaggle/kaggle-api#361]
I was trying to upload a dataset in my path and I am getting a **400 - Bad Request**

```bash
kaggle datasets create -p .

Starting upload for file CheXper-v1.0-small-normal_only.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 850M/850M [00:16<00:00, 52.6MB/s]
Upload successful: CheXper-v1.0-small-normal_only.zip (850MB)
Starting upload for file train.csv
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23.4M/23.4M [00:00<00:00, 58.4MB/s]
Upload successful: train.csv (23MB)
400 - Bad Request
```

What do I do?

**Comment by JacobHP** [comment]
I had this today. When I manually uploaded the data on the Kaggle website I got an error as I already had a kernel sharing the name of the dataset I was trying to create. Might be worth checking this.

**Comment by talkhaldi** [comment]
I have the same problem and I'm not sure what's wrong.
I have:
- initialized it with: kaggle datasets init -p /path/to/dataset
- modified the resulting json to change the default slug
- created datapackage.json and put some details and resources property that contains things in the above json

still getting 400 - Bad Request after upload is complete. Creating the dataset through the web UI and uploading a zipped file worked though.

**Comment by inkyusa** [comment]
Same here...

**Comment by kingabzpro** [comment]
same here😢

**Comment by gaetanlop** [comment]
same here ...

**Comment by kingabzpro** [comment]
> same here😢

I have solved mine by adding data. This error is generated when you have no files in the folder.  Do check your folder or folder location.

**Comment by maplefallfrost** [comment]
Same here

**Comment by souhei827** [comment]
same here

**Comment by rayliuca** [comment]
I have tested this with an update to an old dataset with
`! kaggle datasets version -p "$folder_to_upload" --dir-mode zip -m "update"`
which was using the exact same script I used before.

It worked sometime last month but is no longer working, throwing the `400 - Bad Request` error

My last dataset create API call "appears" to be successful was on Jun 24 with 
`Your private Dataset is being created. Please check progress at /api/v1/datasets/status//rayliuca/CML-Trained-Models`
but the dataset never showed up even though my used capacity is way below the 100GB limit

**Comment by serabiasin** [comment]
same here, is there any solution beside updating dataset from  kaggle website?

**Comment by ibraheem-moosa** [comment]
I'm facing same issue with datasets version. :(

**Comment by gautierdag** [comment]
Same here, getting `400 - Bad Request` error on every API dataset write command both`datasets create` and `datasets update`. 

Thought it was due to an unmentionned limit on my account being reached (I have some large datasets with a lot of versions) - so I went and deleted every large datasets I had just to make sure, but seems like I still have the same problem and it was not due to capacity.

**Comment by Tommy-Ngx** [comment]
Skipping folder: .git; use '--dir-mode' to upload folders
400 - Bad Request

I get the same issue, I tried to get new api, token, upgrade but failed! 
please help!

**Comment by cccntu** [comment]
Same issue today, last time I used it was ~ a month ago.

**Comment by shubhamscifi** [comment]
I am also getting the same error.

**Comment by erdalsivri** [comment]
This should be fixed now. Please let us know if you still have issues creating a dataset

**Comment by Tommy-Ngx** [comment]
100% 820M/820M [00:15<00:00, 56.0MB/s]
Upload successful: MINIST.zip (82MB)
400 - Bad Request

Still error! Upload successful but the same issue! Bad request!

**Comment by ibraheem-moosa** [comment]
Issue is fixed for me. I have tested with datasets version. Thanks @erdalsivri

**Comment by maplefallfrost** [comment]
still 400 bad request error with command kaggle datasets create -p path

**Comment by shubhamscifi** [comment]
For me, both dataset creation and new version creation are working fine now.

**Comment by inkyusa** [comment]
> This should be fixed now. Please let us know if you still have issues creating a dataset

I am still facing the same 400 - Bad Request

**Comment by chandeepadissanayake** [comment]
Still facing the same issue!
