### ISSUE TITLE
The term "kaggle" not recognised by powershell 

### ISSUE THREAD

**Issue by Adrg01** [Kaggle/kaggle-api#365]
I'm getting the following error on entering `kaggle config view` or any other kaggle command in the powershell.
`
kaggle : The term 'kaggle' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ kaggle config view
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (kaggle:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
`
However my setup might have a probelmatic history as I was unable to find the .kaggle folder to place the kaggle.json file. Taking a suggestion from here, I created the folder in my user directory and placed the file in there.

**Comment by neymar-jr** [comment]
I met the same problem. How to fix it?
