### ISSUE TITLE
How can I set a kernel as utility-script in the kernel-metadata.json?

### ISSUE THREAD

**Issue by gloryVine** [Kaggle/kaggle-api#372]
I want to re-use code from one kernel in another, if possible without going via the website. Does the Kaggle API allow for this? I am aware of the possiblity to upload code as a dataset, but this would add an additional step which seems unnecessary since the code I want to re-use is already pushed once as a kernel.

**Comment by jplotts** [comment]
Yes, you can use utility scripts, using the process described in [this issue](https://github.com/Kaggle/kaggle-api/issues/225).
