### ISSUE TITLE
when I upload dataset I get stuck 

### ISSUE THREAD

**Issue by AtwoodDuan** [Kaggle/kaggle-api#376]
HI,
thank you read me

I  can download dataset ,but when I upload dataset I get stuck .
I have tried set proxy and unset. It have no difference.

my environment:
Ubuntu 20.04.2
python 3.8.5
kaggle==1.5.12

download:
![image](https://user-images.githubusercontent.com/19813460/130752662-287016b3-c341-4662-ba27-e7b37dd51865.png)

upload:
![image](https://user-images.githubusercontent.com/19813460/130752544-fc45b0c9-24a0-429b-b01d-2a0d2216379b.png)

**Comment by Philmod** [comment]
Could you try a different network and/or a different computer?

That seems related to your setup.
