### ISSUE TITLE
Bug during kernel-metadata.json generation ("competition_sources")

### ISSUE THREAD

**Issue by S1M0N38** [Kaggle/kaggle-api#377]
## Bug description

I pull a Kaggle kernel to my local machine.  The `-m` flag generate kernel metadata
```bash
kaggle kernels pull -p working -m s1m0n38/simone-bertolotto-857533
```

The generated `kernel-metadata.json` is:
```json
{
  "id": "s1m0n38/simone-bertolotto-857533",
  "id_no": 19985783,
  "title": "Simone Bertolotto 857533",
  "code_file": "simone-bertolotto-857533.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": true,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [
    "s1m0n38/simone-bertolotto-857533"
  ],
  "competition_sources": [
    "c/datamining2021"
  ]
}
```

After modify the notebook locally I try to upload it to Kaggle with
```bash
kaggle kernels push -p working
```

but this error message appears: 
`The following are not valid competition sources and could not be added to the kernel: ['c/datamining2021']`

## Fix

So I changed the competition_sources from `"c/datamining2021"` to `"datamining2021"` and then the upload was successful. I think that there is a bug in the kernel metadata generation process: there shouldn't be the extra `"c/"`.

**Comment by jplotts** [comment]
This should be resolved now.
