### ISSUE TITLE
Where is the kaggle kernel .ipynb stored?

### ISSUE THREAD

**Issue by neel04** [Kaggle/kaggle-api#378]
Had a quick question - where in the whole disk is the kaggle kernel (which we edit) is stored? I wanted to use `colabcode` without always doing the copy-paste or making a dedicated repo

**Comment by jplotts** [comment]
Hi @neel04 - I'm not sure what you mean by "where is it stored".  You can use the Kaggle API to get access to the .ipynb by doing a `kaggle kernels pull <username>/<kernel-slug>`.  Please respond if that doesn't resolve the issue.
