### ISSUE TITLE
400 - Bad Request While Creating Dataset

### ISSUE THREAD

**Issue by anantgupta129** [Kaggle/kaggle-api#381]
I am trying to upload dataset on kaggle using kaggle api, the dataset is around 2.5GB
But every time a try to upload it am having this error after upload is done

```
kaggle datasets create -p  .\Downloads\HerbDetection\
Starting upload for file test.zip
100%|███████████████████████████████████████████████████████████████████████████████| 409M/409M [03:11<00:00, 2.24MB/s]
Upload successful: test.zip (409MB)
Starting upload for file train.zip
100%|█████████████████████████████████████████████████████████████████████████████| 2.01G/2.01G [13:48<00:00, 2.60MB/s]
Upload successful: train.zip (2GB)
400 - Bad Request
```

This is my dataset metadata 
```
{
  "title": "Indian Herbs Classification",
  "id": "anantgupt/Indian Herbs Classification",
  "licenses": [
    {
      "name": "CC0-1.0"
    }
  ]
}
```
Can someone tell is there anything I am doing wrong

**Comment by erdalsivri** [comment]
I think the id of your dataset is malformed. It shouldn't contain any whitespace. Something like "anantgupt/indian-herbs-classification" should work. We should provide a better error message though

**Comment by anantgupta129** [comment]
> I think the id of your dataset is malformed. It shouldn't contain any whitespace. Something like "anantgupt/indian-herbs-classification" should work. We should provide a better error message though

**Comment by anantgupta129** [comment]
Hi @erdalsivri thanks for the reply 
Removing spaces worked & yes for error messages you guys may read the meta file and gives error according to the format

after uploading the dataset i got this message 
`Your private Dataset is being created. Please check progress at /api/v1/datasets/status//anantgupt/indian-herbs-classification`

What is this location at which this is pointing as i am unable to see the dataset

**Comment by erdalsivri** [comment]
I thought we had fixed that url. Anyway, the backend generates that so will prepare a PR to fix on the backend. The correct url to visit a dataset is `<user>/<dataset-id>` so you can just visit your dataset at http://www.kaggle.com/anantgupt/indian-herbs-classification

**Comment by anantgupta129** [comment]
@erdalsivri the link gives me error 404 page not found and I still cannot see the dataset in my dataset section

**Comment by erdalsivri** [comment]
Hmm, maybe there was a problem creating your dataset. Could you maybe ask this in the discussion forums? Someone from the datasets team might be able to help

**Comment by anantgupta129** [comment]
I asked but no one is replying 😶😐
