### ISSUE TITLE
Error 404 not found Error while downloading train Directory 

### ISSUE THREAD

**Issue by par1hsharma** [Kaggle/kaggle-api#385]
```
(tensorflow) parthsharma@Parths-MacBook-Air ~ % kaggle datasets download chest-xray-pneumonia -f train
404 - Not Found
(tensorflow) parthsharma@Parths-MacBook-Air ~ % 
(tensorflow) parthsharma@Parths-MacBook-Air ~ % kaggle --version            
Kaggle API 1.5.12
```
I am trying to download this dataset [https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia]
I only want to download train folder from this dataset

**Comment by jplotts** [comment]
Hi @par1hsharma - there are two issues with your command.  First, the id must include the user name, i.e. - `paultimothymooney/chest-xray-pneumonia` instead of `chest-xray-pneumonia`.  Second `-f` only works with a specific file, not a directory.  We don't currently support downloading a directory.

**Comment by par1hsharma** [comment]
@jplotts so I have to download complete dataset then?

**Comment by jplotts** [comment]
@par1hsharma - yes, you can download a single file or the entire dataset.  Those are the only two options that the API supports at this time.
