### ISSUE TITLE
Dataset not downloading on google colab

### ISSUE THREAD

**Issue by Hrushi11** [Kaggle/kaggle-api#391]
`Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)` I am getting this error message when I am trying to use the Kaggle API.

**Comment by jplotts** [comment]
Hi @Hrushi11 - as discussed in [this previous issue](https://github.com/Kaggle/kaggle-api/issues/382), the issue is with your Colab environment.  You need to update the Kaggle API.
