### ISSUE TITLE
Is it possible to fetch personal info?

### ISSUE THREAD

**Issue by r-matsuzaka** [Kaggle/kaggle-api#393]
Hi.
I have recently worked kaggle activity.
Is it possible to fetch personal info?
I thought that if I can fetch the number of medals I can create the history of the number of medals and then check my growth.
If anyone tell me about this, I would appreciate for it.
This API is not for this purpose, so this issue may be not appropriate...

**Comment by AdityaSoni19031997** [comment]
It's not made for this purpose I guess.
