### ISSUE TITLE
datasets/list empty response

### ISSUE THREAD

**Issue by MashinIvan** [Kaggle/kaggle-api#398]
Greetings!

Experiencing following issue:
Make authenticated request to /datasets/list with no query params. Expected result - get a list of top n hottest datasets. Actual result - empty array is returned, response status - 200.

Same is true for requests with `search`, `filetype`, `page` query params. Reproduces with python library with different accounts.

```python
api = KaggleApi()
api.authenticate()

result = api.dataset_list(search="reddit")
print(result)
```

```
GET /api/v1/datasets/list/ HTTP/1.1
Host: www.kaggle.com
Authorization: Basic 1234567890
```

info:
```
class KaggleApi(KaggleApi):
    __version__ = '1.5.12'
```

**Comment by Philmod** [comment]
Try using it as a CLI instead: `!kaggle datasets list -s reddit`
