### ISSUE TITLE
kaggle-cli 0.12.13 has requirement lxml<4.1,>=4.0.0, but you'll have lxml 4.2.1 which is incompatible.

### ISSUE THREAD

**Issue by jiapei100** [Kaggle/kaggle-api#40]
Fail to install kaggle using the command
`pip3 install kaggle`

> kaggle-cli 0.12.13 has requirement lxml<4.1,>=4.0.0, but you'll have lxml 4.2.1 which is incompatible.

Should kaggle update a bit?

Cheers
Pei

**Comment by rysteboe** [comment]
`kaggle-cli` is a different project - https://github.com/floydwch/kaggle-cli.  Are you sure that you did `pip3 install kaggle` and not `pip3 install kaggle-cli`?

**Comment by jiapei100** [comment]
@rysteboe 
Yes, you are absolutely correct... 

[https://github.com/floydwch/kaggle-cli/issues/76](https://github.com/floydwch/kaggle-cli/issues/76)
