### ISSUE TITLE
unable to submit a submission.csv file

### ISSUE THREAD

**Issue by randomgambit** [Kaggle/kaggle-api#400]
Hello there and thanks for this great package!

I am trying to submit a classic `submission.csv` file to the `jigsaw-toxic-severity-rating` competition. I created the file on colab (using the `kaggle.json` route) and everything works fine. See the `.head()` below:

<html>
<body>

comment_id | score
-- | --
114890 | 2
732895 | 2

</body>
</html>

However, when I try to submit the file, I get an error

```
mysub.to_csv('/content/submission.csv', index = False)
!kaggle competitions submit -c jigsaw-toxic-severity-rating -f /content/submission.csv -m "submission"
100% 86.4k/86.4k [00:01<00:00, 54.0kB/s]
400 - Bad Request
```

Is this a bug?
Thanks!

**Comment by Codin-Go** [comment]
same here

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
