### ISSUE TITLE
Not able to install API

### ISSUE THREAD

**Issue by gmmkmtgk** [Kaggle/kaggle-api#402]
![image](https://user-images.githubusercontent.com/51493190/148402239-3b1497ea-0d0c-48c8-a60e-c54917368327.png)
![image](https://user-images.githubusercontent.com/51493190/148402326-63f12ac6-7a37-4ee2-998c-6009995de515.png)
I am on Windows OS 
I tried pip install kaggle 
these warring are coming 
and when i wrote kaggle competitions download -c titanic

'kaggle' is not recognized as an internal or external command,
operable program or batch file.

comes
Please have a look i have attached the images 

Thanks & Regards

**Comment by jdelisi** [comment]
You need to add the Kaggle folder to your PATH in environment variables. Then it should recognize Kaggle in the terminal.
