### ISSUE TITLE
Kaggle Module not found Error

### ISSUE THREAD

**Issue by ishita199615** [Kaggle/kaggle-api#407]
![Screen Shot 2022-01-25 at 11 08 59 AM](https://user-images.githubusercontent.com/49127145/151024848-59191547-2f09-410a-85d5-7c75638f8970.png)

I have done pip install kaggle in the terminal, which got installed successfully. I did check the version of the kaggle which is 1.5.2.
The problem comes when I try to import the module to the python script to actually use it. 
It says the module is not found. Can someone please guide me if I am missing some steps? Thanks

**Comment by sakethramanujam** [comment]
as far as I know, kaggle is supposed to be used as a command line interface.
try using it as 
```
!kaggle
```

here's an example [https://colab.research.google.com/github/corrieann/kaggle/blob/master/kaggle_api_in_colab.ipynb](https://colab.research.google.com/github/corrieann/kaggle/blob/master/kaggle_api_in_colab.ipynb)
