### ISSUE TITLE
RFE: Ability to specify cloud storage location

### ISSUE THREAD

**Issue by Nick-Harvey** [Kaggle/kaggle-api#41]
It would be great if the kaggle api would allow for someone to download a dataset directly to a cloud storage provider. This way one could avoid the hassle of first downloading to a local machine and then uploading it to the CSP. 

What this could look like for someone using Google Cloud Storage
$kaggle datasets download -d <dataset_name> -p gs://<bucketname>/

**Comment by vsoch** [comment]
hey @Nick-Harvey is it way too slow to download locally then move to storage? If it might be the tool you are using (or you haven't found a good one) a nice one I've found that can work with a ton of cloud storage providers is [rclone](https://github.com/ncw/rclone). You could have a batch script to use the kaggle executable, and then rclone to move elsewhere.
