### ISSUE TITLE
Submit return 400 Bad Request

### ISSUE THREAD

**Issue by tudoanh** [Kaggle/kaggle-api#414]
I'm trying to submit from `kaggle` CLI tool, but on my Google Colab instance and my PC, the submission return only this text: `400 - Bad Request`

```
➜  Kaggle kaggle competitions submit contradictory-my-dear-watson -f ~/submission.csv -m 'first submit'
100%|████████████████| 66.0k/66.0k [00:04<00:00, 15.2kB/s]
400 - Bad Request
```

**Comment by Woodward-Z** [comment]
You need join this competition first.

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
