### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ucas010** [Kaggle/kaggle-api#418]
hi,dear 
I want to get the data from kaggle, but got error
So what's up ?
`kaggle competitions download -c home-credit-default-risk`

403 - Forbidden

**Comment by luke396** [comment]
I also encountered this problem, and I found out because I didn't join the competition. Maybe you have the same reason.

**Comment by ucas010** [comment]
@luke396 so how to join the competition?

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
