### ISSUE TITLE
400 - Bad Request during a submission

### ISSUE THREAD

**Issue by chamecall** [Kaggle/kaggle-api#419]
I keep getting the error trying to submit a default sample_submission file. 
The command is this:
`kaggle competitions submit -f /home/algernone/kaggle-data/US-Patent-phrase-to-phrase-matching/original/sample_submission.csv -m 'submission API test'`

**Comment by Codin-Go** [comment]
same here!

**Comment by Philmod** [comment]
You probably need to pass the competition URL suffix to the command.

I created a bug internally to improve this. http://b/288447126

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
