### ISSUE TITLE
Internal error when creating dataset

### ISSUE THREAD

**Issue by jfpuget** [Kaggle/kaggle-api#424]
I got this message when creating a dataset using the kaggle cli:

500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api

I tried to create the dataset again but get another error:

Dataset creation error: The requested title "NBME nbme_254" is already in use by a dataset. Please choose another title.

I therefore checked, and indeed, there is a dataset creating underway for hours at https://www.kaggle.com/datasets/cpmpml/nbme-254

This is annoying a sI cannot upload my competition winner model the way I used it.

**Comment by ItsPiyusha** [comment]
Did you resolve the issue?

**Comment by jfpuget** [comment]
who? me?  No. I am not involved in kaggle implementation at all.

**Comment by Philmod** [comment]
Hi! Is there any way to get a reproducible command/metadata?

**Comment by jfpuget** [comment]
Thanks for checking.

I gave a link, did you check it? Here it is again: https://www.kaggle.com/datasets/cpmpml/nbme-254

The dataset is still being created, more than one year later.
<img width="966" alt="kaggle_issue" src="https://github.com/Kaggle/kaggle-api/assets/10423052/61eb5770-357c-438a-877b-30159669eae4">


What else do you need?

**Comment by Philmod** [comment]
`Error during creation: The size of your files is 7044094860 bytes, it exceeds the maximum of 6066646832 bytes`, so my guess is that you were over quota.

I've improved the error message handling with the CLI. Feel free to retry / create a new dataset version.

**Comment by jfpuget** [comment]
This is not closed. The link points gto a page saying that teh dataset is being creeated, and I still can't create a new dataset with the same slug. I just tried with this json:

{
  "title": "nbme-254",
  "id": "cpmpml/nbme-254",
  "licenses": [
    {
      "name": "CC0-1.0"
    }
  ]
}

I am opening a new issue.


And I get this error:

Dataset creation error: Slug can only contain alphanumeric or "-" characters

**Comment by jijivski** [comment]
where did you get the error message Error during creation: The size of your files is 7044094860 bytes, it exceeds the maximum of 6066646832 bytes, please? I use the website to create but only know there is an internal error

**Comment by jfpuget** [comment]
As written at the start of the issue: "I got this message when creating a dataset using the kaggle cli"

If you have issues that are not due to using Kaggle cli then you should not use kaggle cli git to get support IMHO. Better ask in Kaggle forums.
