### ISSUE TITLE
Internal server error (500) when `sort-by` key is used in `kernels list`

### ISSUE THREAD

**Issue by avm19** [Kaggle/kaggle-api#436]
```
!kaggle kernels list --competition {competition} --page-size 100 -v -p 1
```
returns a list of kernels in CSV format as expected. However,
```
!kaggle kernels list --competition {competition} --page-size 100 -v -p 1 --sort-by "scoreDescending"
```
fails with message:

> 500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api

Kaggle API 1.5.12
Requests sent from within a Kaggle notebook.

**Comment by Philmod** [comment]
Internal bug: http://b/288447120

**Comment by Philmod** [comment]
I wasn't able to reproduce this bug.

![Screenshot 2023-06-26 at 11 59 50](https://github.com/Kaggle/kaggle-api/assets/818310/b56fabab-3b05-4b4b-a7bf-a779a2c40166)
