### ISSUE TITLE
Joining competitions after the due date will leave you out of the leaderboard even if the competition gets opened again.

### ISSUE THREAD

**Issue by BoranoL** [Kaggle/kaggle-api#445]
Three different people accepted the invitation to a competition after the due date. The competition opened for 2-3 more days after that and those people (with their submissions) could not enter the leaderboard. 
Since there is no option to leave competition and re-join, the only workaround was creating new accounts just to submit to that competition.

**Comment by jplotts** [comment]
Hi @BoranoL - this doesn't appear to be an issue with the Kaggle API?  Feedback about Kaggle's website or product can be posted on our [Product Feedback forum](https://www.kaggle.com/discussions/product-feedback).  Thanks!
