### ISSUE TITLE
I can't save or save version, always show committing... , which leads to constant data loss, and I can't submit

### ISSUE THREAD

**Issue by catqaq** [Kaggle/kaggle-api#453]
An error occurred while committing kernel: Unexpected token '<', "<!DOCTYPE "… is not valid JSON
After closed this info, click save again, nothing seems to happen, no success, no failure messages.
I can't save or save version, always show committing… , which leads to constant data loss, and I can't submit.
Any idea to save or commit my work? Is there any way to save the notebook like git?
discussions in kaggle: https://www.kaggle.com/discussions/questions-and-answers/370792

**Comment by Philmod** [comment]
Is this problem when using the API/CLI?

**Comment by jplotts** [comment]
I think this is not related to the API, so closing this issue.  If it's related to the API, please re-open with more details (e.g. - command run).  If it's related to Kaggle's website, please post on the [Product Feedback forum](https://www.kaggle.com/discussions/product-feedback).
