### ISSUE TITLE
Potentially unreachable code?

### ISSUE THREAD

**Issue by PetterPet01** [Kaggle/kaggle-api#457]
[Here is the code](https://github.com/Kaggle/kaggle-api/blob/49057db362903d158b1e71a43d888b981dd27159/kaggle/api/kaggle_api_extended.py#L1416l)

From line 1416 to 1421, at line 1420 the code checks if "result" is None *after* referencing its property "invalidTags". Shouldn't the null-checking code be before any references to the object?

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
