### ISSUE TITLE
can't download and submit by command, Unauthorized

### ISSUE THREAD

**Issue by benwu232** [Kaggle/kaggle-api#46]
I can't download the data by the command kaggle competitions download -c home-credit-default-risk and got response: Reason: Unauthorized HTTP response headers: HTTPHeaderDict({'Cache-Control': 'private', 'Content-Length': '37', 'Content-Type': 'application/json; charset=utf-8', 'X-MiniProfiler-Ids': '["df7e1723-609f-411b-9206-a4b4884a69f2","8c684700-d1ec-42b0-b3ed-ce20e7fae1cc","21458e01-a86c-4cc8-a3bb-f3eb49654050","4f5d4b4e-e5b9-4675-b7fc-c454b45ce920","15932af9-5c4e-481a-9f2d-8728ef33a638","fc6e4e82-1db3-4f37-a489-e37081704d3b"]', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Set-Cookie': 'ARRAffinity=ee4e320a1b9a3f9ccb209beb6fd7d86959c3f19b5b6bc8390a940f08b337259b;Path=/;HttpOnly;Domain=www.kaggle.com', 'Date': 'Tue, 22 May 2018 02:15:10 GMT'}) HTTP response body: {"code":401,"message":"Unauthorized"}

I tried to download them one by one and it is ok. Then I tried to submit the sample_submission.csv and failed. The response it almost the same: Reason: Unauthorized HTTP response headers: HTTPHeaderDict({'Cache-Control': 'private', 'Content-Length': '37', 'Content-Type': 'application/json; charset=utf-8', 'X-MiniProfiler-Ids': '["48f823d1-beec-4f6a-939d-f173f55e274b","87004b00-a1e5-4265-bfdb-6e91ebe19fe1","26c281c7-820d-4bed-b2a6-a08e8d8dd9c6","ed258e92-77b5-41d9-be91-695ee07b453e","366c5546-49df-4dee-b2dd-455a1e555a5f","e7d26c20-eb47-4863-a882-ea10d869e91a"]', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Set-Cookie': 'ARRAffinity=ce81b1c7a6ee0d37e371380bea90489866bf717e5545123bd3aaf09941faac86;Path=/;HttpOnly;Domain=www.kaggle.com', 'Date': 'Tue, 22 May 2018 02:28:58 GMT'}) HTTP response body: {"code":401,"message":"Unauthorized"}

It is a fairly new competition. I've enrolled and accepted the rules. Not sure what's wrong?

**Comment by rysteboe** [comment]
Do you have the `kaggle.json` token located in `~/.kaggle`?

**Comment by benwu232** [comment]
yes. Actually it was ok in last competition, the talking data...

**Comment by benwu232** [comment]
@rysteboe 
the version is 1.3.6.
Maybe the problem is not in kaggle-api. I tried submit the sample-submission file of home-credit-default-risk in the webpage but failed. Do you know where can I find somebody to help? Thanks!

**Comment by rysteboe** [comment]
I would create a ticket here - https://www.kaggle.com/contact.  Hopefully they can sort it out for you.  I'm going to close this issue out, but feel free to ping it or open a new one if needed.

**Comment by benwu232** [comment]
Thanks a lot!

**Comment by benwu232** [comment]
I tried another competition, but still got the same problem. Then I tried to create a new token and everything goes well again. For guys, who meet this, you can try this!

**Comment by RajeshThevar** [comment]
If any coming across this issue, recreate API token, replace it and ensure access again through chmod. 
It will work.

**Comment by rysteboe** [comment]
@TomSala what do you mean by uploaded a new token?  Please bear in mind that you can only have one active API token at a time.  Creating a new one will automatically expire any existing ones.

**Comment by fjdiod** [comment]
Hello, have the same problem. I've put json to ~/.kaggle/kaggle.json, when using api:
``` shell
$ kaggle competitions download -c human-protein-atlas-image-classification
Warning: Your Kaggle API key is readable by otherusers on this system! To fix this, you can run'chmod 600 /home/fjdiod/.kaggle/kaggle.json'
401 - Unauthorized
```
And after chmod ~/.kaggle/kaggle.json it outputs:
```shell
$ kaggle competitions download -c human-protein-atlas-image-classification
401 - Unauthorized
```
Also, I've tried to create and use a new token with the same results.
Version: Kaggle API 1.4.7.1

**Comment by hugeme** [comment]
Same here:

`$ kaggle competitions download -c human-protein-atlas-image-classification
Warning: Your Kaggle API key is readable by otherusers on this system! To fix this, you can run'chmod 600 /home/fjdiod/.kaggle/kaggle.json'`
`401 - Unauthorized `

And after chmod ~/.kaggle/kaggle.json it outputs:

`$ kaggle competitions download -c human-protein-atlas-image-classification`
`401 - Unauthorized `

`
~/me/here (master) $ pip show kaggle`
`Name: kaggle`
`Version: 1.4.7.1`
`Summary: Kaggle API`
`Home-page: https://github.com/Kaggle/kaggle-api`
`Author: Kaggle`
`Author-email: support@kaggle.com`
`License: Apache 2.0`
`Location: /usr/local/lib/python3.7/site-packages`
`Requires: six, python-slugify, urllib3, certifi, tqdm, requests, python-dateutil`
`Required-by:`

@fjdiod did you manage to solve the issue?

**Comment by rysteboe** [comment]
Have you two accepted the rules of the competition?  The error message is not clear right now in cases where the rules have not been accepted.

**Comment by fjdiod** [comment]
Hello @rysteboe, I've accepted the rules, I could manually download all these data.
@hugeme I ended up just importing cookies from my browser and using wget.

**Comment by shubchat** [comment]
Any headway on this I am also stuck with this problem

**Comment by faizanf47** [comment]
I was getting the same issue.
0. You should install kaggle at user's using 'pip install -U kaggle'
1. Go to My Account on Kaggle.
2. Expire All Tokens.
3.Create a new Token.
4. Create a directory known as '.kaggle'(Note: There is a dot) at [USER]@[MACHINE]:~/
5. Move the file named 'kaggle.json' you just downloaded to that directory.
6. Type chmod 600 /home/[USER]/.kaggle/kaggle.json
7. Type export KAGGLE_USERNAME=[Your Username]
             export KAGGLE_KEY=xxxxxxxxxxxxxx

Hope it helps.

**Comment by shubchat** [comment]
Thanks yeah looked like the problem was with the Json file .

**Comment by devanshuDesai** [comment]
Have the same issue. Tried all steps listed by @faizanf47 , still get the same 401 Authorization Error

**Comment by shubchat** [comment]
Did you get a new json file.That worked for me

**Comment by devanshuDesai** [comment]
@shubchat I did. It didn't resolve the issue for me.

**Comment by hugeme** [comment]
I did absolutely nothing, but now, after some some weeks it is working somehow

**Comment by FMCalisto** [comment]
It did not solve my issue, either. Need some help. Thank you for the support.

**Comment by nirmalsinghania2008** [comment]
For me, the error was caused because new` kaggle.json` was getting renamed to `kaggle (1).json `. and when I copied `kaggle.json` to` ./kaggle`, it was copying the old token which was expired by generating the new one.

Try removing the old token before uploading the new one or explicitly copy the new one.

Hope this helps!

**Comment by adaaaaaa** [comment]
what is the KAGGLE_KEY?
i first got 'ValueError: Error: Missing username in configuration.'
then i type '    7\. export KAGGLE_USERNAME=[Your Username]' and the first error solve...
but then i got 'ValueError: Error: Missing key in configuration.'
how to fix it ?

**Comment by adaaaaaa** [comment]
@faizanf47 if the original kaggle.json file miss...how to find the KAGGLE_KEY?
there is nothing like "key" or "KAGGLE_KEY" in the new download kaggle.json file...

**Comment by SoufianeDataFan** [comment]
@faizanf47 suggestions solved this problem for me. Expire all the token and create a new ~/.kaggle.json and this error will go away

**Comment by rebelosa** [comment]
Also ` sudo kaggle competitions list` worked for me.

**Comment by hrivu21** [comment]
I was facing the same problem...here is the solution that worked for me.

In the ~/.kaggle directory, delete all the previous existing .json files and retry.

**Comment by jorijnsmit** [comment]
I was using credentials from an outdated `.json` file.

**Comment by larroy** [comment]
Doesn't seem to work from fish shell, but works from bash shell. I have both environment variables and credentials in the json file.

**Comment by haofanwang** [comment]
Works for me.

**Comment by mremreozan** [comment]
you have to write "sudo" in  the begining of command.

**Comment by 18iteration** [comment]
> ### [<img alt="@mremreozan" width="20" height="20" src="https://avatars.githubusercontent.com/u/54943673?s=60&amp;u=7323c16e15ea3963e26be0e16670107f58904b27&amp;v=4">](/mremreozan) ** [mremreozan](/mremreozan)**

This worked after trying every thing (your reply led to it):

(Used Debian WSL)
1. Remove kaggle with pip (or pip3) uninstall kaggle.
2. Install with sudo pip (or pip3) install -U kaggle
3. Go to Kaggle Account and Generate a new token. Copy / sudo mv the new downloaded kaggle.json file to /root/.kaggle/
4. sudo kaggle whatever you want to do (download in my case) and it works

**Comment by blazespinnaker** [comment]
I created a new notebook and that fixed it.  Perhaps Kaggle API is caching something on the docker?

**Comment by blazespinnaker** [comment]
Ran into this issue on Kaggle cloud.  Had to create a new notebook.

note that I execute:

!chmod 600 /root/.kaggle/kaggle.json
!cat /root/.kaggle/kaggle.json 

And verified that the file outputted is the same on the broken and working docker before executing the kaggle command.

My guess is possibly that kaggle api is caching something somewhere.  Of course, I've been wrong before.
