### ISSUE TITLE
Kernel metadata created by `kernels pull -m` command contain wrong items in `kernel_sources` field

### ISSUE THREAD

**Issue by svendaj** [Kaggle/kaggle-api#464]
When using `kaggle kernels pull -m username/kernel-slug` CLI command to generate metadata of existing notebook which is using other notebooks or datasets as input, it creates `kernel-metadata.json` with `kernel_sources` list items containing prerfix `"code/"`. If datasets are used as input, then its `dataset_sources` list items are prefixed by `"dataset/"` string. [Kernel Metadata Wiki](https://github.com/Kaggle/kaggle-api/wiki/Kernel-Metadata) is specifying content of these without these prefixes as only `"username/kernel-slug"` or `"username/dataset-slug"` respectively. 

If such `kernel-metadata.json` is pushed back for execution with `kaggle kernels push` command, its execution will fail because it will not find prefixed input notebooks or datasets.

Here is an example of such `kernel-metadata.json` file with invalid `kernel_sources` field:
```
{
  "id": "svendaj/jos-lb-lazy",
  "id_no": 34349505,
  "title": "JOS_LB_LAZY",
  "code_file": "jos-lb-lazy.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": true,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [
    "code/svendaj/numerai-data",
    "code/svendaj/jos-lb-lazy"
  ],
  "competition_sources": []
}
```
I have not tested `competition_sources` field, but my guess is that it will have the same issue. Prefixing it with `"competition/"` maybe?

**Comment by svendaj** [comment]
Today I have also mentioned the unexpected behavior of `"enable_internet"` field. Although my pulled Kaggle notebook is internet enabled, metadata json was created with `"enable_internet": false` setting. Last week it worked correctly.

**Comment by Philmod** [comment]
Internal bug: http://b/288415155

**Comment by Philmod** [comment]
Thanks for the report, a fix has now been deploy:

![Screenshot 2023-06-27 at 13 41 12](https://github.com/Kaggle/kaggle-api/assets/818310/5f07bd57-dde2-4abc-8ebb-1237417454e9)

I couldn't reproduce your `enable_internet` bug though.

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
