### ISSUE TITLE
error when creating dataset 

### ISSUE THREAD

**Issue by jfpuget** [Kaggle/kaggle-api#485]
This is a follow up on https://github.com/Kaggle/kaggle-api/issues/424

I had an issue when creating a dataset more than a year ago. The dataset is still being shown as being created at https://www.kaggle.com/datasets/cpmpml/nbme-254

I needed to create a dataset with that path in order to deliver my sinner solution at the time.

I just tried to create a dataset with same path, using this json:

{
  "title": "nbme-254",
  "id": "cpmpml/nbme-254",
  "licenses": [
    {
      "name": "CC0-1.0"
    }
  ]
}

I get this error:

Dataset creation error: Slug can only contain alphanumeric or "-" characters

The original sisue is not soved: I still can't create a ataset with the path I need.

**Comment by Philmod** [comment]
Hi!

I tried to reproduce this bug: 

```dataset-metadata.json
{
  "title": "nbme-254",
  "id": "philmod/nbme-254",
  "licenses": [
    {
      "name": "CC0-1.0"
    }
  ]
}
```

```
$ kaggle datasets create -p ...
[...]
Upload successful: ...
Your private Dataset is being created. Please check progress at https://www.kaggle.com/datasets/philmod/nbme-254
```

**Comment by jfpuget** [comment]
What you just found out is that philmod/nbme-254 is not the same as cpmpml/nbme-254.

I reported twice an issue: the dataset cpmpml/nbme-254 is being crated forever, which precludes using its name for an actual dataset.

**Comment by Philmod** [comment]
Gotcha, what you really want is for us to delete the existing `cpmpml/nbme-254` dataset?

**Comment by jfpuget** [comment]
Yes, but there is a bug that led to this zombie dataset. 

I no longer need the name, but I reported the fact that the dataset creation hangs.

**Comment by Philmod** [comment]
Understood. I'm sorry we didn't treat this problem earlier.

Do you have a way to reproduce this kind of zombie dataset?

**Comment by jfpuget** [comment]
I used the cli with the json I shared. You said in the previous issue I opened that there was an error because of space quota. Maybe the error handling did not went well at the time?

**Comment by Philmod** [comment]
I deleted the dataset `cpmpml/nbme-254`, you should be able to re-create it.

**Comment by jfpuget** [comment]
Thanks!
