### ISSUE TITLE
Bug when doing kaggle datasets download

### ISSUE THREAD

**Issue by HaowenGuan** [Kaggle/kaggle-api#489]
System:
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
python_version=3.11.4

I installed api kaggle==1.5.15
When I run `kaggle datasets download Cornell-University/arxiv`
I got a wired error:
```
(HG_kaggle) [sbcaesar@dais10 ~]$ kaggle datasets download Cornell-University/arxiv
time data 'Sat, 08 Jul 2023 23:58:54 GMT' does not match format '%a, %d %b %Y %X %Z'
```

I revert the version of kaggle back to kaggle==1.5.13
the download works.

**Comment by Philmod** [comment]
Internal bug: http://b/291578234

**Comment by Philmod** [comment]
It should be fixed in https://github.com/Kaggle/kaggle-api/releases/tag/1.5.16. Let me know if that works for you now.
