### ISSUE TITLE
Kaggle API-Anaconda error

### ISSUE THREAD

**Issue by Suncinar** [Kaggle/kaggle-api#495]
I am trying to install Kaggle to Anaconda and I gets following error message. I am pretty new using Kaggle and Anaconda. Could you please help me out with the following command? 

usage: kaggle [-h] [-v] {competitions,c,datasets,d,kernels,k,models,m,files,f,config} ...
kaggle: error: the following arguments are required: command.

**Comment by OMatheusWander** [comment]
Why u don't use kaggle notebooks?

**Comment by jplotts** [comment]
Hi @Suncinar - this error means that you need to tell the API what you want it to do.  It looks like your set up is working fine, so I'm going to close this issue.
