### ISSUE TITLE
Style guide?

### ISSUE THREAD

**Issue by delirious-lettuce** [Kaggle/kaggle-api#5]
This looks like a neat project but I am curious about the style of the code itself and since the project only seems to be four days old, this might be a good time to make changes.

For example:
https://github.com/Kaggle/kaggle-api/blob/4625bc72cb942d9022928b2a4444fee769aef013/kaggle/api/kaggle_api_extended.py#L54

* Python projects usually use four space indentation but this method alone has three different indentations (4 space then 2 space then 3 space).
    > [Use 4 spaces per indentation level.](http://pep8.org/#indentation)
* There are also spaces around the `=` operators whereas PEP8 recommends no spaces.
    > [Don’t use spaces around the = sign when used to indicate a keyword argument or a default parameter value.](http://pep8.org/#other-recommendations)
* The function name also uses `camelCase` instead of the more common `snake_case` convention.
    > [Function names should be lowercase, with words separated by underscores as necessary to improve readability.](http://pep8.org/#function-names)

Many projects seem to stay pretty close to PEP8 except maybe loosening the line length recommendation from 79 chars to around 100 chars.
* http://pep8.org/#maximum-line-length

These are small things but fixing them would touch many lines of code in the project and I wasn't sure if that would be frowned upon. Any thoughts?

**Comment by pulkitmaloo** [comment]
Can I work on making the code PEP8 Style?

**Comment by rysteboe** [comment]
Apologies for the late response.  I'm picking up this project now.  

Conforming the handwritten code to Google's python style is on my short-term todo list.  At least one version will not contain breaking changes, but I don't want to leave in the old method names too long.

**Comment by rysteboe** [comment]
Wound up just including the breaking changes.  Please see the changelog - they shouldn't affect command line only use.  

The code was formatted per Google style, which has a lot of similarities to pep8, but is not identical.
