### ISSUE TITLE
About download model from huggingface to /kaggle/input

### ISSUE THREAD

**Issue by Hanochhu** [Kaggle/kaggle-api#507]
I want to use model from huggingface but the competition ban internet.

 I have tried to save model in /kaggle/working but it's failed to submit and /kaggle/input it's read-only folder, the only way I thought it's to **download in my mac and upload to /input**. 

I wonder if there is a **better** way to make it.

**Comment by jplotts** [comment]
Hi @Hanochhu - this repo is for the Kaggle API specifically, but it sounds like you're having trouble with Kaggle (website).  You're likely to get a better response by posting on the forum of the competition you're competing in, where other members of the Kaggle community may see it and offer suggestions.
