### ISSUE TITLE
sys.exit on kaggle.json is bad

### ISSUE THREAD

**Issue by exp0nge** [Kaggle/kaggle-api#51]
Hard exiting when the kaggle.json file doesn't exist is just bad. We only need the file during submit.

An **error** should be **raised** during submit not import/initialization! 

I can submit a PR if that helps?

**Comment by rysteboe** [comment]
PR's are always welcome.  I do plan to improve error handling soon.

**Comment by rysteboe** [comment]
`ValueError`s are now raised instead as of 1.4.0.
