### ISSUE TITLE
Command not found and unable to uninstall.

### ISSUE THREAD

**Issue by nasgold** [Kaggle/kaggle-api#53]
Hello - I tried downloading the api via pip using `pip install --user kaggle`.

This didn't work for me due to permissioning but this with `sudo -H` appeared successful.

However, I get the command not found message when attempting to use `kaggle` on the command line even after adding `/var/root/Library/Python/2.7/bin` to my path (which is where my attempt at installation with the `sudo -H` included told me to look).

When I try to uninstall using `pip uninstall kaggle` pip doesn't believe kaggle is installed, and `whereis kaggle` along with `pip show kaggle` don't fail but also don't output anything.

Any help in getting this fixed and installed correctly would be appreciated. Thanks.

**Comment by exp0nge** [comment]
Are you sure `pip` was pointing to the same environment every time?

**Comment by nasgold** [comment]
Thanks for replying. And I believe so - just doing everything in my home directory and not using any virtual environments.

**Comment by rysteboe** [comment]
Is it installed to `~/.local/bin`?  That's where it lands when I do an install with `sudo -H`.  (This is on Ubuntu.)

**Comment by nasgold** [comment]
No problem, thanks for responding! I should have mentioned I am on High Sierra.

It appears to be installed at `var/root/Library/Python/2.7/lib/python/site-packages`.

I seem to be able to get it working as long as I run `sudo -i` before using the tool. Assume that's a result of installing using `sudo -H`. Not ideal but will allow me to move forward for now.

**Comment by rysteboe** [comment]
All right.  Going to close this out.  Glad you found a solution even though I agree it's not ideal.  If more people run into this, then I'll look into why it's acting oddly.
