### ISSUE TITLE
submission error

### ISSUE THREAD

**Issue by codejay12** [Kaggle/kaggle-api#530]
iam trying submission through api and found the 403 error says"**403 - Forbidden - Permission 'competitions.participate'** was denied" and the command is `kaggle competitions submit playground-series-s3e2626 -f .\sample_submission.csv -m "submission through api`

**Comment by jplotts** [comment]
Hi @codejay12 - it seems like you have a typo in your competition name.  It should be "playground-series-s3e26" not "playground-series-s3e2626".  We will look into providing a better error message, but hopefully this should help in the meantime.
