### ISSUE TITLE
Question not really a bug

### ISSUE THREAD

**Issue by wkaisertexas** [Kaggle/kaggle-api#531]
I am trying to download the output for a notebook run directly (directly accessing image files).

GitHub allows you to use raw.githubusercontent.com access files in this way.

What is the Kaggle equivalent to this?

**Comment by wkaisertexas** [comment]
There is a way to do it in the swagger spec I just get a 401

**Comment by jplotts** [comment]
Hi @wkaisertexas - it seems like you're looking for `kaggle kernels output <user>/<slug>`?  401 is unauthorized, so it might be a problem with your key rather than a problem with the specific API you're calling.

**Comment by wkaisertexas** [comment]
The key I am using is the one that I got from the Kaggle cli and is valid as I am able to do somewhat critical things like manage / delete data sources.

If there is a way to get different permissions on a key, I did not know of one.

**Comment by jplotts** [comment]
@wkaisertexas - I'm not sure how I can help you.  I responded to your initial query (how to get outputs) with a specific command.  You didn't say how you're getting a 401, so I can only give you the generic information that 401 means unauthorized.  If you'd like help with your 401 error, you need to provide repro steps.
