### ISSUE TITLE
BadZipFile Error using opendatasets

### ISSUE THREAD

**Issue by Bagelsause** [Kaggle/kaggle-api#533]
I was trying to download the files in the YouTube Trending Video Dataset by Rishav Sharma and was using the opendatasets Python import, and I received a BadZipFile warning for the following code:

od.download("https://www.kaggle.com/datasets/rsrishav/youtube-trending-video-dataset?select=US_youtube_trending_data.csv", force=True)
od.download("https://www.kaggle.com/datasets/rsrishav/youtube-trending-video-dataset?select=US_category_id.json", force=True)

And as instructed in the error, "('Bad zip file, please report on www.github.com/kaggle/kaggle-api', BadZipFile('File is not a zip file'))", I'm reporting it as an issue. I have the kaggle.json present in the directory, so it doesn't ask for any input in the code box.

Please let me know if I should submit any other information regarding this issue!

**Comment by Philmod** [comment]
Thanks for reporting, I have a fix for this bug that will go out today with the version `1.6.1`.
