### ISSUE TITLE
BadZipFile('File is not a zip file')

### ISSUE THREAD

**Issue by nadialvy** [Kaggle/kaggle-api#536]
I try to `kaggle datasets download muhammadbinimran/housing-price-prediction-data --unzip`
but this is the response i got
Downloading housing-price-prediction-data.zip to /home/nadia/nadia/Projects/Machine Learning/kaggle/homeprediction
  0%|                                                                                              | 0.00/763k [00:00<?, ?B/s]
  0%|                                                                                              | 0.00/763k [00:00<?, ?B/s]
('Bad zip file, please report on www.github.com/kaggle/kaggle-api', BadZipFile('File is not a zip file'))

also if i dont include --unzip keyword, it succeed to download the datasets, but it cannot be unzipped manually. Im using linux btw

**Comment by nadialvy** [comment]
I alsoo tried to unzip the downloaded file using unzip online but the result is same, it says that the file is error. Pls fixed this :)

**Comment by Philmod** [comment]
Thanks for reporting, I have a fix for this bug that will go out today with the version `1.6.1`.
