### ISSUE TITLE
404 - Can't pull my kernels without versions

### ISSUE THREAD

**Issue by oxmwh** [Kaggle/kaggle-api#538]
How to reproduce:
`kaggle --version -> Kaggle API 1.6.2`
`kaggle kernels list -m` works correctly (shows both private and public kernels)
but `kaggle kernels pull` or `kaggle kernels status` on my private kernels gives:
`404 - Not Found - Not found`
They work fine on my public kernels though.
Same 404 results using python like so:

```python
import os
from kaggle.api.kaggle_api_extended import KaggleApi

os.environ['KAGGLE_CONFIG_DIR'] = "/home/<Linux-username>/.kaggle/"
api = KaggleApi()
api.authenticate()
api.kernels_pull('username/kernel-slug')
```

**Comment by jplotts** [comment]
Hi @oxmwh - I'm not reproducing the bug with `kaggle kernels pull <private>`; it works for me.  Similarly, I think you have a slight bug in your code, as `kernels_pull` requires an output path
```
api.kernels_pull('username/kernel-slug', 'output-dir')
```

With the output path, I'm able to download my private kernels.

**Comment by oxmwh** [comment]
Thank you so much @jplotts for your response.

I have created a [notebook](https://www.kaggle.com/code/jdjdjhk/bug-404) to reproduce the bug inside Kaggle itself.

Here is also a screenshot of the bug:
![404](https://github.com/Kaggle/kaggle-api/assets/139810090/62662548-662b-43a2-98fe-007b746b8743)

**Comment by jplotts** [comment]
Hi @oxmwh - I see the problem now.  It's not that the notebooks are private, it's that they have no versions.  Permanent versions are created when a notebook is pushed via the API, or they can be created in the Notebook Editor UI via the "Save Version" button.  I'll reopen this issue and file a bug internally to handle this case better.  As a workaround in the meantime, creating a version of your notebook should enable you to pull it via the API.

**Comment by oxmwh** [comment]
OMG you're totally right! You're an angel from above!

**Comment by stevemessick** [comment]
Looks like @lucyhe fixed this one. I created another (internal) issue for push failing to create the first version and session of a kernel. (You need both version and session to exist to push a kernel.)
