### ISSUE TITLE
Online Dataset Upload

### ISSUE THREAD

**Issue by vsoch** [Kaggle/kaggle-api#54]
Hi Kaggle!

The Kaggle API upload seemed to return a successful response, but 4 hours later I'm still getting a 404 on the page. I submit a help/suppor ticket, and decided to try creating the dataset manually (I did this before and it magically showed up). I ran into another (web UI issue) that I wanted to report here because I needed to share screen shots, and I hope it's ok I'm using an issue board for this (please forward to the team that would want to see!). The issue is that when I am uploading a dataset, I am encouraged (and would want) to give a description. For example:

![saving](https://user-images.githubusercontent.com/814322/41577910-539e03b4-7344-11e8-9e6e-327bc2664d72.png)

Notice that I have entered a small descriptor. Next, I would click save. The problem is that it doesn't seem to actually save:

![doesnt-save](https://user-images.githubusercontent.com/814322/41577923-646b283e-7344-11e8-9615-f797e63b26ee.png)

It could be that it gets recorded somewhere and not represented / shown in the interface, but likely not. Here is the console output if it helps, but note that the second error only happens *after* the upload finishes.

![image](https://user-images.githubusercontent.com/814322/41577948-9a47a31a-7344-11e8-84d3-d61cf61ce749.png)

Thanks for the help! I hope that my dataset appears soon :)

**Comment by rysteboe** [comment]
I've forwarded the web UI part of this along to the rest of the eng team, who will take a look.

With regards to the dataset uploads, I'm going to just copy paste my response on your PR for tracking purposes.

I have an outstanding issue right now to clarify the message printed to make it clear that the creation takes time beyond the upload. I won't be able to get to that until next week though (vacation, woohoo!), but feel free to file a second PR if you like to that effect.

Status is also something that I want to get to in the next few weeks, but will require me creating the server side endpoint.

**Comment by vsoch** [comment]
Thank you!

And great to hear about status! I intuited that some server endpoint work would be needed (and I can't do this!) but let me know if I can help with something else. Minimally I can offer to test out future stuffs.

**Comment by vsoch** [comment]
A quick update on the bug - creating the dataset in the web interface actually created a second (with the same URL) and I can't access the one that has the complete data (likely this is the one that had the upload work).

![image](https://user-images.githubusercontent.com/814322/41614953-c8b01560-73ae-11e8-962c-1b5bbf05b586.png)

I'm going to try deleting the one I created in the interface to see if it opens up access to the second.

**Comment by timoboz** [comment]
Hi Vanessa,

I'm taking care of the web side of things for datasets, looks like there were a bunch of different issues here:

- Javascript errors in the uploader: We actually released a completely new uploader today (alongside full preview functionality - yay see here https://www.kaggle.com/product-feedback/59413), most likely these  should be gone now. In any case, they are not critical to the dataset upload itself, so ok to ignore.
- No web page for datasets in progress: We know the experience is currently somewhat broken. To give you a bit more info: Each dataset has a last current "successful" version. For existing datasets, this stays at the last version until the processing of the next version has completed, in case something breaks with that next version. For new datasets, this basically means this is NULL and without any version, we can't really show a dataset page. For Web users, this is solved with the progress bar on the uploader, but API users don't really have anything to see the progress. Maybe we need an API function to pull the version status or so. Will talk to @rysteboe about potentially exposing that.
- Duplicate datasets: We discovered an issue yesterday that allowed users to create the same dataset with the same name twice, mostly related to my point above. We took care of those duplicates now, so in your list you should see only one now.
- (A bit unrelated) I saw that on your dockerfiles dataset (https://www.kaggle.com/stanfordcompute/dockerfiles), the preview is a bit messed up for the zip file. Without going into the details of why this doesn't work (it's the name), I took the liberty of renaming that file to make the preview work a little bit nicer. It's processing right now, hope that was ok.

Cheers,
Timo

**Comment by vsoch** [comment]
hey @timoboz thanks for the updates! I'm going to create and upload a dataset to give the new uploader a go, and then I'll close the issue if all is well! Oh, and I think the rename seems ok :)

**Comment by vsoch** [comment]
okay, I finished creating the [new dataset](https://vsoch.github.io/datasets/2018/singularity-hub/), and then running [this container](https://hub.docker.com/r/vanessa/kaggle/) (interactively) to upload, here is the output:

```bash
$ docker run -v /home/vanessa/.kaggle:/root/.kaggle -v $PWD:/tmp/data -it vanessa/kaggle bash
(base) root@1fbdfeddd7f9:/code# python create_dataset.py --username stanfordcompute --title "Singularity Container Guts" --name "singularity-guts" --files /tmp/data/v1.0.0.zip --keywords software,containers
Data package template written to: /tmp/tmprj05ozga/datapackage.json
Preparing upload folder...
{
 "title": "Singularity Container Guts",
 "id": "stanfordcompute/singularity-guts",
 "licenses": [
  {
   "name": "other"
  }
 ],
 "keywords": [
  "software",
  "containers"
 ],
 "resources": [
  {
   "path": "v1.0.0.zip",
   "description": "v1.0.0.zip, part of Singularity Container Guts Dataset, 6/2018, MIT License"
  }
 ]
}
Starting upload for file v1.0.0.zip
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 141M/141M [03:27<00:00, 713kB/s]
Upload successful: v1.0.0.zip (141MB)
The following URL will be available after processing (10-15 minutes)
https://www.kaggle.com/stanfordcompute/singularity-guts
```

It's already there! --> https://www.kaggle.com/stanfordcompute/singularity-guts
I'm going to close this issue, I think it's resolved as far as I can tell. I can reopen another issue if something different arises. Thanks again for the help! :)
