### ISSUE TITLE
[BUG] "Kernel push error: Notebook not found" - unable to push notebook

### ISSUE THREAD

**Issue by ARKAD97** [Kaggle/kaggle-api#545]
First, I pull my existing notebook:

```bash
kaggle kernels pull -p path/to/dir --metadata nickname/name
```

Then I do:
```bash
kaggle kernels push -p path/to/dir
```

And getting error:
```bash
Kernel push error: Notebook not found
```

both notebook and metadata are in place.
Tried to `cd` into directory and run `kaggle kernels push` - the result is the same.

kaggle version = 1.6.5
python version = 3.10
Linux ac746e85fdc9 5.4.0-163-generic #180-Ubuntu SMP Tue Sep 5 13:21:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Running in cloud on slightly modified official kaggle docker.

Thank you for your help

**Comment by ARKAD97** [comment]
Figured it out. You have to save your notebook in web interface before updating it.

Would be great if this info added to the documentation

**Comment by Yudis53732** [comment]
> First, I pull my existing notebook:
> 
> ```shell
> kaggle kernels pull -p path/to/dir --metadata nickname/name/
> ```
> 
> Then I do:
> 
> ```shell
> kaggle kernels push -p path/to/dir
> ```
> 
> And getting 
> 
> ```shell $1500
> Kernel push : Notebook not found
> ```
> 
> both notebook and metadata are in place. Tried to `cd` into directory and run `kaggle kernels push` - the result is the same.
> 
> kaggle version = 1.6.5 python version = 3.10 Linux ac746e85fdc9 5.4.0-163-generic #180-Ubuntu SMP Tue Sep 5 13:21:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> 
> Running in cloud on slightly modified official kaggle docker.
> 
>
