### ISSUE TITLE
Issue with code in Kaggle but unsure how to fix it

### ISSUE THREAD

**Issue by AlexisG1999** [Kaggle/kaggle-api#547]
So I was trying to run the code and I am getting an error message. From what directions I had it doesn't seem to have an error but I am not sure if I am missing something in the code.

import io #import Python's to library
ff = io.open('/kaggle/input/2016ws/2016WS.txt', 'r', errors='ignore') #open text version of Wiki article
doc = nlp(ff.read()) #read text file
ff.close() #close after reading

NameError                                 Traceback (most recent call last)
Cell In[8], line 3
      1 import io #import Python's to library
      2 ff = io.open('/kaggle/input/2016ws/2016WS.txt', 'r', errors='ignore') #open text version of Wiki article
----> 3 doc = nlp(ff.read()) #read text file
      4 ff.close() #close after reading

NameError: name 'nlp' is not defined

**Comment by Philmod** [comment]
Hi! Your code snippet doesn't even seem to be using the kaggle API.

**Comment by AlexisG1999** [comment]
> Hi! Your code snippet doesn't even seem to be using the kaggle API.

what is the kaggle API you're talking about?
