### ISSUE TITLE
Unable to download model files using kaggle API

### ISSUE THREAD

**Issue by pranavvp16** [Kaggle/kaggle-api#548]
I'm using kaggle API to download a private model from kaggle and setup my credentials of API in the `.kaggle` file also tried setting it up with env variables, still downloading of model fail with error 403

`You don't have permission to access resource at URL: https://www.kaggle.com/api/v1/models/username/model_name/framework/variant/1/download/config.json
Please make sure you are authenticated if you are trying to access a private resource or a resource requiring consent.`

**Comment by m-umairali** [comment]
Still looking for this solution

**Comment by pranavvp16** [comment]
@m-umairali I also tried importing the model in kaggle notebook while signed in to kaggle account, but still getting the same error. Maybe you can try doing this, it didn't work for me :)

**Comment by jplotts** [comment]
Hi @pranavvp16 - I'm not able to reproduce this.  I can try again if you share the command that you're using.  One thing to note is that 403 can in some cases also mean "not found" rather than an actual permissions error.  This is done by many APIs to remove the ability of malicious actors to probe the namespace.

**Comment by pranavvp16** [comment]
`POST failed with: {"errors":["Permission \u0027models.get\u0027 was denied"],"error":{"code":7,"details":[]},"wasSuccessful":false}` I'm getting this error in kaggle notebooks event though I had added the model in data sources of the notebook through kaggle UI @jplotts

**Comment by jplotts** [comment]
@pranavvp16 - where are you seeing that error?  It looks like it's from the Kaggle Web UI, not the API.  Detailed repro steps would be useful here like:
* Where are you running?  Locally?  Kaggle notebook editor?
* What specific commands are you running?  Or if in the notebook editor, what actions are you taking?

Note that just attaching the notebook in the editor doesn't mean you can use the API from the editor to access it.

**Comment by pranavvp16** [comment]
Its solved the issue was with the path of download. While creating the model I named it in the name of variant but later renamed it back to model name. But the download URL expected the older name of model which was the variant name. So I created a new model with proper paths and variant .

**Comment by rohitblpprajapat** [comment]
I also facing this issue when I'm exporting kaggle notebook to colab notebook and try to run it there. Can anyone help?
