### ISSUE TITLE
Feature Request: Warning suppression option

### ISSUE THREAD

**Issue by billziss-gh** [Kaggle/kaggle-api#554]
After a fresh `pip install kaggle` I get the following warning, when I try to use the `kaggle` client.

```
$ kaggle k list -m --csv
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.7 / client 1.6.6)
ref,title,author,lastRunTime,totalVotes
...
```

Your documentation seems to suggest that the CLI is the recommended "API" for programmatically interfacing with Kaggle. Such warnings are detrimental to this use, because any tool that uses the `kaggle` CLI has to be aware of warnings and has to parse them out.

Please provide an option to disable warnings from `kaggle`.

**Comment by jplotts** [comment]
Thanks for your feedback!  I've filed a bug in our internal tracking system for this request - http://b/327367674
