### ISSUE TITLE
403 - Forbidden - Permission 'competitions.participate' was denied

### ISSUE THREAD

**Issue by skrydg** [Kaggle/kaggle-api#555]
```
kaggle competitions download https://www.kaggle.com/competitions/home-credit-credit-risk-model-stability
403 - Forbidden - Permission 'competitions.participate' was denied
```

```
kaggle --version
Kaggle API 1.6.6
```

```
kaggle competitions list | grep "home"
https://www.kaggle.com/competitions/home-credit-credit-risk-model-stability      2024-05-27 23:59:00  Featured          $105,000        453            True
```

I have register on this competition.
I notice strange warning while doing list request
`Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.7 / client 1.6.6)`,
but there's no 1.6.7 client:
```
pip3 install kaggle==1.6.7
Looking in indexes: https://pypi.ordercapital.com/simple, https://pypi.org/simple
ERROR: Ignored the following yanked versions: 1.5.7
ERROR: Could not find a version that satisfies the requirement kaggle==1.6.7 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.2.1, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.9.1, 1.3.10, 1.3.11, 1.3.11.1, 1.3.12, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.7.1, 1.5.0, 1.5.1, 1.5.1.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.8, 1.5.9, 1.5.10, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.6.0a0, 1.6.0a2, 1.6.0a3, 1.6.0a4, 1.6.0a5, 1.6.0a6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6)
ERROR: No matching distribution found for kaggle==1.6.7
```

What am i doing wrong?

**Comment by dineiar** [comment]
I am facing this same error on the website when trying to join the competition https://www.kaggle.com/c/twitter-bot-classification/data

This is also discussed on #87.

**Comment by saikiran816** [comment]
> I am facing this same error on the website when trying to join the competition https://www.kaggle.com/c/twitter-bot-classification/data
> 
> This is also discussed on #87.

The kaggle competition you want to join is "Invitation Only". You can only join if the host invites you to the competition.

**Comment by grelade** [comment]
Maybe someone will find it useful.
 I had the same issue with ''403 - Forbidden - Permission 'competitions.participate' was denied" but I found that it was because I used an url instead of the name:
```
kaggle competitions submissions https://www.kaggle.com/competitions/home-credit-credit-risk-model-stability
403 - Forbidden - Permission 'competitions.participate' was denied
```

but it works just with the name of the competition:

```
kaggle competitions submissions home-credit-credit-risk-model-stability
No submissions found
```
