### ISSUE TITLE
Broken packaging in latest version

### ISSUE THREAD

**Issue by philkuz** [Kaggle/kaggle-api#567]
Hi there,

The current packaging scheme is broken and creates a `src` package when you pip install the latest version of kaggle (1.6.11). 

This broke the LSP of the repo at my job because we use the `src` package to contain our code. This wasn't a problem in previous versions of the kaggle package so it looks like some new release messed it up.

Repro:
```
pyenv virtualenv testkaggle
pyenv activate testkaggle
pip install kaggle
# check existence of unexpected `src` package
export KAGGLE_PACKAGE_PATH=$(pip show kaggle | grep Location | cut -d ' ' -f 2)
cat $KAGGLE_PACKAGE_PATH/src/setup.py 
```

If you run into this issue, you can quickfix your version to `kaggle==1.6.10`

**Comment by jmasukawa** [comment]
@philkuz Sorry about that. I've opened a pull request to fix that issue: https://github.com/Kaggle/kaggle-api/pull/568

And I also cut a new release on PyPi: https://pypi.org/project/kaggle/1.6.12/

If you run `pip install --upgrade kaggle` or `pip install kaggle==1.6.12` the latest release should not include our `src` directory. `pip` should also remove any of our lingering files from `src` (while leaving anything already there alone).

Sorry about that!
