### ISSUE TITLE
Add Utility Script is Malfunctioning

### ISSUE THREAD

**Issue by john-james-ai** [Kaggle/kaggle-api#570]
When attempting to add a utility script into a notebook, the 'Add Data' window is rendered (on the right); however, no utility scripts are listed. The 'Add Data' window is essentially blank.

**Comment by jplotts** [comment]
Hi @john-james-ai - it seems like you're referring File menu option in the Kaggle web UI?  We're in the process of removing that menu option, but you can still add utility scripts in the right hand panel under "Add Input".  Hope that helps!
