### ISSUE TITLE
403 when trying to list competition files

### ISSUE THREAD

**Issue by DamonShahrivar** [Kaggle/kaggle-api#577]
Getting 403 when i am trying to list files of a previously entered competition.
I have also deleted and re issued a new token.

![Screenshot 2024-05-13 003844](https://github.com/Kaggle/kaggle-api/assets/7365819/a3393020-8534-438d-9df2-dff6ed84edc2)

**Comment by stevemessick** [comment]
Have you installed the credentials? See:
https://github.com/Kaggle/kaggle-api/blob/main/docs/README.md#api-credentials

**Comment by stevemessick** [comment]
Sorry for the noise. I see in your screenshot that authentication was successful.

According to the docs for `competition_list_files()` the argument should be the competition name, not its URL. Try changing that and let us know if that helps.

**Comment by DamonShahrivar** [comment]
Yeah it worked!
