### ISSUE TITLE
jigsaw-unintended-bias-in-toxicity-classification leaderboard request returns wrong information

### ISSUE THREAD

**Issue by thesofakillers** [Kaggle/kaggle-api#584]
Try running

```
kaggle competitions leaderboard jigsaw-unintended-bias-in-toxicity-classification --show -v
```

You will get a leaderboard with every single team having a score of `0.00000`.

This is obviously different from the actual leaderboard shown online: https://www.kaggle.com/c/jigsaw-unintended-bias-in-toxicity-classification/leaderboard

The same command works fine for other competitions. Something is broken for this specific competition it seems.

**Comment by stevemessick** [comment]
Thanks for the report. After taking a quick look we think this is a problem in the server, not the Python client. We have an internal tracking issue for it.

**Comment by stevemessick** [comment]
@thesofakillers This has been fixed and I verified that the scores are now included. Thanks @dster2 !
