### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by shraddha01032000** [Kaggle/kaggle-api#585]
Hi, can you please tell me where I can get the dataset for this project? 
Thank you!

**Comment by yashu1wwww** [comment]
https://medium.com/@Yashu_Krish11/first-create-a-kaggle-datasets-folder-in-google-drive-4342c679b46f
check it...

**Comment by shraddha01032000** [comment]
Hi Yashawanth, Thank you for replying to my query. I just wanted to ask if
I can get your dataset directly as I wanted to do my dissertation using the
dataset or if you have any new e-commerce dataset that would also be
helpful. I am doing my dissertation on the topic of Data-driven
decision-making in e-commerce using generative AI. Hence if you could help
me in this in any way would be appreciated.

Thanks and regards
Shraddha Kumbhar.

**Comment by shraddha01032000** [comment]
I am not bale to download the dataset even after entering my credentials of kaggle can you please help?
Thank you!

**Comment by stevemessick** [comment]
@shraddha01032000 This project does not have a dataset. This project is the Kaggle public API, which allows much of the Kaggle platform to be accessed as Python code. I suggest posting a question in one of the discussion forums, possibly General or Getting Started.
https://admin.kaggle.com/discussions
