### ISSUE TITLE
OLAP integration for scalable analytics

### ISSUE THREAD

**Issue by derak-isaack** [Kaggle/kaggle-api#588]
Can there be a feature for handling large datasets? By this, I mean integrating with `OLAP databases` to perform heavy analytical tasks. A typical scenario involves loading a 300 MB data file directly into these databases without the need to download them but instead, load them directly.

**Comment by stevemessick** [comment]
I think this would need to be an enhancement to the Kaggle platform, not a Kaggle API enhancement. I suggest posting a request to https://www.kaggle.com/discussions/product-feedback
