### ISSUE TITLE
API - issue with"  kaggle: command not found error "

### ISSUE THREAD

**Issue by dskrief** [Kaggle/kaggle-api#59]
Hello.     
I need to install the Kaggle API to download my data for the competition but I am stuck here and please request for your help and guidance.   
I have a MacBook Pro OS High Sierra.
When I unsuccessfully tried launching in the command line, the following command for data collection (and from various directory location on my Mac)  :
kaggle competitions download -c home-credit-default-risk

, then I have received the  following message **** "kaggle: command not found error" **** and the « ensure that your python binaries are on your path », but I don't understand the latest message concretely.

As a reference I already did or tried the following :
- pip install --user kaggle

This placed various Kaggle files in :
-  /Users/laurxxtkrxxef/.local/bin/kaggle
- and in :  /Users/laurxxtkrxxef/.local/lib/python3.6/site-packages/kaggle-1.3.11.1.dist-info

- I also placed my credentials API as requested in  the directory  .kaggle/kaggle.json 
- And I accepted my above mentioned competition General terms and conditions.

Any help or advice would be appreciated to help me proceed.
Thank you in advance.

Best regards, Laurent

**Comment by rysteboe** [comment]
Could you please share the results of `echo $PATH`?

**Comment by dskrief** [comment]
Dear Rebecca,  I succeeded in downloading with your indication : I added the path before the command  ~/.local/bin/kaggle competitions download -c ....

And it works fine.
Thank you again.
Best regards. Laurent

**Comment by rysteboe** [comment]
If you add `~/.local/bin` to your path you shouldn't need to specify the full path to the binary.  It looks like you're on a mac?  I don't know precisely the process for that but you can google it.

**Comment by RonakDedhiya** [comment]
> Dear Rebecca, I succeeded in downloading with your indication : I added the path before the command ~/.local/bin/kaggle competitions download -c ....
> 
> And it works fine.
> Thank you again.
> Best regards. Laurent

This worked for me

**Comment by devanshuDesai** [comment]
Adding to what @dskrief said, you could permanently fix it by adding this line to your `.bashrc` or `.zshrc`:
`alias kaggle="~/.local/bin/kaggle"`
Save it, exit you RC file and run:
`bash` or `zsh` based on your file system.
