### ISSUE TITLE
Listing datasets allows 0 for `page` query parameter

### ISSUE THREAD

**Issue by anorderh** [Kaggle/kaggle-api#593]
When making HTTP requests to the following API endpoint
```
https://www.kaggle.com/api/v1/datasets/list?page=0
```

I am able to receive valid responses. This seems incorrect when referencing [the source code](https://github.com/Kaggle/kaggle-api/blob/49bbf9bff5ee937ca651371776b73c3e93c28a74/kaggle/api/kaggle_api_extended.py#L1187)
```py
if int(page) <= 0:
            raise ValueError('Page number must be >= 1')
```

My testing did not include using the CLI tool, so this may only be a server issue.

**Comment by stevemessick** [comment]
Thanks for the report. Since we do not officially support this functionality, I'm closing this issue.
