### ISSUE TITLE
Rebooting kaggle notebook instance with minimal number of packages

### ISSUE THREAD

**Issue by realharryhero** [Kaggle/kaggle-api#595]
Hello! For a competition, I want to use tools that are far outside those that are normally used, say for the most recent math-like competition, including [LEAN](https://github.com/leanprover/lean4) and many scripts. But for example, trying to use LEAN on the kaggle notebook with this code causes some errors:

<details><summary>Code </summary>
<p>

```lean
cd /kaggle/working

sudo apt-get update

set -exo pipefail

sudo apt-get install -y --install-suggests git libgmp-dev cmake ccache clang

bash -c 'curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:v4.7.0 || (echo && read -n 1 -s -r -p "Install failed, press ENTER to continue...")' 

source ~/.profile

elan self update

lake_do () {
   lake update
   lake build
}

lake new my_project
cd my_project
lake update
lake build
echo 'got here'
printf '\nrequire mathlib from /kaggle/working/mathlib4' >> ./lakefile.lean
printf 'leanprover/lean4:v4.7.0' > ./lean-toolchain
cat ./lakefile.lean
lake update
lake build
printf '\n\nimport Mathlib.Topology.Basic\n\n#check TopologicalSpace' >> ./Main.lean
lake update
lake build
lake env lean --run ./Main.lean
```

</p>
</details> 

Various other (seemingly unrelated) issues pop up with other tools I'd like to use, and I believe this is due to the extremely large amount of packages uploaded in each kaggle notebook that would normally be used for commonly-used ML packages like torch or tensorflow, etc. Is there a way to reboot a kaggle notebook into a sort-of "minimal instance" without so many packages? Thank you!

**Comment by stevemessick** [comment]
@realharryhero I don't understand your code. What language is it written in? What errors are you seeing?

**Comment by stevemessick** [comment]
@realharryhero Thanks for the additional info! What you're asking for is a fairly large change to the platform. It isn't something that can be addressed by `kaggle-api`. To get better visibility of your request, I suggest you post a topic in our product feedback forum:
https://www.kaggle.com/discussions/product-feedback

Doing so will also make it more visible to other Kaggle users, which might help with allocation of engineering resources.
