### ISSUE TITLE
Unauthorized problem

### ISSUE THREAD

**Issue by weichencoder** [Kaggle/kaggle-api#60]
I have download the kaggle.json file and put it in the right place. but it still report a problem like this:

'Unauthorized: you must download an API key from https://www.kaggle.com/<username>/account
Then put kaggle.json in the folder /kaggle.json'

Maybe I think I didn't set the shell environment variable. In the readme.md , second part API credentials, how can I set the environment variable.?

'You can define a shell environment variable KAGGLE_CONFIG_DIR to change this location to $KAGGLE_CONFIG_DIR/kaggle.json (on Windows it will be %KAGGLE_CONFIG_DIR%\kaggle.json).'

when I don't set evironment variable, it report this:

'Unauthorized: you must download an API key from https://www.kaggle.com/<username>/account
Then put kaggle.json in the folder $/kaggle.json'

**Comment by rysteboe** [comment]
What directory did you put it in?  On a unix system, you should be able to, in most cases, do `mkdir ~/.kaggle` and download the API key to that directory. You don't need to set the environmental variable - that is entirely optional.

**Comment by weichencoder** [comment]
@rysteboe I put it in 3 places, /, /kaggle.json(folder), ~/.kaggle.

**Comment by weichencoder** [comment]
@rysteboe when I don't set evironment variable, it report this:

'Unauthorized: you must download an API key from https://www.kaggle.com//account
Then put kaggle.json in the folder $/kaggle.json'

**Comment by rysteboe** [comment]
Did you install kaggle with `sudo`?  If so, it's looking for your root home directory, and you would need to use kaggle as root all of the time.  If that's what you did, try `sudo pip uninstall kaggle` followed by `pip install --user kaggle`

**Comment by rysteboe** [comment]
Closing this due to no responses for a month.

**Comment by YerongLi** [comment]
This does not work.
