### ISSUE TITLE
OSError: Could not find kaggle.json.

### ISSUE THREAD

**Issue by ElNino9495** [Kaggle/kaggle-api#617]
I keep getting this error when I try to download some datasets, even though I  have already added the json file to my kaggle directory

 File "/Users/rohitsuresh/miniconda3/envs/pytorch/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/Users/rohitsuresh/miniconda3/envs/pytorch/lib/python3.11/site-packages/kaggle/__init__.py", line 7, in <module>
    api.authenticate()
  File "/Users/rohitsuresh/miniconda3/envs/pytorch/lib/python3.11/site-packages/kaggle/api/kaggle_api_extended.py", line 407, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /Users/rohitsuresh/.kaggle. Or use the environment method. See setup instructions at https://github.com/Kaggle/kaggle-api/

**Comment by stevemessick** [comment]
@ElNino9495 What do you see when you do this?
```bash
ls -l /Users/rohitsuresh/.kaggle
```

**Comment by Kking112** [comment]
Having the same issue.

**Comment by ElNino9495** [comment]
I was able to resolve the issue, I had not uninstalled the kaggle directory properly before reinstalling it again.

**Comment by ElNino9495** [comment]
mkdir -p ~/.kaggle
    mv /path/to/kaggle.json ~/.kaggle/
    chmod 600 ~/.kaggle/kaggle.json


@Kking112 make sure to run these commands

**Comment by stevemessick** [comment]
@ElNino9495 Thanks for the update! @Kking112 If you are still having problems, please open a new issue with more details, and try the suggestions @ElNino9495 made.
