### ISSUE TITLE
Bad zip file?

### ISSUE THREAD

**Issue by EstherNgamata** [Kaggle/kaggle-api#619]
Dataset URL: https://www.kaggle.com/datasets/brandao/Diabetes

1507 try:
   1508     with zipfile.ZipFile(outfile) as z:
-> 1509         z.extractall(effective_path)
   1510 except zipfile.BadZipFile as e:
   1511     raise ValueError(
   1512         'Bad zip file, please report on '
   1513         '[www.github.com/kaggle/kaggle-api](https://www.github.com/kaggle/kaggle-api)', e)

**Comment by bzm10** [comment]
The zipfile.BadZipFile error indicates that the downloaded file is either corrupted or not a valid .zip file.

**Comment by stevemessick** [comment]
@EstherNgamata What `kaggle` command did you use? Is it reproducible for you?

When I do `kaggle datasets download brandao/Diabetes --unzip` I get two files, no errors.
