### ISSUE TITLE
Cannot submit with API to a late submission competition

### ISSUE THREAD

**Issue by gonzalezJohnas** [Kaggle/kaggle-api#621]
Hello,  

# Problem description
I have been trying to use the kaggle API to do a submission for the competition: 
https://www.kaggle.com/competitions/dog-breed-identification
 However, I got _could not submit to competition_ error, but if I do it through the competition page it works.

I tested on other competition which are also in **late submission** and it works from the API.

Could it be possible to know why some competition can be submitted through the API and some no ? 

In general it is possible to submit to late submission with the API ?

**Comment by stevemessick** [comment]
The message `Could not submit to competition` is printed after a failed upload attempt. There should have been another error message printed before that, although it might not look like an error. See if you can find the other error message and paste it here. If t looks like a transient problem then perhaps you could re-try your submission.

**Comment by gonzalezJohnas** [comment]
Thank you for your quick answer, unfortunately I don't have any other message printed before this. This is the reason I am asking if there is known reasons of why some competitions cannot be submitted through the API and only from the competition page on a browser.

**Comment by stevemessick** [comment]
As I mentioned before, the submission failed to upload. There should be another message printed that says what went wrong. Can you redo the upload then copy the command and everything printed after it, then paste that here, please?
