### ISSUE TITLE
Kernel metadata file contains wrong dataset source property 

### ISSUE THREAD

**Issue by devstermarts** [Kaggle/kaggle-api#633]
Hello team!

Minor finding when creating **kernel_metadata.json** with `kaggle kernels init`, the preset file lists `"dataset_sources": [],` as property for dataset, while it should be `"dataset_data_sources": [],`  (see: https://github.com/Kaggle/kaggle-api/blob/main/docs/KernelPushRequest.md). 

Regards, Martin

**Comment by stevemessick** [comment]
Thanks for the report. However, for some reason, the file uses `dataset_sources` but the CLI [renames](https://github.com/Kaggle/kaggle-api/blob/192c7e68a316ff532dc1a190feff81e99b776e2a/src/kaggle/api/kaggle_api_extended.py#L2354) it to `dataset_data_sources` when doing a `push`. So this is actually working as intended, even though it is a bit confusing.
