### ISSUE TITLE
403 - Forbidden - Permission 'datasets.update' was denied

### ISSUE THREAD

**Issue by MH0386** [Kaggle/kaggle-api#642]
Hi,

I am trying to upload my dataset. It is not part of a competition. I can't upload; even though I just got a new API from my profile.

input:
```
kaggle d version -r tar -m https://github.com/MH0386/seismic_data/commit/${{ github.sha }}
```
output:
```
Upload successful: data.tar (3GB)
403 - Forbidden - Permission 'datasets.update' was denied
```

**Comment by MH0386** [comment]
Sorry for annoying you, It was due to an outdated dataset-metadata.json

**Comment by ai-nikolai** [comment]
@MH0386 How exactly did you fix this? I am running into the same issue?

What needs to be updated in the dataset-metadata.json?
