### ISSUE TITLE
model_sources are ignored in Kaggle kernel push

### ISSUE THREAD

**Issue by yitang** [Kaggle/kaggle-api#643]
I'm using Kaggle API version 1.6.17. I noticed the `model_sources` field in the kernel-metadata.json file is ignore when using` kaggle kernel push` CLI command. I tried it both with creating new kernels, and editing existing kernels.

**Comment by stevemessick** [comment]
Thanks for the report @yitang !

Could you make a test notebook that repros this problem and add me (stevemessick on Kaggle) as a collaborator? I looked through the code, both client and server, and it looks like it should be getting handled.

**Comment by yitang** [comment]
@stevemessick  i added you to the testing notebook and model as a collaborator. not sure if it is matters but both notebook and model are private. 

i just tried it again to replicate the issue: 
1.  pull the kernels
2. edit the metadata.json, add the model_sources field, 
3. push the kernel
4. open the kernel on kaggle website

the model i added in step 2 is missing in the input field.

**Comment by stevemessick** [comment]
Thanks @yitang. Could you add a link to your testing notebook?

We'll look into this soon.

**Comment by yitang** [comment]
Here's the link. https://www.kaggle.com/code/yimacs/test-kaggle-api/

**Comment by stevemessick** [comment]
@yitang It turns out, you were just (un)lucky! If you had used almost any framework except "Other" it would have worked. The server didn't properly handle that one framework (and a couple other recent additions). I have a fix in the works and it should be live on the server in a day or two. Thanks for finding this problem!

**Comment by yitang** [comment]
Thanks @stevemessick going to test it in weekend.
