### ISSUE TITLE
Add support for accessing public web API with API credentials

### ISSUE THREAD

**Issue by swaptr** [Kaggle/kaggle-api#652]
It would be highly beneficial if parts of the public web API (`kaggle.com/api/i/`) could be accessible using API credentials. Enabling this would unlock critical functionality, including:

- Fetching output and events of currently running kernels.
- Accessing metadata for datasets.
- Retrieving public and personal user metadata.

**Comment by stevemessick** [comment]
@swaptr Please open new issues to request new features to be added to `kaggle-api`. It would help us with prioritization if you could include a description of how the new features would be used.

Also, please see these datasets that may have some of the data you want:
https://www.kaggle.com/datasets/kaggle/meta-kaggle
https://www.kaggle.com/datasets/kaggle/meta-kaggle-code
