### ISSUE TITLE
kaggle kernels output not downloading all folders

### ISSUE THREAD

**Issue by LeonShams** [Kaggle/kaggle-api#664]
## Problem

The `kaggle kernels output [kernel]` does not always download all folders in the kernel.

## Steps to reproduce

Take a look at: https://www.kaggle.com/code/motono0223/js24-preprocessing-create-lags/output

There are two folders: `training.parquet` and `validation.parquet`

However running the command `kaggle kernels output motono0223/js24-preprocessing-create-lags -p /path/to/dest` only downloads the contents of `training.parquet`

**Comment by stevemessick** [comment]
Downloading output files is limited to the first 500 currently. We plan to add pagination so that additional files can be downloaded.
