### ISSUE TITLE
How to download data on kaggle kernel and save in mongoDb

### ISSUE THREAD

**Issue by leecheukwing** [Kaggle/kaggle-api#69]
Some data has API code such as kaggle datasets download -d madhab/jobposts. However, I cannot find the code on kaggle dataset?It seems that I need to create new kernel? If I need to create,what should i pass in?Thx
PS: I have already download kaggle.

**Comment by rysteboe** [comment]
I'm not sure what you mean.  The API commands are available in [the README](https://github.com/Kaggle/kaggle-api), including how to work with datasets.  If you want a kernel about a dataset, then you'll either need to find one that uses that dataset through the website or through the API (`kaggle kernels list --dataset madhab/jobposts`), or you'll need to write one yourself.  If you've never written a kaggle kernel before, I would suggest playing around with it on the website before using the API to manage it.  If you have a kernel already, you can do `kaggle kernels pull -k {username}/{kernel-id} -p /path/to/download --metadata`  to pull the code down, and `kaggle kernels push -p /path/to/kernel` to push new code once you've made changes.

Please be aware that for the particular dataset that you mentioned, there is an outstanding bug that will not be fixed until Monday.  See https://github.com/Kaggle/kaggle-api/issues/68

**Comment by rysteboe** [comment]
Closing due to no response.
