### ISSUE TITLE
Download competition data without creating extra directory

### ISSUE THREAD

**Issue by alejandrodumas** [Kaggle/kaggle-api#7]
Hi! Thanks for kaggle-api. 
When I use 
``kaggle competitions download -c competition-name --wp``
The CLI stores all my data inside a dir with the competition name, but I would like to store the data in the working dir, without the creation of the extra dir with the competition name.

Most of the time I have a folder with ./data in it and I want to store the datasets there, not in 
./data/competition-name.
Is it possible?
Thanks

**Comment by mxbi** [comment]
I have the same annoyance and others do too. I can make a PR to fix this.

**Comment by timoboz** [comment]
Good point, thanks for reporting! Currently both the -p (path) and -w (working path) parameters both append the competition name / dataset name to the specified path and I can see how that's probably not what most people want. 

I'll add it to the feature list for the next release, which should be coming up shortly.
