### ISSUE TITLE
Big problems 

### ISSUE THREAD

**Issue by leecheukwing** [Kaggle/kaggle-api#70]
When i pass from bq_helper import BigQueryHelper and its functions.It displays ModuleNotFoundError: No module named 'bq_helper' and NameError: name 'BigQueryHelper' is not defined.Why? Therefore, I download Google Cloud Platform than i displays:
httplib2.python2.httplib2.SSLHandsharkeError: [SSL:CERTIFCATE_VERIFY_FAILED] cer...
Failed to install.
Why?Someone can help me ?thx

**Comment by rysteboe** [comment]
The API doesn't support working with bigquery datasets.  Unfortunately, we have no plans to lift this limitation in the near future.
