### ISSUE TITLE
When i run the code, jupter notebook said ModuleNotFoundError: No module named 'bq_helper',why?

### ISSUE THREAD

**Issue by leecheukwing** [Kaggle/kaggle-api#73]
from bq_helper import BigQueryHelper .I add bq_helper in C: .When i run the code jupter notebook said ModuleNotFoundError: No module named 'bq_helper',why?

**Comment by rysteboe** [comment]
Do you have this problem on the Kaggle website?

**Comment by leecheukwing** [comment]
My problems :
![image](https://user-images.githubusercontent.com/41764574/43524495-0abc0a00-95d2-11e8-9557-1b7d07b7fac7.png)
![image](https://user-images.githubusercontent.com/41764574/43524525-19968a8c-95d2-11e8-9009-9cf4aa635753.png)

**Comment by rysteboe** [comment]
Closing due to no response in four weeks.

**Comment by npatten1** [comment]
having the same issue

**Comment by chnegiz-su** [comment]
I am having the same issue, there seems to be no current information on the topic

**Comment by x1155665** [comment]
If you do not use bq_helper on the Kaggle website, please check the [BigQuery_Helper](https://github.com/SohierDane/BigQuery_Helper) repo. @chnegiz-su @npatten1
