### ISSUE TITLE
Model submission API

### ISSUE THREAD

**Issue by jeongyoonlee** [Kaggle/kaggle-api#75]
Currently there is no API for model submission. For competitions that require model submissions, the file upload over the webpage is troublesome especially when the file size is large (e.g. Zillow Prize 2 requires model submissions including serialized models and external data, and my submission file is over 2GB).

**Comment by rysteboe** [comment]
Discussing this with the team to figure out what this would look like.  I don't think it will be particularly complicated, though.  Will update this when I know a rough timeline for implementation.

**Comment by Philmod** [comment]
Kaggle now has a Models section (https://www.kaggle.com/models), soon users will be able to create their own.
