### ISSUE TITLE
Download leaderboard raw data?

### ISSUE THREAD

**Issue by deargle** [Kaggle/kaggle-api#8]
Hi, I'm looking for a way to programmatically download the raw data from the leaderboard of a competition. I'm teaching a class and I'd like to set up a script to do the download one a day, or something like that. If possible I'd like to avoid Selenium, although at the moment I don't see another option because the login page doesn't work without javascript :-(

Possible to hack these api calls to download competition raw data?

**Comment by deargle** [comment]
Here's my dirty hack for how I figured out how to do it. API would be cleaner, of course.

```python
import requests
username = ''
password = ''
competition_id='3136' #the code for titanic

session = requests.Session()
get_me = 'https://www.kaggle.com/account/login?ReturnUrl=%2fc%2f' + competition_id + '%2fpublicleaderboarddata.zip'
response = session.get(get_me) #call it once to get the request verification cookie
payload = {'username': username,' password':password, '__RequestVerificationToken': session.cookies.get('__RequestVerificationToken')}
r = requests.post(get_me, data=payload)
with open('the-zip.zip', 'wb') as f:
    f.write(r.content)

```

**Comment by deargle** [comment]
Sigh so you add a captcha to the login screen. Back to requesting that this functionality be added to the API.

**Comment by deargle** [comment]
I would like to ask, what is the point of a captcha on the Kaggle login page? It can't be that you're trying to limit bandwidth, because you already provide API access. If you're trying to prevent batch account creation, why not only have the captcha on the account registration page?

**Comment by mxbi** [comment]
I believe the captcha was a temporary security measure to mitigate an ongoing attack against accounts.

However, for your specific problem, I would login in a browser like chrome and save the sessionID cookie. Then, that cookie can be used indefinitely to make logged in requests from eg. a python script. I do this personally using the cookies.txt chrome extension to save the cookies (https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en) and then simply doing:

`wget --load-cookies cookies.txt [URL]` which will download the URL as a logged in user.

Hope that helps.

**Comment by rysteboe** [comment]
I'm picking up this project for the Kaggle team.  This is on my todo list, but I don't have an ETA at this point.

**Comment by deargle** [comment]
Thanks, appreciated.

**Comment by rysteboe** [comment]
You can now do `kaggle competitions leaderboard -d` to download the full leaderboard as of `1.3.9`.  See the readme for a bit more information.

**Comment by Ural0203** [comment]
Hi, I was wondering if we can download more information such as the number of entries and team member details using the API. Is there a way for that? Thanks a lot!
