### ISSUE TITLE
Integration with CI

### ISSUE THREAD

**Issue by vsoch** [Kaggle/kaggle-api#85]
Hey kaggle team! 

I’m wanting to set up some cool workflows that will have it possible to collaborate on, for example a github repository and then when a pull request is merged a data set is updated and then pushed to Kaggle as well.  It seems like the primary avenue for interacting with the API is personal tokens, and I’m wondering if there  is a way to somehow create a more secured or official connection to github or some kind of special token that expects a particular web hook? Or for an organization?  Basically I’d want to have a specific permission scoped for a Kaggle repo from a specific location and associated with an organization and not my entire user space. I’m happy to help however I can and am grateful to get this discussion going. Happy Monday!

**Comment by rysteboe** [comment]
The problem with CI is that it needs to be linked with our internal CICD flow.  There was a recent issue where a backend performance change broke part of the kernels API - sanity tests would solve this.  However, that by necessity makes it impossible to make the CICD flow for the API visible to everyone else.  In addition, I'm primarily working on redoing our CICD for Kaggle as a whole, which means that any work in this space is just going to have to be redone soon.  

So, I dunno.  It's certainly entirely possible to have a Jenkins stood up with a secret for the API token and have the tests use that, but I honestly can't put the time into something like that right now, given that it will need to be changed again soon anyway.

I recognize that this is not particularly helpful :(

**Comment by vsoch** [comment]
hey @rysteboe you are working really hard! I think my question wasn't clear, I'm not interested here about the CI for the library itself, but rather that a user (like myself) could easily hook up **their** repository on CircleCI, TravisCI, to do some kind of testing and then upload a dataset. The need would be for a native integration of Kaggle with one of the CI, or a different kind of organization token that the user could get for his/her organization to put into CircleCI or Travis. Does that make sense?

**Comment by rysteboe** [comment]
re: native CI integration - something to look into once kernels integration is a thing (as in, being able to use the API from a kernel).  The implementation would probably be similar.  Hoping to at least design this next quarter, but implementation ETA is ... shakier.
re: a scoped token - this would probably be an involved effort.  I like the idea (there are other things I want to do to make tokens more flexible, too), but they're unfortunately at the P2 level with a bunch of P0's hanging above them.

**Comment by vsoch** [comment]
No worries! I'm going to be making an [openbases](https://openbases.github.io) builder that hooks into kaggle, and actually have tooons of other things to develop before that so I'm grateful for a longer ETA. Please keep me in the loop, and let me know when the time comes if I can help out.
