### ISSUE TITLE
Got error ，when i try to create datasets via kaggle api

### ISSUE THREAD

**Issue by mrlonely001** [Kaggle/kaggle-api#89]
First , I run this " kaggle datasets init -p D:\kaggle\PredictFutureSales\data"
then I run this  "kaggle datasets create -p D:\kaggle\PredictFutureSales\data"
and I got this error :
'file' object has no attribute 'readable'
Upload unsuccessful: test.csv
Dataset creation error: Please specify at least one file.

btw , I have give the test.csv all permission

**Comment by rysteboe** [comment]
What version of the API are you using and what does your metadata file look like?

**Comment by mrlonely001** [comment]
I use the Kaggle API 1.4.7.1 ，and  matadata file is :
{
  "title": "My Awesome Dataset", 
  "subtitle": "My awesomer subtitle",
  "description": "My awesomest description",
  "id": "changtaoyin/my-awesome-dataset", 
  "licenses": [{"name": "CC0-1.0"}],
  "resources": [
    {
      "path": "test.csv",
      "description": "This is my awesome data!"
    }
  ],
  "keywords": [
    "beginner",
    "tutorial"
  ]
}

**Comment by mrlonely001** [comment]
Someone help me？

**Comment by rysteboe** [comment]
It's possible something is going wrong with relative paths (although I thought I had fixed all of those issues).  Try `cd D:\kaggle\PredictFutureSales\data` and running the command from there.  Make sure that `test.csv` is in the same directory as `dataset-metadata.json`.

**Comment by KamleshJethwani** [comment]
Are you sure that the file/data is present in the path that you have provided as the meaning of the error is, It required at least one data set to process.

**Comment by HenryCaiHaiying** [comment]
I have the same problem, my Kaggle version is also Kaggle API 1.4.7.1

**Comment by HenryCaiHaiying** [comment]
I already 'cd' to the folder where both metadata and data file are in
