### ISSUE TITLE
Not able to download files - it says already downloaded

### ISSUE THREAD

**Issue by sahilk16** [Kaggle/kaggle-api#90]
I was trying to use the kaggle-cli to download a specific dataset but not able to do so. 

I use kg download -u username -p password -c competitionname to download but it dosent work, It says 

downloading https://www.kaggle.com/c/digit-recognizer/download/train.csv
train.csv already downloaded !

downloading https://www.kaggle.com/c/digit-recognizer/download/test.csv
test.csv already downloaded !

downloading https://www.kaggle.com/c/digit-recognizer/download/sample_submission.csv
sample_submission.csv already downloaded !. 

Cannot see the file, i tried using an empty folder but it doesnt work. I also tried uninstalling and installing kaggle-cli again.

**Comment by rysteboe** [comment]
`kaggle-cli` is a different project that is not maintained by Kaggle.  Please report issues here https://github.com/floydwch/kaggle-cli or switch to using this client (`pip install kaggle`).
