### ISSUE TITLE
Still get command not found: kaggle, after run 'pip install --user kaggle'

### ISSUE THREAD

**Issue by yourSylvia** [Kaggle/kaggle-api#91]
The first time I tried to install it, there is a warning of the files "tqdm", "unidecode" and another file (don't remember the exact name and the exact warning). However, it still showed "successfully install kaggle", that's why I ignore this warning.

Then I tried "kaggle" in the command line and got "command not found: kaggle".

I tried to uninstall kaggle and delete the three files(path: ~/Library/Python/2.7/bin) with the warning and reinstall it, I get:
Collecting kaggle
  Using cached https://files.pythonhosted.org/packages/c6/78/832b9a9ec6b3baf8ec566e1f0a695f2fd08d2c94a6797257a106304bfc3c/kaggle-1.4.7.1.tar.gz
Requirement already satisfied: urllib3<1.23.0,>=1.15 in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from kaggle) (1.22)
Requirement already satisfied: six>=1.10 in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from kaggle) (1.11.0)
Requirement already satisfied: certifi in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from kaggle) (2018.8.24)
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from kaggle) (1.5)
Requirement already satisfied: requests in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from kaggle) (2.19.1)
Requirement already satisfied: tqdm in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from kaggle) (4.25.0)
Requirement already satisfied: python-slugify in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from kaggle) (1.2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from requests->kaggle) (2.7)
Requirement already satisfied: Unidecode>=0.04.16 in /Users/sylviameow/Library/Python/2.7/lib/python/site-packages (from python-slugify->kaggle) (1.0.22)
Installing collected packages: kaggle
  Running setup.py install for kaggle ... done
Successfully installed kaggle-1.4.7.1

But 'kaggle' still can't work. Can anyone help? Thanks.

In addition, there is no folder ~/.kaggle/ after install.

**Comment by rysteboe** [comment]
Python 2 support has fallen by the wayside.  I'll update the README to indicate that we no longer support it.

**Comment by yourSylvia** [comment]
Thanks. How can I change the pip install path to python3?

Regards

Rebecca Ysteboe <notifications@github.com> 于2018年9月10日周一 下午9:07写道：
