### ISSUE TITLE
Dataset Not Found using Kaggle-API

### ISSUE THREAD

**Issue by manishprasadthapliyal** [Kaggle/kaggle-api#92]
Hi,
I am using kaggle version : Kaggle API 1.4.7.1
still getting not found issue for available dataset.

command : !kaggle competitions download -c tgs-salt-identification-challenge
result : 404 - Not Found

**Comment by axlesor** [comment]
Possibly kaggle API is down all day Sep 16th since I cannot able to download/list any dataset  from colab!

**Comment by manishprasadthapliyal** [comment]
It is working now :)

**Comment by rysteboe** [comment]
We had some site issues yesterday.  Looks like everything is cleared up now?  (And either way, not an API bug in this case.)
