### ISSUE TITLE
kaggle command fails with google colaboratory

### ISSUE THREAD

**Issue by R7038XX** [Kaggle/kaggle-api#97]
Executing the following command will result in an error.
"kaggle.json" is right under google drive.
What is the cause?

[https://colab.research.google.com/drive/1BhbII5rQTqfxLK0aYusfHReWJpNSm7XD](url)

`
!pip install kaggle
`
> Collecting kaggle
>     :
> Successfully installed Unidecode-1.0.22 kaggle-1.4.7.1 python-slugify-1.2.6

`from googleapiclient.discovery import build`
`import io, os`
`from googleapiclient.http import MediaIoBaseDownload`
`from google.colab import auth`
`auth.authenticate_user()`
`drive_service = build('drive', 'v3')`
`results = drive_service.files().list(q="name = 'kaggle.json'", fields="files(id)").execute()`
`kaggle_api_key = results.get('files', [])`
`filename = "~/.kaggle/kaggle.json"`
`os.makedirs(os.path.dirname(filename), exist_ok=True)`
`request = drive_service.files().get_media(fileId=kaggle_api_key[0]['id'])`
`fh = io.FileIO(filename, 'wb')`
`downloader = MediaIoBaseDownload(fh, request)`
`done = False`
`while done is False:`
`    status, done = downloader.next_chunk()`
`    print("Download %d%%." % int(status.progress() * 100))`
`os.chmod(filename, 600)`

> Download 100%

`!kaggle competitions list`

> Traceback (most recent call last):
>   File "/usr/local/bin/kaggle", line 7, in <module>
>     from kaggle.cli import main
>   File "/usr/local/lib/python3.6/dist-packages/kaggle/__init__.py", line 23, in <module>
>     api.authenticate()
>   File "/usr/local/lib/python3.6/dist-packages/kaggle/api/kaggle_api_extended.py", line 110, in authenticate
>     self._load_config(config_data)
>   File "/usr/local/lib/python3.6/dist-packages/kaggle/api/kaggle_api_extended.py", line 149, in _load_config
>     raise ValueError('Error: Missing %s in configuration.' % item)
> ValueError: Error: Missing username in configuration.

**Comment by R7038XX** [comment]
The file seems to be present.

`%cd .kaggle`
`!ls`
> kaggle.json

**Comment by R7038XX** [comment]
Hello rysteboe,

The contents are as follows.

>{"username":"xxx","key":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}

**Comment by R7038XX** [comment]
Hello amartya-k,

That file is stored correctly.

`!ls -a`
> .config .kaggle sample_data

`%cd .kaggle`
`!ls -a`
> kaggle.json

**Comment by corrieann** [comment]
Can you try changing filename above to "/root/.kaggle/kaggle.json"?

https://colab.research.google.com/gist/corrieann/7b1e460d3381bf058627bdaa64840122/kaggle-api.ipynb

**Comment by amartya-k** [comment]
@corrieann 
Try this [https://stackoverflow.com/questions/51958553/error-while-importing-kaggle-dataset-on-colab](url)

**Comment by R7038XX** [comment]
Hello corrieann,

Thanks to you I solved it!

**Comment by CaduceusInc** [comment]
Thanks amartya-k. Your suggestion solved it for me

**Comment by theProcrastinatr** [comment]
I'm getting a strange behaviour trying this with `!` commands.

Generally, I like to put all the bash commands in one cell like:
```
! cp /content/drive/MyDrive/kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

! pip install -q kaggle

! kaggle datasets download -d link/to/dataset

! mkdir data/
! unzip -q dataset_name.zip -d data/
! rm dataset_name.zip
```

 In the above case, this gives an error `cp: cannot create regular file '/root/.kaggle/': Not a directory` and I've checked that `.kaggle/` is in fact present in the `/root/`. However when I try to run `! cp /content/drive/MyDrive/kaggle.json ~/.kaggle/` in a separate cell, it works just fine and so does everything else.

Please let me know if someone else is facing similar issue.
